// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [['Greeting Message', '"Hello " + Full Name']];

describe('FEEL TCK / 0001-input-data-string', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Testing valid input', () => {
    const ctx = run({ 'Full Name': 'John Doe' });
    expect(aeq(n(ctx['Greeting Message']), 'Hello John Doe'), 'Greeting Message').toBe(true);
  });
});
