// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [['Yearly Salary', '12 * Monthly Salary']];

describe('FEEL TCK / 0002-input-data-number', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Testing valid input', () => {
    const ctx = run({ 'Monthly Salary': 10000 });
    expect(aeq(n(ctx['Yearly Salary']), 120000), 'Yearly Salary').toBe(true);
  });
});
