// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['Decision1', '.872'],
  ['Decision2', '-.872'],
  ['Decision4', '50'],
  ['Decision5', '-50'],
  ['Decision7', '125.4321987654'],
  ['Decision8', '-125.4321987654'],
];

describe('FEEL TCK / 0101-feel-constants', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Tests FEEL decimal number constant', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision1), 0.872), 'Decision1').toBe(true);
  });
  it('002: Tests FEEL negative decimal number constant', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision2), -0.872), 'Decision2').toBe(true);
  });
  it('004: Tests FEEL number constant', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision4), 50), 'Decision4').toBe(true);
  });
  it('005: Tests FEEL negative number constant', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision5), -50), 'Decision5').toBe(true);
  });
  it('007: Tests FEEL decimal number constant', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision7), 125.4321987654), 'Decision7').toBe(true);
  });
  it('008: Tests FEEL negative decimal number constant', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision8), -125.4321987654), 'Decision8').toBe(true);
  });
});
