// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['Decision1', '"foo bar"'],
  ['Decision2', '"šomeÚnicodeŠtriňg"'],
  ['Decision3', '"横綱"'],
  [
    'Decision4',
    '"thisIsSomeLongStringThatMustBeProcessedSoHopefullyThisTestPassWithItAndIMustWriteSomethingMoreSoItIsLongerAndLongerAndLongerAndLongerAndLongerTillItIsReallyLong"',
  ],
];

describe('FEEL TCK / 0102-feel-constants', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Tests FEEL string constants', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision1), 'foo bar'), 'Decision1').toBe(true);
  });
  it('002: Tests FEEL unicode string constant', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision2), 'šomeÚnicodeŠtriňg'), 'Decision2').toBe(true);
  });
  it('003: Tests FEEL unicode string constant', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision3), '横綱'), 'Decision3').toBe(true);
  });
  it('004: Tests FEEL long string constant', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx.Decision4),
        'thisIsSomeLongStringThatMustBeProcessedSoHopefullyThisTestPassWithItAndIMustWriteSomethingMoreSoItIsLongerAndLongerAndLongerAndLongerAndLongerTillItIsReallyLong',
      ),
      'Decision4',
    ).toBe(true);
  });
});
