// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['Decision1', '10+5'],
  ['Decision2', '-10+-5'],
  ['Decision3', '(-10)+(-5)'],
  ['Decision4', '10-5'],
  ['Decision5', '-10--5'],
  ['Decision6', '(-10)-(-5)'],
  ['Decision7', '(10+20)-(-5+3)'],
  ['Decision8', '10*5'],
  ['Decision9', '-10*-5'],
  ['Decision10', '(-10)*(-5)'],
  ['Decision11', '(10+5)*(-5*3)'],
  ['Decision12', '10/5'],
  ['Decision13', '-10/-5'],
  ['Decision14', '(-10)/(-5)'],
  ['Decision15', '(10+20)/(-5*3)'],
  ['Decision16', '(10+20)/0'],
  ['Decision17', '10**5'],
  ['Decision18', '10**-5'],
  ['Decision19', '(5+2)**5'],
  ['Decision20', '5+2**5'],
  ['Decision21', '5+2**5+3'],
  ['Decision22', '5+2**(5+3)'],
  ['Decision23', '10+null'],
  ['Decision24', 'null + 10'],
  ['Decision25', '10 - null'],
  ['Decision26', 'null - 10'],
  ['Decision27', '10 * null'],
  ['Decision28', 'null * 10'],
  ['Decision29', '10 / null'],
  ['Decision30', 'null / 10'],
  ['Decision31', '10 + 20 / -5 - 3'],
  ['Decision32', '10 + 20 / (-5 - 3)'],
  ['Decision33', '1.2*10**3'],
];

describe('FEEL TCK / 0105-feel-math', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Tests FEEL addition of number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision1), 15), 'Decision1').toBe(true);
  });
  it('002: Tests FEEL addition of negative number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision2), -15), 'Decision2').toBe(true);
  });
  it('003: Tests FEEL addition of negative number literals with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision3), -15), 'Decision3').toBe(true);
  });
  it('004: Tests FEEL subtraction of number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision4), 5), 'Decision4').toBe(true);
  });
  it('005: Tests FEEL subtraction of negative number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision5), -5), 'Decision5').toBe(true);
  });
  it('006: Tests FEEL subtraction of negative number literals with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision6), -5), 'Decision6').toBe(true);
  });
  it('007: Tests FEEL addition and subtraction of number literals with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision7), 32), 'Decision7').toBe(true);
  });
  it('008: Tests FEEL multiplication of number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision8), 50), 'Decision8').toBe(true);
  });
  it('009: Tests FEEL multiplication of negative number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision9), 50), 'Decision9').toBe(true);
  });
  it('010: Tests FEEL multiplication of negative number literals with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision10), 50), 'Decision10').toBe(true);
  });
  it('011: Tests FEEL addition and multiplication of number literals with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision11), -225), 'Decision11').toBe(true);
  });
  it('012: Tests FEEL division of number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision12), 2), 'Decision12').toBe(true);
  });
  it('013: Tests FEEL division of negative number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision13), 2), 'Decision13').toBe(true);
  });
  it('014: Tests FEEL division of negative number literals with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision14), 2), 'Decision14').toBe(true);
  });
  it('015: Tests FEEL addition and division of number literals with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision15), -2), 'Decision15').toBe(true);
  });
  it('016: Tests FEEL division by zero', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision16), null), 'Decision16').toBe(true);
  });
  it('017: Tests FEEL potency of number literal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision17), 100000), 'Decision17').toBe(true);
  });
  it('018: Tests FEEL negative potency of number literal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision18), 0.00001), 'Decision18').toBe(true);
  });
  it('019: Tests FEEL potency of number literal with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision19), 16807), 'Decision19').toBe(true);
  });
  it('020: Tests FEEL addition and potency of number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision20), 37), 'Decision20').toBe(true);
  });
  it('021: Tests FEEL addition and potency of number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision21), 40), 'Decision21').toBe(true);
  });
  it('022: Tests FEEL addition and potency of number literals with brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision22), 261), 'Decision22').toBe(true);
  });
  it('023: Tests FEEL addition with null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision23), null), 'Decision23').toBe(true);
  });
  it('024: Tests FEEL addition with null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision24), null), 'Decision24').toBe(true);
  });
  it('025: Tests FEEL subtraction with null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision25), null), 'Decision25').toBe(true);
  });
  it('026: Tests FEEL subtraction with null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision26), null), 'Decision26').toBe(true);
  });
  it('027: Tests FEEL multiplication with null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision27), null), 'Decision27').toBe(true);
  });
  it('028: Tests FEEL multiplication with null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision28), null), 'Decision28').toBe(true);
  });
  it('029: Tests FEEL division with null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision29), null), 'Decision29').toBe(true);
  });
  it('030: Tests FEEL division with null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision30), null), 'Decision30').toBe(true);
  });
  it('031: Tests FEEL arithmetics with spaces between number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision31), 3), 'Decision31').toBe(true);
  });
  it('032: Tests FEEL arithmetics with spaces between number literals and brakets', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision32), 7.5), 'Decision32').toBe(true);
  });
  it('033: Tests FEEL arithmetics with decimal number literals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.Decision33), 1200), 'Decision33').toBe(true);
  });
});
