// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['DecisionAnd', 'A and B'],
  ['DecisionOr', 'A or B'],
];

describe('FEEL TCK / 0106-feel-ternary-logic', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Tests ternary logic for true, true', () => {
    const ctx = run({ A: true, B: true });
    expect(aeq(n(ctx.DecisionAnd), true), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), true), 'DecisionOr').toBe(true);
  });
  it('002: Tests ternary logic for false, true', () => {
    const ctx = run({ A: false, B: true });
    expect(aeq(n(ctx.DecisionAnd), false), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), true), 'DecisionOr').toBe(true);
  });
  it('003: Tests ternary logic for null, true ', () => {
    const ctx = run({ A: null, B: true });
    expect(aeq(n(ctx.DecisionAnd), null), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), true), 'DecisionOr').toBe(true);
  });
  it('004: Tests ternary logic for true, false', () => {
    const ctx = run({ A: true, B: false });
    expect(aeq(n(ctx.DecisionAnd), false), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), true), 'DecisionOr').toBe(true);
  });
  it('005: Tests ternary logic for false, false', () => {
    const ctx = run({ A: false, B: false });
    expect(aeq(n(ctx.DecisionAnd), false), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), false), 'DecisionOr').toBe(true);
  });
  it('006: Tests ternary logic for null, false ', () => {
    const ctx = run({ A: null, B: false });
    expect(aeq(n(ctx.DecisionAnd), false), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), null), 'DecisionOr').toBe(true);
  });
  it('007: Tests ternary logic for true, null', () => {
    const ctx = run({ A: true, B: null });
    expect(aeq(n(ctx.DecisionAnd), null), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), true), 'DecisionOr').toBe(true);
  });
  it('008: Tests ternary logic for false, null', () => {
    const ctx = run({ A: false, B: null });
    expect(aeq(n(ctx.DecisionAnd), false), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), null), 'DecisionOr').toBe(true);
  });
  it('009: Tests ternary logic for null, null ', () => {
    const ctx = run({ A: null, B: null });
    expect(aeq(n(ctx.DecisionAnd), null), 'DecisionAnd').toBe(true);
    expect(aeq(n(ctx.DecisionOr), null), 'DecisionOr').toBe(true);
  });
});
