// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['Join', 'DeptTable[number = EmployeeTable[name=LastName].deptNum[1]].manager[1]'],
];

describe('FEEL TCK / 0006-join', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({
      EmployeeTable: [
        { id: '7792', deptNum: 10, name: 'Clark' },
        { id: '7934', deptNum: 10, name: 'Miller' },
        { id: '7976', deptNum: 20, name: 'Adams' },
        { id: '7902', deptNum: 20, name: 'Ford' },
        { id: '7900', deptNum: 30, name: 'James' },
      ],
      DeptTable: [
        { number: 10, name: 'Sales', manager: 'Smith' },
        { number: 20, name: 'Finance', manager: 'Jones' },
        { number: 30, name: 'Engineering', manager: 'King' },
      ],
      LastName: 'Clark',
    });
    expect(aeq(n(ctx.Join), 'Smith'), 'Join').toBe(true);
  });
});
