// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { parseDuration } from '../../../src/temporal/duration.js';
import { parseDate, parseDateTime, parseTime } from '../../../src/temporal/index.js';
import { aeq, type Ctx, n } from '../utils.js';

const _d = parseDate,
  _t = parseTime,
  _dt = parseDateTime,
  dur = parseDuration;

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['Date-Time', 'date and time(dateTimeString)'],
  ['Time', 'time(timeString)'],
  ['Date-Time2', 'date and time(Date.fromString,Time)'],
  ['Time2', 'time(Date-Time2)'],
  ['Time3', 'time(Hours,Minutes,Seconds,Timezone)'],
  ['dtDuration1', 'duration(durationString)'],
  ['dtDuration2', 'Date-Time - Date-Time2'],
  ['sumDurations', 'dtDuration1 + dtDuration2'],
  ['ymDuration2', 'years and months duration(Date-Time2,Date-Time)'],
  ['cDay', 'Date.fromString.day'],
  ['cYear', 'Date.fromString.year'],
  ['cMonth', 'Date.fromString.month'],
  ['cHour', 'Date-Time2.hour'],
  ['cMinute', 'Date-Time2.minute'],
  ['cSecond', 'Date-Time2.second'],
  ['cOffset', 'Date-Time2.time offset'],
  ['years', 'ymDuration2.years'],
  ['seconds', 'dtDuration1.seconds'],
];

describe('FEEL TCK / 0007-date-time', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({
      dateString: '2015-12-24',
      timeString: '00:00:01-01:00',
      dateTimeString: '2016-12-24T23:59:00-08:00',
      Hours: 12,
      Minutes: 59,
      Seconds: 1.3,
      Timezone: dur('-PT1H'),
      Year: 1999,
      Month: 11,
      Day: 22,
      oneHour: dur('PT1H'),
      durationString: 'P13DT2H14S',
    });
    expect(aeq(n(ctx['Date-Time']), '2016-12-24T23:59:00-08:00'), 'Date-Time').toBe(true);
    expect(aeq(n(ctx.Time), '00:00:01-01:00'), 'Time').toBe(true);
    expect(aeq(n(ctx.Time3), '12:59:01.3-01:00'), 'Time3').toBe(true);
    expect(aeq(n(ctx.dtDuration1), 'P13DT2H14S'), 'dtDuration1').toBe(true);
    expect(aeq(n(ctx.seconds), 14), 'seconds').toBe(true);
  });
});
