// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['literalSimpleList', '["a","b","c"]'],
  ['literalNestedList', '[["w","x"],["y"],["z"]]'],
  ['append1', 'append(literalNestedList,["t"])'],
  ['append2', 'append(nestedList,simpleList)'],
  ['append3', 'append(nestedList,literalSimpleList)'],
  ['append4', 'append(literalNestedList,literalSimpleList)'],
  ['flatten1', 'flatten(append1)'],
  ['flatten2', 'flatten(append2)'],
  ['flatten3', 'flatten(append3)'],
  ['flatten4', 'flatten(append4)'],
];

describe('FEEL TCK / 0009-append-flatten', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({ simpleList: ['a', 'b', 'c'], nestedList: [['w', 'x'], ['y'], ['z']] });
    expect(aeq(n(ctx.literalSimpleList), ['a', 'b', 'c']), 'literalSimpleList').toBe(true);
    expect(aeq(n(ctx.literalNestedList), [['w', 'x'], ['y'], ['z']]), 'literalNestedList').toBe(
      true,
    );
    expect(aeq(n(ctx.append1), [['w', 'x'], ['y'], ['z'], ['t']]), 'append1').toBe(true);
    expect(aeq(n(ctx.append2), [['w', 'x'], ['y'], ['z'], ['a', 'b', 'c']]), 'append2').toBe(true);
    expect(aeq(n(ctx.append3), [['w', 'x'], ['y'], ['z'], ['a', 'b', 'c']]), 'append3').toBe(true);
    expect(aeq(n(ctx.append4), [['w', 'x'], ['y'], ['z'], ['a', 'b', 'c']]), 'append4').toBe(true);
    expect(aeq(n(ctx.flatten1), ['w', 'x', 'y', 'z', 't']), 'flatten1').toBe(true);
    expect(aeq(n(ctx.flatten2), ['w', 'x', 'y', 'z', 'a', 'b', 'c']), 'flatten2').toBe(true);
    expect(aeq(n(ctx.flatten3), ['w', 'x', 'y', 'z', 'a', 'b', 'c']), 'flatten3').toBe(true);
    expect(aeq(n(ctx.flatten4), ['w', 'x', 'y', 'z', 'a', 'b', 'c']), 'flatten4').toBe(true);
  });
});
