// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['literalSimpleList', '["a","b","c"]'],
  ['literalNestedList', '[["w","x"],["y"],["z"]]'],
  ['concatenate1', 'concatenate(simpleList,literalSimpleList)'],
  ['concatenate2', 'concatenate(simpleList,flatten(nestedList))'],
  ['concatenate3', 'concatenate(literalSimpleList,flatten(nestedList))'],
  ['concatenate4', 'concatenate([literalSimpleList],literalNestedList)'],
];

describe('FEEL TCK / 0010-concatenate', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({ simpleList: ['a', 'b', 'c'], nestedList: [['w', 'x'], ['y'], ['z']] });
    expect(aeq(n(ctx.literalSimpleList), ['a', 'b', 'c']), 'literalSimpleList').toBe(true);
    expect(aeq(n(ctx.literalNestedList), [['w', 'x'], ['y'], ['z']]), 'literalNestedList').toBe(
      true,
    );
    expect(aeq(n(ctx.concatenate1), ['a', 'b', 'c', 'a', 'b', 'c']), 'concatenate1').toBe(true);
    expect(aeq(n(ctx.concatenate2), ['a', 'b', 'c', 'w', 'x', 'y', 'z']), 'concatenate2').toBe(
      true,
    );
    expect(aeq(n(ctx.concatenate3), ['a', 'b', 'c', 'w', 'x', 'y', 'z']), 'concatenate3').toBe(
      true,
    );
    expect(
      aeq(n(ctx.concatenate4), [['a', 'b', 'c'], ['w', 'x'], ['y'], ['z']]),
      'concatenate4',
    ).toBe(true);
  });
});
