// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['listContainsList', 'list contains(list1,list2)'],
  ['listContains', 'list contains(list2,string1)'],
  ['count1', 'count(list1)'],
  ['min1', 'min(numList)'],
  ['sum1', 'sum(numList)'],
  ['mean1', 'mean(numList)'],
  ['mean2', 'mean(num1,num2,num3)'],
  ['sublist12', 'sublist(list1,1,2)'],
  ['sublistLast', 'sublist(list1,-1,1)'],
  ['append1', 'append(numList,num1,num2)'],
  ['concatenate1', 'concatenate(list1,list2)'],
  ['insertBefore1', 'insert before(list2,2,string1)'],
  ['remove2nd', 'remove(list2,2)'],
  ['reverse1', 'reverse(concatenate1)'],
  ['appendListItem', 'append(list1,string1)'],
  ['indexOf1', 'index of(list2,string1)'],
  ['union1', 'union(insertBefore1,concatenate1)'],
  ['distinctVals', 'distinct values(insertBefore1)'],
  ['flatten1', 'flatten(append(list1, list2))'],
];

describe('FEEL TCK / 0012-list-functions', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({ list1: ['a', 'b', 'c'], list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.listContainsList), false), 'listContainsList').toBe(true);
  });
  it('002', () => {
    const ctx = run({ string1: 'OK', list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.listContains), false), 'listContains').toBe(true);
  });
  it('003', () => {
    const ctx = run({ list1: ['a', 'b', 'c'] });
    expect(aeq(n(ctx.count1), 3), 'count1').toBe(true);
  });
  it('004', () => {
    const ctx = run({ numList: [6, 14, -3] });
    expect(aeq(n(ctx.min1), -3), 'min1').toBe(true);
  });
  it('005', () => {
    const ctx = run({ numList: [6, 14, -3] });
    expect(aeq(n(ctx.sum1), 17), 'sum1').toBe(true);
  });
  it('006', () => {
    const ctx = run({ numList: [6, 14, -3] });
    expect(aeq(n(ctx.mean1), 5.66666666666667), 'mean1').toBe(true);
  });
  it('007', () => {
    const ctx = run({ num1: 11, num2: 2, num3: 10 });
    expect(aeq(n(ctx.mean2), 7.66666666666667), 'mean2').toBe(true);
  });
  it('008', () => {
    const ctx = run({ list1: ['a', 'b', 'c'] });
    expect(aeq(n(ctx.sublist12), ['a', 'b']), 'sublist12').toBe(true);
  });
  it('009', () => {
    const ctx = run({ list1: ['a', 'b', 'c'] });
    expect(aeq(n(ctx.sublistLast), ['c']), 'sublistLast').toBe(true);
  });
  it('010', () => {
    const ctx = run({ num1: 11, num2: 2, num3: 10, numList: [6, 14, -3] });
    expect(aeq(n(ctx.append1), [6, 14, -3, 11, 2]), 'append1').toBe(true);
  });
  it('011', () => {
    const ctx = run({ list1: ['a', 'b', 'c'], list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.concatenate1), ['a', 'b', 'c', 'x', 'y', 'z']), 'concatenate1').toBe(true);
  });
  it('012', () => {
    const ctx = run({ string1: 'OK', list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.insertBefore1), ['x', 'OK', 'y', 'z']), 'insertBefore1').toBe(true);
  });
  it('013', () => {
    const ctx = run({ list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.remove2nd), ['x', 'z']), 'remove2nd').toBe(true);
  });
  it('014', () => {
    const ctx = run({ list1: ['a', 'b', 'c'], list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.reverse1), ['z', 'y', 'x', 'c', 'b', 'a']), 'reverse1').toBe(true);
  });
  it('015', () => {
    const ctx = run({ list1: ['a', 'b', 'c'], string1: 'x' });
    expect(aeq(n(ctx.appendListItem), ['a', 'b', 'c', 'x']), 'appendListItem').toBe(true);
  });
  it('016', () => {
    const ctx = run({ string1: 'OK', list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.indexOf1), []), 'indexOf1').toBe(true);
  });
  it('017', () => {
    const ctx = run({ string1: 'OK', list1: ['a', 'b', 'c'], list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.union1), ['x', 'OK', 'y', 'z', 'a', 'b', 'c']), 'union1').toBe(true);
  });
  it('018', () => {
    const ctx = run({ string1: 'OK', list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.distinctVals), ['x', 'OK', 'y', 'z']), 'distinctVals').toBe(true);
  });
  it('019', () => {
    const ctx = run({ list1: ['a', 'b', 'c'], list2: ['x', 'y', 'z'] });
    expect(aeq(n(ctx.flatten1), ['a', 'b', 'c', 'x', 'y', 'z']), 'flatten1').toBe(true);
  });
});
