// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['sort1', 'sort(listA, function(x,y) x>y)'],
  ['sort2', 'sort(tableB, function(x,y) x.col2<y.col2)'],
  ['sort3', 'sort(stringList, function(x,y) x<y)'],
];

describe('FEEL TCK / 0013-sort', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({
      listA: [3, 1, 5, 4],
      stringList: ['a', '8', 'Aa', 'A', '10', '9'],
      tableB: [
        { col1: 16, col2: 4, col3: 25, col4: 1 },
        { col1: 16, col2: 43, col3: 2, col4: 10 },
        { col1: 1, col2: 0, col3: 1, col4: 1 },
      ],
    });
    expect(aeq(n(ctx.sort1), [5, 4, 3, 1]), 'sort1').toBe(true);
    expect(
      aeq(n(ctx.sort2), [
        { col1: 1, col2: 0, col3: 1, col4: 1 },
        { col1: 16, col2: 4, col3: 25, col4: 1 },
        { col1: 16, col2: 43, col3: 2, col4: 10 },
      ]),
      'sort2',
    ).toBe(true);
    expect(aeq(n(ctx.sort3), ['10', '8', '9', 'A', 'Aa', 'a']), 'sort3').toBe(true);
  });
});
