// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { parseDuration } from '../../../src/temporal/duration.js';
import { parseDate, parseDateTime, parseTime } from '../../../src/temporal/index.js';
import { aeq, type Ctx, n } from '../utils.js';

const d = parseDate,
  _t = parseTime,
  _dt = parseDateTime,
  _dur = parseDuration;

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['simpleIf', 'if bool then num+10 else num-10'],
  [
    'conditionWithFunctions',
    'if aDate > date("2017-01-01") then substring before(aString, " ") else substring after(aString, " ")',
  ],
];

describe('FEEL TCK / 0032-conditionals', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it("001: Tests simple 'if' condition for true", () => {
    const ctx = run({ bool: true, num: 100 });
    expect(aeq(n(ctx.simpleIf), 110), 'simpleIf').toBe(true);
  });
  it("002: Tests simple 'if' condition for false", () => {
    const ctx = run({ bool: false, num: 100 });
    expect(aeq(n(ctx.simpleIf), 90), 'simpleIf').toBe(true);
  });
  it("003: Tests simple 'if' condition for null", () => {
    const ctx = run({ bool: null, num: 100 });
    expect(aeq(n(ctx.simpleIf), 90), 'simpleIf').toBe(true);
  });
  it("004: Tests 'if' condition with function calls for true", () => {
    const ctx = run({ aDate: d('2017-01-02'), aString: 'Hello World' });
    expect(aeq(n(ctx.conditionWithFunctions), 'Hello'), 'conditionWithFunctions').toBe(true);
  });
  it("005: Tests 'if' condition with function calls for false", () => {
    const ctx = run({ aDate: d('2017-01-01'), aString: 'Hello World' });
    expect(aeq(n(ctx.conditionWithFunctions), 'World'), 'conditionWithFunctions').toBe(true);
  });
  it("006: Tests 'if' condition with function calls for null", () => {
    const ctx = run({ aDate: null, aString: 'Hello World' });
    expect(aeq(n(ctx.conditionWithFunctions), 'World'), 'conditionWithFunctions').toBe(true);
  });
});
