// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'abs(1)'],
  ['decision002', 'abs(-1)'],
  ['decision003', 'abs(0)'],
  ['decision004', 'abs()'],
  ['decision005', 'abs(1,1)'],
  ['decision006', 'abs(n:-1)'],
  ['decision007', 'abs(number:-1)'],
  ['decision008', 'abs(null)'],
  ['decision009', 'abs("-1")'],
  ['decision010', 'abs(true)'],
  ['decision011', 'abs(duration("-P1D"))'],
  ['decision011_a', 'abs(duration("P1D"))'],
  ['decision012', 'abs(duration("-P1Y"))'],
  ['decision012_a', 'abs(duration("P1Y"))'],
  ['decision013', 'abs(date("-2018-12-06"))'],
  ['decision014', 'abs(time("00:00:00"))'],
  ['decision015', 'abs(date and time("2018-12-06T00:00:00"))'],
];

describe('FEEL TCK / 0050-feel-abs-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Assert on positive number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), 1), 'decision001').toBe(true);
  });
  it('002: Assert on negative number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), 1), 'decision002').toBe(true);
  });
  it('003: Assert on zero', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), 0), 'decision003').toBe(true);
  });
  it('004: Assert with no params', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: Assert with too many params', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: Assert with named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), 1), 'decision006').toBe(true);
  });
  it('007: Assert with incorrect named param', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it('008: Assert with null param', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('009: Assert with string param', () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it('010: Assert with boolean param', () => {
    const ctx = run({});
    expect(n(ctx.decision010)).toBeNull();
  });
  it('011: Assert with negative days duration param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011), 'P1D'), 'decision011').toBe(true);
  });
  it('011_a: Assert with positive days duration param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011_a), 'P1D'), 'decision011_a').toBe(true);
  });
  it('012: Assert with negative months duration param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision012), 'P1Y'), 'decision012').toBe(true);
  });
  it('012_a: Assert with positive months duration param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision012_a), 'P1Y'), 'decision012_a').toBe(true);
  });
  it('013: Assert with date param', () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
  it('014: Assert with time param', () => {
    const ctx = run({});
    expect(n(ctx.decision014)).toBeNull();
  });
  it('015: Assert with datetime param', () => {
    const ctx = run({});
    expect(n(ctx.decision015)).toBeNull();
  });
});
