// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'exp(4)'],
  ['decision002', 'exp(-1)'],
  ['decision003', 'exp(0)'],
  ['decision004', 'exp()'],
  ['decision005', 'exp(4,4)'],
  ['decision006', 'exp(number:4)'],
  ['decision007', 'exp(n:4)'],
  ['decision008', 'exp(null)'],
  ['decision009', 'exp("4")'],
  ['decision010', 'exp(true)'],
  ['decision011', 'exp(duration("P4D"))'],
  ['decision012', 'exp(duration("P4Y"))'],
  ['decision013', 'exp(date("2018-12-06"))'],
  ['decision014', 'exp(time("00:00:00"))'],
  ['decision015', 'exp(date and time("2018-12-06T00:00:00"))'],
];

describe('FEEL TCK / 0052-feel-exp-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Assert on positive number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), 54.59815003), 'decision001').toBe(true);
  });
  it('002: Assert on negative number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), 0.36787944), 'decision002').toBe(true);
  });
  it('003: Assert on zero', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), 1), 'decision003').toBe(true);
  });
  it('004: Assert with no params', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: Assert with too many params', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: Assert with named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), 54.59815003), 'decision006').toBe(true);
  });
  it('007: Assert with incorrect named param', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it('008: Assert with null param', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('009: Assert with string param', () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it('010: Assert with boolean param', () => {
    const ctx = run({});
    expect(n(ctx.decision010)).toBeNull();
  });
  it('011: Assert with days duration param', () => {
    const ctx = run({});
    expect(n(ctx.decision011)).toBeNull();
  });
  it('012: Assert with months duration param', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('013: Assert with date param', () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
  it('014: Assert with time param', () => {
    const ctx = run({});
    expect(n(ctx.decision014)).toBeNull();
  });
  it('015: Assert with datetime param', () => {
    const ctx = run({});
    expect(n(ctx.decision015)).toBeNull();
  });
});
