// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', '{a: "foo", b: "bar"}'],
  ['decision002', '{a: "foo", b: {c: "bar", d: {e: "baz"}}}'],
  ['decision003', '{a: 1 + 2, b: a + 3}'],
  ['decision003_a', '{a: 1 + 2, b: 3, c: {d: a + b}}'],
  ['decision004', '{foo bar: "foo"}'],
  ['decision005', '{foo+bar: "foo"}'],
  ['decision006', '{"foo+bar((!!],foo": "foo"}'],
  ['decision007', '{"": "foo"}'],
  ['decision008', '{foo: "bar", foo: "baz"}'],
  ['decision009', '{ a: 1 }.b'],
  ['decision010', 'null.b'],
];

describe('FEEL TCK / 0057-feel-context', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: creation of simple context', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), { a: 'foo', b: 'bar' }), 'decision001').toBe(true);
  });
  it('002: nested context', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx.decision002), { a: 'foo', b: { c: 'bar', d: { e: 'baz' } } }),
      'decision002',
    ).toBe(true);
  });
  it('003: previous entries in scope for later entries', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), { a: 3, b: 6 }), 'decision003').toBe(true);
  });
  it('003_a: previous entries in scope for later (nested) entries', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_a), { a: 3, b: 3, c: { d: 6 } }), 'decision003_a').toBe(true);
  });
  it('004: spaces permitted in name', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), { 'foo bar': 'foo' }), 'decision004').toBe(true);
  });
  it('005: extra chars permtted in name', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005), { 'foo+bar': 'foo' }), 'decision005').toBe(true);
  });
  it('006: string literal permitted as name', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), { 'foo+bar((!!],foo': 'foo' }), 'decision006').toBe(true);
  });
  it('007: empty string literal permitted as name', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007), { '': 'foo' }), 'decision007').toBe(true);
  });
  it('008: duplicate context entry keys not allowed (DMN14-178), results in null', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('009: non-existing member access results in null', () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it('010: non-existing member access (on null)', () => {
    const ctx = run({});
    expect(n(ctx.decision010)).toBeNull();
  });
});
