// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'any([true, false, true])'],
  ['decision002', 'any([false, false, false])'],
  ['decision004', 'any([123, false])'],
  ['decision005', 'any([])'],
  ['decision006', 'any(true)'],
  ['decision007', 'any(false)'],
  ['decision008', 'any(null)'],
  ['decision009', 'any(123)'],
  ['decision010', 'any(true, false, true)'],
  ['decision011', 'any(false, false)'],
  ['decision012', 'any(null, false)'],
  ['decision014', 'any()'],
  ['decision015', 'any(list:[true, false, true])'],
  ['decision016', 'any(list:[false, false])'],
  ['decision017', 'any(list:[null, false])'],
  ['decision018', 'any(list:null)'],
  ['decision019', 'any(l:[true])'],
];

describe('FEEL TCK / 0060-feel-any-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: return true if any item is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), true), 'decision001').toBe(true);
  });
  it('002: return false if all items are false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), false), 'decision002').toBe(true);
  });
  it('004: return null if any item not true and not all false', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: return false for empty list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005), false), 'decision005').toBe(true);
  });
  it('006: return true for singleton true ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), true), 'decision006').toBe(true);
  });
  it('007: return false for singleton false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007), false), 'decision007').toBe(true);
  });
  it('008: return null for singleton null', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('009: return null for singleton non-boolean', () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it('010: return true if any vararg item is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision010), true), 'decision010').toBe(true);
  });
  it('011: return false if all vararg items are false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011), false), 'decision011').toBe(true);
  });
  it('012: return null if not all vararg items are true and none are false false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision012), null), 'decision012').toBe(true);
  });
  it('014: return error when no params', () => {
    const ctx = run({});
    expect(n(ctx.decision014)).toBeNull();
  });
  it('015: return true if any item is true with named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision015), true), 'decision015').toBe(true);
  });
  it('016: return false if all items are false with named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision016), false), 'decision016').toBe(true);
  });
  it('017: return null if none true and not all false - with named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision017), null), 'decision017').toBe(true);
  });
  it('018: return error when named param is null', () => {
    const ctx = run({});
    expect(n(ctx.decision018)).toBeNull();
  });
  it('019: will error when wrongly named param', () => {
    const ctx = run({});
    expect(n(ctx.decision019)).toBeNull();
  });
});
