// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'mode([6, 3, 9, 6, 6])'],
  ['decision002', 'mode([3, 6, 1, 9, 6, 1, 3])'],
  ['decision003', 'mode()'],
  ['decision003_a', 'mode(null)'],
  ['decision004', 'mode()'],
  ['decision005', 'mode([1,2,"foo",4])'],
  ['decision006', 'mode([2.5, 1, 2.5, 3])'],
  ['decision007', 'mode([])'],
  ['decision008', 'mode(6)'],
  ['decision009', 'mode(6, 3, 9, 6, 6)'],
  ['decision011', 'mode(list:[6, 3, 9, 6, 6])'],
  ['decision012', 'mode(list:null)'],
  ['decision013', 'mode(l:[2, 4, 7, 5])'],
];

describe('FEEL TCK / 0062-feel-mode-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: will return median for even list size', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), [6]), 'decision001').toBe(true);
  });
  it('002: will return median for odd list size', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), [1, 3, 6]), 'decision002').toBe(true);
  });
  it('003: will error when no params', () => {
    const ctx = run({});
    expect(n(ctx.decision003)).toBeNull();
  });
  it('003_a: will error when null param', () => {
    const ctx = run({});
    expect(n(ctx.decision003_a)).toBeNull();
  });
  it('004: will error when list item not a number', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: will error when list item not a number', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: will median to decimals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), [2.5]), 'decision006').toBe(true);
  });
  it('007: will return empty list when param is empty list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007), []), 'decision007').toBe(true);
  });
  it('008: will coerce singleton list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008), [6]), 'decision008').toBe(true);
  });
  it('009: will return median for varargs list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009), [6]), 'decision009').toBe(true);
  });
  it('011: will return median for named params', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011), [6]), 'decision011').toBe(true);
  });
  it('012: will error when null named param', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('013: will error when wrongly named param', () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
});
