// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'stddev([2, 4, 7, 5])'],
  ['decision003', 'stddev()'],
  ['decision003_a', 'stddev(null)'],
  ['decision004', 'stddev()'],
  ['decision005', 'stddev([1,2,"foo",4])'],
  ['decision007', 'stddev([])'],
  ['decision008', 'stddev(47)'],
  ['decision008_a', 'stddev([47])'],
  ['decision009', 'stddev(2, 4, 7, 5)'],
  ['decision011', 'stddev(list:[2, 4, 7, 5])'],
  ['decision012', 'stddev(list:null)'],
  ['decision013', 'stddev(l:[2, 4, 7, 5])'],
];

describe('FEEL TCK / 0063-feel-stddev-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: will return stddev', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), 2.0816659994661), 'decision001').toBe(true);
  });
  it('003: will error when no params', () => {
    const ctx = run({});
    expect(n(ctx.decision003)).toBeNull();
  });
  it('003_a: will error when null param', () => {
    const ctx = run({});
    expect(n(ctx.decision003_a)).toBeNull();
  });
  it('004: will error when list item not a number', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: will error when list item not a number', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('007: will return null for empty list', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it("008: will error when a single item.  Note, the example given in the spec can only be calculated using\n            'sample' stddev algorithm, not the 'population' algorithm.  For the 'sample' algorithm, the stdev result\n            of a single item is undefined as part of the calculation is a division by the (sample size - 1).\n            Which, with a sample size of 1, results in a divide by zero error.\n        ", () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('008_a: will error when a list with a single item.', () => {
    const ctx = run({});
    expect(n(ctx.decision008_a)).toBeNull();
  });
  it('009: will return stddev for varargs list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009), 2.0816659994661), 'decision009').toBe(true);
  });
  it('011: will return stddev - named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011), 2.0816659994661), 'decision011').toBe(true);
  });
  it('012: will error when null named param', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('013: will error when wrongly named param', () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
});
