// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'true and true'],
  ['decision002', 'true and false'],
  ['decision003_a', 'true and null'],
  ['decision003_b', 'true and 123'],
  ['decision003_c', 'true and "true"'],
  ['decision004', 'false and true'],
  ['decision005', 'false and false'],
  ['decision006_a', 'false and null'],
  ['decision006_b', 'false and 123'],
  ['decision006_c', 'false and "true"'],
  ['decision007_a', 'null and true'],
  ['decision007_b', '123 and true'],
  ['decision007_c', '"true" and true'],
  ['decision008_a', 'null and false'],
  ['decision008_b', '123 and false'],
  ['decision008_c', '"true" and false'],
  ['decision009_a', 'null and null'],
  ['decision009_b', '"true" and "true"'],
  ['decision009_c', '0 and 0'],
];

describe('FEEL TCK / 0064-feel-conjunction', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), true), 'decision001').toBe(true);
  });
  it('002', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), false), 'decision002').toBe(true);
  });
  it('003_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_a), null), 'decision003_a').toBe(true);
  });
  it('003_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_b), null), 'decision003_b').toBe(true);
  });
  it('003_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_c), null), 'decision003_c').toBe(true);
  });
  it('004', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), false), 'decision004').toBe(true);
  });
  it('005', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005), false), 'decision005').toBe(true);
  });
  it('006_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006_a), false), 'decision006_a').toBe(true);
  });
  it('006_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006_b), false), 'decision006_b').toBe(true);
  });
  it('006_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006_c), false), 'decision006_c').toBe(true);
  });
  it('007_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_a), null), 'decision007_a').toBe(true);
  });
  it('007_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_b), null), 'decision007_b').toBe(true);
  });
  it('007_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_c), null), 'decision007_c').toBe(true);
  });
  it('008_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008_a), false), 'decision008_a').toBe(true);
  });
  it('008_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008_b), false), 'decision008_b').toBe(true);
  });
  it('008_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008_c), false), 'decision008_c').toBe(true);
  });
  it('009_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009_a), null), 'decision009_a').toBe(true);
  });
  it('009_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009_b), null), 'decision009_b').toBe(true);
  });
  it('009_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009_c), null), 'decision009_c').toBe(true);
  });
});
