// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'true or true'],
  ['decision002', 'true or false'],
  ['decision003_a', 'true or null'],
  ['decision003_b', 'true or 123'],
  ['decision003_c', 'true or "true"'],
  ['decision004', 'false or true'],
  ['decision005', 'false or false'],
  ['decision006_a', 'false or null'],
  ['decision006_b', 'false or 123'],
  ['decision006_c', 'false or "true"'],
  ['decision007_a', 'null or true'],
  ['decision007_b', '123 or true'],
  ['decision007_c', '"true" or true'],
  ['decision008_a', 'null or false'],
  ['decision008_b', '123 or false'],
  ['decision008_c', '"true" or false'],
  ['decision009_a', 'null or null'],
  ['decision009_b', '"true" or "true"'],
  ['decision009_c', '0 or 0'],
];

describe('FEEL TCK / 0065-feel-disjunction', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), true), 'decision001').toBe(true);
  });
  it('002', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), true), 'decision002').toBe(true);
  });
  it('003_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_a), true), 'decision003_a').toBe(true);
  });
  it('003_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_b), true), 'decision003_b').toBe(true);
  });
  it('003_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_c), true), 'decision003_c').toBe(true);
  });
  it('004', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), true), 'decision004').toBe(true);
  });
  it('005', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005), false), 'decision005').toBe(true);
  });
  it('006_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006_a), null), 'decision006_a').toBe(true);
  });
  it('006_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006_b), null), 'decision006_b').toBe(true);
  });
  it('006_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006_c), null), 'decision006_c').toBe(true);
  });
  it('007_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_a), true), 'decision007_a').toBe(true);
  });
  it('007_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_b), true), 'decision007_b').toBe(true);
  });
  it('007_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_c), true), 'decision007_c').toBe(true);
  });
  it('008_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008_a), null), 'decision008_a').toBe(true);
  });
  it('008_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008_b), null), 'decision008_b').toBe(true);
  });
  it('008_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008_c), null), 'decision008_c').toBe(true);
  });
  it('009_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009_a), null), 'decision009_a').toBe(true);
  });
  it('009_b', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009_b), null), 'decision009_b').toBe(true);
  });
  it('009_c', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009_c), null), 'decision009_c').toBe(true);
  });
});
