// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'not(true)'],
  ['decision002', 'not(false)'],
  ['decision003_a', 'not(null)'],
  ['decision003_b', 'not(0)'],
  ['decision003_c', 'not(1)'],
  ['decision003_d', 'not("true")'],
];

describe('FEEL TCK / 0066-feel-negation', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), false), 'decision001').toBe(true);
  });
  it('002', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), true), 'decision002').toBe(true);
  });
  it('003_a', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_a), null), 'decision003_a').toBe(true);
  });
  it('003_b', () => {
    const ctx = run({});
    expect(n(ctx.decision003_b)).toBeNull();
  });
  it('003_c', () => {
    const ctx = run({});
    expect(n(ctx.decision003_c)).toBeNull();
  });
  it('003_d', () => {
    const ctx = run({});
    expect(n(ctx.decision003_d)).toBeNull();
  });
});
