// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'split("John Doe", "\\s")'],
  ['decision001_a', 'split("a;b;c;;", ";")'],
  ['decision004', 'split()'],
  ['decision005', 'split("foo")'],
  ['decision006', 'split(delimiter: ",", string:"foo,bar")'],
  ['decision007', 'split(delimiter: ",", str:"foo,bar")'],
  ['decision008', 'split(null, null)'],
  ['decision008_a', 'split("foo", null)'],
  ['decision008_b', 'split(null, ",")'],
];

describe('FEEL TCK / 0067-feel-split-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: will split', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), ['John', 'Doe']), 'decision001').toBe(true);
  });
  it('001_a: Will split', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_a), ['a', 'b', 'c', '', '']), 'decision001_a').toBe(true);
  });
  it('004: Assert with no params', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: Assert with too few params', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: Assert with named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), ['foo', 'bar']), 'decision006').toBe(true);
  });
  it('007: Assert with incorrect named param', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it('008: Assert with null params', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('008_a: Assert with null params', () => {
    const ctx = run({});
    expect(n(ctx.decision008_a)).toBeNull();
  });
  it('008_b: Assert with null params', () => {
    const ctx = run({});
    expect(n(ctx.decision008_b)).toBeNull();
  });
});
