// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['null_001', 'null = null'],
  ['null_002', 'null != null'],
  ['boolean_001', 'true = true'],
  ['boolean_002', 'true != true'],
  ['boolean_003', 'false = false'],
  ['boolean_004', 'false != false'],
  ['boolean_005', 'true = false'],
  ['boolean_006', 'true = null'],
  ['boolean_007', 'false = null'],
  ['boolean_008', 'false = 0'],
  ['boolean_009', 'true = 1'],
  ['number_001', '123 = 123'],
  ['number_002', '123.01 = 123.01'],
  ['number_003', '0 = 0.00'],
  ['number_004', '-0 = 0'],
  ['number_005', '-1 = 1'],
  ['number_006', '100 = null'],
  ['number_007', '100 = "100"'],
  ['number_008', '12300 = 1.23e4'],
  ['number_009', '12300 = 1.23e+4'],
  ['number_010', '0.000123 = 1.23e-4'],
  ['string_001', '"foo" = "foo"'],
  ['string_002', '"foo" = "Foo"'],
  ['string_003', '"foo" != "Foo"'],
  ['string_004', '"foo" = null'],
  ['string_005', '"foo" = 100'],
  ['list_001', '[1,2,3] = [1,2,3]'],
  ['list_002', '[1,1,1] = [1,1,1,1]'],
  ['list_003', '[1,1,1] = [1,1,2]'],
  ['list_004', '[] = []'],
  ['list_005', '[1,2,3] = [3,2,1]'],
  ['list_006', 'true[1] = true'],
  ['list_007', '100[1] = 100'],
  ['list_008', '"foo"[1] = "foo"'],
  ['list_009', 'date("2018-12-08")[1] = date("2018-12-08")'],
  ['list_010', 'time("10:30:12")[1] = time("10:30:12")'],
  ['list_011', 'date and time("2018-12-08")[1] = date and time("2018-12-08")'],
  ['list_012', 'duration("P1D")[1] = duration("P1D")'],
  ['list_013', 'duration("P1Y")[1] = duration("P1Y")'],
  ['list_014', '{a: "foo"}[1] = {a: "foo"}'],
  ['list_015', '[] = null'],
  ['list_016', '[] = 0'],
  ['context_001', '{} = {}'],
  ['context_002', '{foo: "bar", bar: "baz"} = {foo: "bar", bar: "baz"}'],
  ['context_003', '{foo: "bar", bar: "baz"} = {bar: "baz", foo: "bar"}'],
  ['context_004', '{foo: "bar"} = {"foo": "bar"}'],
  ['context_005', '{foo: "bar"} = {foo: "baz"}'],
  ['context_006', '{} = null'],
  ['context_007', '{} = []'],
  ['date_001', 'date("2018-12-08") = date("2018-12-08")'],
  ['date_002', 'date("2018-12-07") = date("2018-12-08")'],
  ['date_003', 'date("2018-12-07") = null'],
  ['date_004', 'date("2018-12-07") = 100'],
  ['time_001', 'time("10:30:00") = time("10:30:00")'],
  ['time_002', 'time("11:30:00") = time("10:30:00")'],
  ['time_002_a', 'time("10:31:00") = time("10:30:00")'],
  ['time_002_b', 'time("10:30:01") = time("10:30:00")'],
  ['time_003', 'time("10:30:00.0000") = time("10:30:00")'],
  ['time_004', 'time("10:30:00.0001") = time("10:30:00.0001")'],
  ['time_005', 'time("10:30:00.0001") = time("10:30:00.0002")'],
  ['time_006', 'time("10:30:00@Europe/Paris") = time("10:30:00@Europe/Paris")'],
  ['time_010', 'time("10:30:00Z") = time("10:30:00+00:00")'],
  ['time_011', 'time("10:30:00") = null'],
  ['time_012', 'time("10:30:00") = 100'],
  ['datetime_001', 'date and time("2018-12-08T10:30:00") = date and time("2018-12-08T10:30:00")'],
  ['datetime_002', 'date and time("2018-12-08") = date and time("2018-12-08T00:00:00")'],
  [
    'datetime_003',
    'date and time("2018-12-08T00:00:00.0001") = date and time("2018-12-08T00:00:00.0001")',
  ],
  [
    'datetime_003_a',
    'date and time("2018-12-08T00:00:00.0001") = date and time("2018-12-08T00:00:00.0000")',
  ],
  ['datetime_004', 'date and time("2018-12-08T00:00:00") = date and time("2018-12-07T00:00:00")'],
  [
    'datetime_005',
    'date and time("2018-12-08T00:00:00@Europe/Paris") = date and\n                time("2018-12-08T00:00:00@Europe/Paris")',
  ],
  [
    'datetime_006',
    'date and time("2018-12-08T00:00:00@Europe/Paris") = date and time("2018-12-08T00:00:00@Asia/Dhaka")',
  ],
  [
    'datetime_008',
    'date and time("2018-10-08T00:00:00+02:00") = date and time("2018-10-08T00:00:00@Europe/Paris")',
  ],
  [
    'datetime_008_a',
    'date and time("2018-02-08T00:00:00+01:00") = date and time("2018-02-08T00:00:00@Europe/Paris")',
  ],
  [
    'datetime_008_b',
    '@"2002-04-02T12:00:00@Australia/Melbourne" = @"2002-04-02T12:00:00@Australia/Sydney"',
  ],
  [
    'datetime_009',
    'date and time("2018-12-08T00:00:00+00:00") = date and time("2018-12-08T00:00:00@Etc/UTC")',
  ],
  ['datetime_010', 'date and time("2018-12-08T00:00:00") = null'],
  ['datetime_011', 'date and time("2018-12-08T00:00:00") = 100'],
  ['datetime_012', '@"2002-04-02T12:00:00-01:00" = @"2002-04-02T17:00:00+04:00"'],
  ['datetime_013', '@"2002-04-02T23:00:00-04:00" = @"2002-04-03T02:00:00-01:00"'],
  ['dt_duration_001', 'duration("P1D") = duration("P1D")'],
  ['dt_duration_002', 'duration("P1D") = duration("PT24H")'],
  ['dt_duration_003', 'duration("P1D") = duration("P2D")'],
  ['dt_duration_004', 'duration("P1D") = duration("-P1D")'],
  ['dt_duration_005', 'duration("P0D") = duration("-P0D")'],
  ['dt_duration_006', 'duration("P0D") = null'],
  ['dt_duration_007', 'duration("P0D") = 0'],
  ['ym_duration_001', 'duration("P1Y") = duration("P1Y")'],
  ['ym_duration_002', 'duration("P1Y") = duration("P12M")'],
  ['ym_duration_003', 'duration("P1Y") = duration("P2Y")'],
  ['ym_duration_004', 'duration("P1Y") = duration("-P1Y")'],
  ['ym_duration_005', 'duration("P0Y") = duration("-P0Y")'],
  ['ym_duration_006', 'duration("P1Y") = duration("P365D")'],
  ['ym_duration_007', 'duration("P0Y") = null'],
  ['ym_duration_008', 'duration("P0Y") = 0'],
  ['deep_001', '[1,2,[3, 4]] = [1,2,[3, 4]]'],
  ['deep_002', '[1,2,{a: [3,4]}] = [1,2,{a: [3,4]}]'],
  ['deep_003', '[1,2,[3, 4]] = [1,2,[4, 3]]'],
  ['deep_004', '[1,2,{a: [3,4]}] = [1,2,{a: [3,4], b: "foo"}]'],
  ['deep_005', '{a: {b: "foo", c: [1,2]}} = {a: {b: "foo", c: [1,2]}}'],
  ['deep_006', '{a: {c: "bar", b: "foo"}} = {a: {b: "foo", c: "bar"}}'],
  ['deep_007', '{a: {b: "foo", c: [1,2]}} = {a: {b: "foo", c: [2,1]}}'],
  ['range_001', '[1..10] = [1..10]'],
  ['range_002', '[1..2] = [1..3]'],
  ['range_003', '[2..10] = [1..10]'],
  ['range_004', '(1..10] = ]1..10]'],
  ['range_005', '[1..10) = [1..10['],
  ['range_006', '(< 10) = (null..10)'],
  ['range_006_a', '(< 10) = (< 10)'],
  ['range_007', '(<= 10) = (null..10]'],
  ['range_008', '(> 10) = (10..null)'],
  ['range_009', '(>= 10) = [10..null)'],
  ['range_010', '(=10) = [10..10]'],
  ['range_011', '(=10) = (=10)'],
  ['range_012', '(!=10) = (!=10)'],
];

describe('FEEL TCK / 0068-feel-equality', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('null_001: null equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_001), true), 'null_001').toBe(true);
  });
  it('null_002: null not equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_002), false), 'null_002').toBe(true);
  });
  it('boolean_001: boolean true equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_001), true), 'boolean_001').toBe(true);
  });
  it('boolean_002: boolean true not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_002), false), 'boolean_002').toBe(true);
  });
  it('boolean_003: boolean true equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_003), true), 'boolean_003').toBe(true);
  });
  it('boolean_004: boolean true not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_004), false), 'boolean_004').toBe(true);
  });
  it('boolean_005: boolean true not equal false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_005), false), 'boolean_005').toBe(true);
  });
  it('boolean_006: boolean true equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_006), false), 'boolean_006').toBe(true);
  });
  it('boolean_007: boolean false equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_007), false), 'boolean_007').toBe(true);
  });
  it('boolean_008: boolean false equals another type (0)', () => {
    const ctx = run({});
    expect(n(ctx.boolean_008)).toBeNull();
  });
  it('boolean_009: boolean true equals another type (1)', () => {
    const ctx = run({});
    expect(n(ctx.boolean_009)).toBeNull();
  });
  it('number_001: num equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_001), true), 'number_001').toBe(true);
  });
  it('number_002: num with digits equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_002), true), 'number_002').toBe(true);
  });
  it('number_003: zero equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_003), true), 'number_003').toBe(true);
  });
  it('number_004: negative zero equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_004), true), 'number_004').toBe(true);
  });
  it('number_005: negative inequality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_005), false), 'number_005').toBe(true);
  });
  it('number_006: number equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_006), false), 'number_006').toBe(true);
  });
  it('number_007: number equals another type', () => {
    const ctx = run({});
    expect(n(ctx.number_007)).toBeNull();
  });
  it("number_008: number equals literal 'e' exponent number with default sign", () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_008), true), 'number_008').toBe(true);
  });
  it("number_009: number equals literal 'e' exponent number with '+' sign", () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_009), true), 'number_009').toBe(true);
  });
  it("number_010: number equals literal 'e' exponent number with '-' sign", () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_010), true), 'number_010').toBe(true);
  });
  it('string_001: string equals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_001), true), 'string_001').toBe(true);
  });
  it('string_002: string case sensitive', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_002), false), 'string_002').toBe(true);
  });
  it('string_003: string not equals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_003), true), 'string_003').toBe(true);
  });
  it('string_004: string equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_004), false), 'string_004').toBe(true);
  });
  it('string_005: string equals another type', () => {
    const ctx = run({});
    expect(n(ctx.string_005)).toBeNull();
  });
  it('list_001: list equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_001), true), 'list_001').toBe(true);
  });
  it('list_002: lists of different lengths not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_002), false), 'list_002').toBe(true);
  });
  it('list_003: lists of same length with diff contents not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_003), false), 'list_003').toBe(true);
  });
  it('list_004: empty lists equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_004), true), 'list_004').toBe(true);
  });
  it('list_005: list with same content but different order not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_005), false), 'list_005').toBe(true);
  });
  it('list_006: non list boolean of index 1 equals boolean', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_006), true), 'list_006').toBe(true);
  });
  it('list_007: non list number of index 1 equals number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_007), true), 'list_007').toBe(true);
  });
  it('list_008: non list string of index 1 equals string', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_008), true), 'list_008').toBe(true);
  });
  it('list_009: non list date of index 1 equals date', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_009), true), 'list_009').toBe(true);
  });
  it('list_010: non list time of index 1 equals time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_010), true), 'list_010').toBe(true);
  });
  it('list_011: non list date time of index 1 equals date time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_011), true), 'list_011').toBe(true);
  });
  it('list_012: non list days duration of index 1 equals days duration', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_012), true), 'list_012').toBe(true);
  });
  it('list_013: non list years duration of index 1 equals years duration', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_013), true), 'list_013').toBe(true);
  });
  it('list_014: non list context of index 1 equals context', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_014), true), 'list_014').toBe(true);
  });
  it('list_015: list equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_015), false), 'list_015').toBe(true);
  });
  it('list_016: list equals another type', () => {
    const ctx = run({});
    expect(n(ctx.list_016)).toBeNull();
  });
  it('context_001: empty contexts equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_001), true), 'context_001').toBe(true);
  });
  it('context_002: contexts with same properties in same order equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_002), true), 'context_002').toBe(true);
  });
  it('context_003: contexts with same properties in different order equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_003), true), 'context_003').toBe(true);
  });
  it('context_004: string literal name equal to non-string-literal name', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_004), true), 'context_004').toBe(true);
  });
  it('context_005: context with same name and different values not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_005), false), 'context_005').toBe(true);
  });
  it('context_006: context equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_006), false), 'context_006').toBe(true);
  });
  it('context_007: context equals another type', () => {
    const ctx = run({});
    expect(n(ctx.context_007)).toBeNull();
  });
  it('date_001: same dates are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_001), true), 'date_001').toBe(true);
  });
  it('date_002: different dates are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_002), false), 'date_002').toBe(true);
  });
  it('date_003: date equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_003), false), 'date_003').toBe(true);
  });
  it('date_004: date equals another type', () => {
    const ctx = run({});
    expect(n(ctx.date_004)).toBeNull();
  });
  it('time_001: same times are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_001), true), 'time_001').toBe(true);
  });
  it('time_002: different times are not equal: hours', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_002), false), 'time_002').toBe(true);
  });
  it('time_002_a: different times are not equal: minutes', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_002_a), false), 'time_002_a').toBe(true);
  });
  it('time_002_b: different times are not equal: seconds', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_002_b), false), 'time_002_b').toBe(true);
  });
  it('time_003: same times with zero milliseconds are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_003), true), 'time_003').toBe(true);
  });
  it('time_004: same times with same milliseconds are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_004), true), 'time_004').toBe(true);
  });
  it('time_005: same times with different milliseconds are equal as value resolution is seconds', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_005), true), 'time_005').toBe(true);
  });
  it('time_006: same times in same zone are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_006), true), 'time_006').toBe(true);
  });
  it('time_010: same times = one with Z zone, the other with UTC are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_010), true), 'time_010').toBe(true);
  });
  it('time_011: time equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_011), false), 'time_011').toBe(true);
  });
  it('time_012: time equals another type', () => {
    const ctx = run({});
    expect(n(ctx.time_012)).toBeNull();
  });
  it('datetime_001: same datetimes are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_001), true), 'datetime_001').toBe(true);
  });
  it('datetime_002: datetimes with no time is equal to datetime with zero time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_002), true), 'datetime_002').toBe(true);
  });
  it('datetime_003: datetimes with same milliseconds are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_003), true), 'datetime_003').toBe(true);
  });
  it('datetime_003_a: datetimes with different milliseconds are equal as resolution is to the second', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_003_a), true), 'datetime_003_a').toBe(true);
  });
  it('datetime_004: different datetimes are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_004), false), 'datetime_004').toBe(true);
  });
  it('datetime_005: same datetimes in same zone are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_005), true), 'datetime_005').toBe(true);
  });
  it('datetime_006: same datetimes in different zones are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_006), false), 'datetime_006').toBe(true);
  });
  it('datetime_008: same datetimes, one with offset and the other with zone are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_008), true), 'datetime_008').toBe(true);
  });
  it('datetime_008_a: same datetimes, one with offset and the other with zone are equal - DST', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_008_a), true), 'datetime_008_a').toBe(true);
  });
  it('datetime_008_b: same datetimes, with same offsets but different zones equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_008_b), true), 'datetime_008_b').toBe(true);
  });
  it('datetime_009: datetime with zero offset is equal to utc zone', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_009), true), 'datetime_009').toBe(true);
  });
  it('datetime_010: datetime equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_010), false), 'datetime_010').toBe(true);
  });
  it('datetime_011: datetime equals another type', () => {
    const ctx = run({});
    expect(n(ctx.datetime_011)).toBeNull();
  });
  it('datetime_012: datetime: different times in different zones can be equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_012), true), 'datetime_012').toBe(true);
  });
  it('datetime_013: datetime: different times in different zones can be equal (with negative offset)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_013), true), 'datetime_013').toBe(true);
  });
  it('dt_duration_001: same durations are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_001), true), 'dt_duration_001').toBe(true);
  });
  it('dt_duration_002: equivalent durations are (erm) equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_002), true), 'dt_duration_002').toBe(true);
  });
  it('dt_duration_003: different durations are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_003), false), 'dt_duration_003').toBe(true);
  });
  it('dt_duration_004: negative non-zero durations of same amount are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_004), false), 'dt_duration_004').toBe(true);
  });
  it('dt_duration_005: negative zero duration and zero duration are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_005), true), 'dt_duration_005').toBe(true);
  });
  it('dt_duration_006: dt duration equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_006), false), 'dt_duration_006').toBe(true);
  });
  it('dt_duration_007: dt duration equals another type', () => {
    const ctx = run({});
    expect(n(ctx.dt_duration_007)).toBeNull();
  });
  it('ym_duration_001: same durations are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_001), true), 'ym_duration_001').toBe(true);
  });
  it('ym_duration_002: equivalent durations are (erm) equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_002), true), 'ym_duration_002').toBe(true);
  });
  it('ym_duration_003: different durations are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_003), false), 'ym_duration_003').toBe(true);
  });
  it('ym_duration_004: negative non-zero durations of same amount are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_004), false), 'ym_duration_004').toBe(true);
  });
  it('ym_duration_005: negative zero duration and zero duration are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_005), true), 'ym_duration_005').toBe(true);
  });
  it('ym_duration_006: years/months duration not equal to days/hours duration of same amount', () => {
    const ctx = run({});
    expect(n(ctx.ym_duration_006)).toBeNull();
  });
  it('ym_duration_007: years/months duration equals null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_007), false), 'ym_duration_007').toBe(true);
  });
  it('ym_duration_008: years/months duration equals another type', () => {
    const ctx = run({});
    expect(n(ctx.ym_duration_008)).toBeNull();
  });
  it('deep_001: deep array equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.deep_001), true), 'deep_001').toBe(true);
  });
  it('deep_002: deep array equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.deep_002), true), 'deep_002').toBe(true);
  });
  it('deep_003: deep array in-equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.deep_003), false), 'deep_003').toBe(true);
  });
  it('deep_004: deep array in-equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.deep_004), false), 'deep_004').toBe(true);
  });
  it('deep_005: deep context equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.deep_005), true), 'deep_005').toBe(true);
  });
  it('deep_006: deep context equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.deep_006), true), 'deep_006').toBe(true);
  });
  it('deep_007: deep context in-equality', () => {
    const ctx = run({});
    expect(aeq(n(ctx.deep_007), false), 'deep_007').toBe(true);
  });
  it('range_001: ranges with same endpoint and inclusivity are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_001), true), 'range_001').toBe(true);
  });
  it('range_002: ranges with different upper endpoints are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_002), false), 'range_002').toBe(true);
  });
  it('range_003: ranges with different lower endpoints are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_003), false), 'range_003').toBe(true);
  });
  it('range_004: ranges with same endpoints, but same though syntactically different lower inclusivity are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_004), true), 'range_004').toBe(true);
  });
  it('range_005: ranges with same endpoints, but same though syntactically different upper inclusivity are equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_005), true), 'range_005').toBe(true);
  });
  it('range_006: equal ranges though syntactically different are not equal: LT ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_006), false), 'range_006').toBe(true);
  });
  it('range_006_a: unary syntax comparison range LT', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_006_a), true), 'range_006_a').toBe(true);
  });
  it('range_007: equal ranges though syntactically different are not equal: LE ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_007), false), 'range_007').toBe(true);
  });
  it('range_008: equal ranges though syntactically different are not equal: GT ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_008), false), 'range_008').toBe(true);
  });
  it('range_009: equal ranges though syntactically different are not equal: GE ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_009), false), 'range_009').toBe(true);
  });
  it('range_010: equal ranges though syntactically different are not equal: EQ ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_010), false), 'range_010').toBe(true);
  });
  it('range_011: unary syntax comparison range EQ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_011), true), 'range_011').toBe(true);
  });
  it('range_012: unary syntax comparison range NE', () => {
    const ctx = run({});
    expect(aeq(n(ctx.range_012), true), 'range_012').toBe(true);
  });
});
