// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', '[1,2,3]'],
  ['decision001_a', '[]'],
  ['decision002', '[1,2,3][0]'],
  ['decision003', '[1,2,3][4]'],
  ['decision004', '[1,2,3][1]'],
  ['decision005', '[1,2,3][3]'],
  ['decision006', '[1,2,3][-1]'],
  ['decision007', '[1,2,3][-3]'],
  ['decision008', '[1,2,3][-4]'],
  ['decision009', '[1,2,3][true]'],
  ['decision010', '[1,2,3][false]'],
  ['decision011', '[1,2,3][item >= 2]'],
  ['decision012', 'true[true]'],
  ['decision013', 'true[false]'],
  ['decision014', '100[true]'],
  ['decision015', '100[false]'],
  ['decision016', '"foo"[true]'],
  ['decision017', '"foo"[false]'],
  ['decision018', 'true[1]'],
  ['decision019', '100[1]'],
  ['decision020', '"foo"[1]'],
  ['decision021', 'true[0]'],
  ['decision022', '100[0]'],
  ['decision023', '"foo"[0]'],
  ['decision024', '[{a: 1}, {a: 2}, {a: 3}][item.a >= 2]'],
  ['decision025', '[{a: 1}, {a: 2}, {a: 3}][a >= 2]'],
  ['decision026', '[{item: 1}, {item: 2}, {item: 3}][item >= 2]'],
  ['decision027', '[ 1, 2, 3, 4 ][ item > 2 ]'],
  ['decision028', '[ { x: 1, y: 2 }, { x: 2, y: 3 } ][ x = 1 ]'],
  ['decision029', '[ { x: 1, y: 2 }, { x: null, y: 3 } ][ x < 2 ]'],
  ['decision030', '[ { x: 1, y: 2 }, { x: 2, y: 3 } ].y'],
  ['decision031', '[ { x: 1 } ][ y > 1 ]'],
  ['decision032', '[ { x: 1 }, { y: 2 } ][ y > 1 ]'],
  ['decision033', '[ { x: 1 } ].y'],
  ['decision034', '[ { x: 1 }, { y: 2 } ].y'],
];

describe('FEEL TCK / 0069-feel-list', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: creation of list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), [1, 2, 3]), 'decision001').toBe(true);
  });
  it('001_a: creation of empty list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_a), []), 'decision001_a').toBe(true);
  });
  it('002: access of index 0', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), null), 'decision002').toBe(true);
  });
  it('003: access of index > size', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), null), 'decision003').toBe(true);
  });
  it('004: access of first element', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), 1), 'decision004').toBe(true);
  });
  it('005: access of last element', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005), 3), 'decision005').toBe(true);
  });
  it('006: access of negative element', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), 3), 'decision006').toBe(true);
  });
  it('007: access of negative element', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007), 1), 'decision007').toBe(true);
  });
  it('008: access of negative element > -size', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008), null), 'decision008').toBe(true);
  });
  it('009: true boolean index element gives entire list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009), [1, 2, 3]), 'decision009').toBe(true);
  });
  it('010: false boolean index element gives empty list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision010), []), 'decision010').toBe(true);
  });
  it('011: filter expression using item', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011), [2, 3]), 'decision011').toBe(true);
  });
  it('012: true filter expression on non list - boolean', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision012), [true]), 'decision012').toBe(true);
  });
  it('013: false filter expression on non list - boolean', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision013), []), 'decision013').toBe(true);
  });
  it('014: true filter expression on non list - number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision014), [100]), 'decision014').toBe(true);
  });
  it('015: false filter expression on non list - number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision015), []), 'decision015').toBe(true);
  });
  it('016: true filter expression on non list - string', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision016), ['foo']), 'decision016').toBe(true);
  });
  it('017: false filter expression on non list - string', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision017), []), 'decision017').toBe(true);
  });
  it('018: index of 1 on non list - boolean', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision018), true), 'decision018').toBe(true);
  });
  it('019: index of 1 on non list - number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision019), 100), 'decision019').toBe(true);
  });
  it('020: index of 1 on non list - string', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision020), 'foo'), 'decision020').toBe(true);
  });
  it('021: index of 0 on non list - boolean', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision021), null), 'decision021').toBe(true);
  });
  it('022: index of 0 on non list - number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision022), null), 'decision022').toBe(true);
  });
  it('023: index of 0 on non list - string', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision023), null), 'decision023').toBe(true);
  });
  it('024: filter on context using item', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision024), [{ a: 2 }, { a: 3 }]), 'decision024').toBe(true);
  });
  it('025: filter on context using property name', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision025), [{ a: 2 }, { a: 3 }]), 'decision025').toBe(true);
  });
  it("026: filter on context using property 'item' name", () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision026), [{ item: 2 }, { item: 3 }]), 'decision026').toBe(true);
  });
  it('027: filter on scalars (10.3.2.5 - example 1)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision027), [3, 4]), 'decision027').toBe(true);
  });
  it('028: filter on property name (10.3.2.5 - example 2)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision028), [{ x: 1, y: 2 }]), 'decision028').toBe(true);
  });
  it('029: filter on property name + null value (10.3.2.5 - example 3)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision029), [{ x: 1, y: 2 }]), 'decision029').toBe(true);
  });
  it('030: path expression (10.3.2.5 - example 4)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision030), [2, 3]), 'decision030').toBe(true);
  });
  it('031: filter / non-member matching (empty)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision031), []), 'decision031').toBe(true);
  });
  it('032: filter / non-member matching (single result)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision032), [{ y: 2 }]), 'decision032').toBe(true);
  });
  it('033: path expression / no match', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision033), [null]), 'decision033').toBe(true);
  });
  it('034: path expression / partial match', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision034), [null, 2]), 'decision034').toBe(true);
  });
});
