// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['null_001', 'null instance of Any'],
  ['null_002', 'null instance of number'],
  ['null_003', 'null instance of string'],
  ['null_004', 'null instance of boolean'],
  ['null_005', 'null instance of date'],
  ['null_006', 'null instance of time'],
  ['null_007', 'null instance of date and time'],
  ['null_008', 'null instance of list<Any>'],
  ['null_009', 'null instance of years and months duration'],
  ['null_010', 'null instance of days and time duration'],
  ['null_012', 'null instance of function<> -> Any'],
  ['number_001', '123.01 instance of Any'],
  ['number_002', '123.01 instance of number'],
  ['number_003', '123.01 instance of boolean'],
  ['number_004', '123.01 instance of boolean'],
  ['number_005', '123.01 instance of date'],
  ['number_006', '123.01 instance of time'],
  ['number_007', '123.01 instance of date and time'],
  ['number_008', '123.01 instance of list<Any>'],
  ['number_009', '123.01 instance of years and months duration'],
  ['number_010', '123.01 instance of days and time duration'],
  ['number_012', '123.01 instance of function<>->Any'],
  ['string_001', '"foo" instance of Any'],
  ['string_002', '"foo" instance of number'],
  ['string_003', '"foo" instance of string'],
  ['string_004', '"foo" instance of boolean'],
  ['string_005', '"foo" instance of date'],
  ['string_006', '"foo" instance of time'],
  ['string_007', '"foo" instance of date and time'],
  ['string_008', '"foo" instance of list<Any>'],
  ['string_009', '"foo" instance of years and months duration'],
  ['string_010', '"foo" instance of days and time duration'],
  ['string_012', '"foo" instance of function<>->Any'],
  ['boolean_001', 'true instance of Any'],
  ['boolean_002', 'true instance of number'],
  ['boolean_003', 'true instance of string'],
  ['boolean_004', 'true instance of boolean'],
  ['boolean_005', 'true instance of date'],
  ['boolean_006', 'true instance of time'],
  ['boolean_007', 'true instance of date and time'],
  ['boolean_008', 'true instance of list<Any>'],
  ['boolean_009', 'true instance of years and months duration'],
  ['boolean_010', 'true instance of days and time duration'],
  ['boolean_012', 'true instance of function<>->Any'],
  ['date_001', 'date("2018-12-08") instance of Any'],
  ['date_002', 'date("2018-12-08") instance of number'],
  ['date_003', 'date("2018-12-08") instance of string'],
  ['date_004', 'date("2018-12-08") instance of boolean'],
  ['date_005', 'date("2018-12-08") instance of date'],
  ['date_006', 'date("2018-12-08") instance of time'],
  ['date_007', 'date("2018-12-08") instance of date and time'],
  ['date_008', 'date("2018-12-08") instance of list<Any>'],
  ['date_009', 'date("2018-12-08") instance of years and months duration'],
  ['date_010', 'date("2018-12-08") instance of days and time duration'],
  ['date_012', 'date("2018-12-08") instance of function<>->Any'],
  ['time_001', 'time("10:30:00") instance of Any'],
  ['time_002', 'time("10:30:00") instance of number'],
  ['time_003', 'time("10:30:00") instance of string'],
  ['time_004', 'time("10:30:00") instance of boolean'],
  ['time_005', 'time("10:30:00") instance of date'],
  ['time_006', 'time("10:30:00") instance of time'],
  ['time_007', 'time("10:30:00") instance of date and time'],
  ['time_008', 'time("10:30:00") instance of list<Any>'],
  ['time_009', 'time("10:30:00") instance of years and months duration'],
  ['time_010', 'time("10:30:00") instance of days and time duration'],
  ['time_012', 'time("10:30:00") instance of function<>->Any'],
  ['list_001', '[1,2,3] instance of Any'],
  ['list_002', '[1,2,3] instance of number'],
  ['list_003', '[1,2,3] instance of string'],
  ['list_004', '[1,2,3] instance of boolean'],
  ['list_005', '[1,2,3] instance of date'],
  ['list_006', '[1,2,3] instance of time'],
  ['list_007', '[1,2,3] instance of date and time'],
  ['list_008', '[1,2,3] instance of list<Any>'],
  ['list_009', '[1,2,3] instance of years and months duration'],
  ['list_010', '[1,2,3] instance of days and time duration'],
  ['list_012', '[1,2,3] instance of function<>->Any'],
  ['list_016', '[1] instance of number'],
  ['list_020', '[{a: "a", b: "b"}] instance of list<context<a: string, b: string>>'],
  ['ym_duration_001', 'duration("P1Y") instance of Any'],
  ['ym_duration_002', 'duration("P1Y") instance of number'],
  ['ym_duration_003', 'duration("P1Y") instance of string'],
  ['ym_duration_004', 'duration("P1Y") instance of boolean'],
  ['ym_duration_005', 'duration("P1Y") instance of date'],
  ['ym_duration_006', 'duration("P1Y") instance of time'],
  ['ym_duration_007', 'duration("P1Y") instance of date and time'],
  ['ym_duration_008', 'duration("P1Y") instance of list<Any>'],
  ['ym_duration_009', 'duration("P1Y") instance of years and months duration'],
  ['ym_duration_010', 'duration("P1Y") instance of days and time duration'],
  ['ym_duration_012', 'duration("P1Y") instance of function<>->Any'],
  ['dt_duration_001', 'duration("P1D") instance of Any'],
  ['dt_duration_002', 'duration("P1D") instance of number'],
  ['dt_duration_003', 'duration("P1D") instance of string'],
  ['dt_duration_004', 'duration("P1D") instance of boolean'],
  ['dt_duration_005', 'duration("P1D") instance of date'],
  ['dt_duration_006', 'duration("P1D") instance of time'],
  ['dt_duration_007', 'duration("P1D") instance of date and time'],
  ['dt_duration_008', 'duration("P1D") instance of list<Any>'],
  ['dt_duration_009', 'duration("P1D") instance of years and months duration'],
  ['dt_duration_010', 'duration("P1D") instance of days and time duration'],
  ['dt_duration_012', 'duration("P1D") instance of function<>->Any'],
  ['context_001', '{a: "foo"} instance of Any'],
  ['context_002', '{a: "foo"} instance of number'],
  ['context_003', '{a: "foo"} instance of string'],
  ['context_004', '{a: "foo"} instance of boolean'],
  ['context_005', '{a: "foo"} instance of date'],
  ['context_006', '{a: "foo"} instance of time'],
  ['context_007', '{a: "foo"} instance of date and time'],
  ['context_008', '{a: "foo"} instance of list<Any>'],
  ['context_009', '{a: "foo"} instance of years and months duration'],
  ['context_010', '{a: "foo"} instance of days and time duration'],
  ['context_012', '{a: "foo"} instance of function<>->Any'],
  ['context_018', '{a: "foo"} instance of context<a: string>'],
  ['context_019', '{a: null} instance of context<a: string>'],
  ['context_020', '{a: "123", b: 123} instance of context<a: string>'],
  ['context_021', '{a: "123", b: 123} instance of context<a: string, b: number>'],
  ['context_022', '{a: "123"} instance of context<a: number>'],
  ['context_023', '{a: {b: 123}} instance of context<a: context<b: number>>'],
  ['context_024', '{a: {b: 123}} instance of context<a: context<b: string>>'],
  ['function_001', '(function() "foo") instance of Any'],
  ['function_002', '(function() "foo") instance of number'],
  ['function_003', '(function() "foo") instance of string'],
  ['function_004', '(function() "foo") instance of boolean'],
  ['function_005', '(function() "foo") instance of date'],
  ['function_006', '(function() "foo") instance of time'],
  ['function_007', '(function() "foo") instance of date and time'],
  ['function_008', '(function() "foo") instance of list<Any>'],
  ['function_009', '(function() "foo") instance of years and months duration'],
  ['function_010', '(function() "foo") instance of days and time duration'],
];

describe('FEEL TCK / 0070-feel-instance-of', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('null_001: null instance of Any is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_001), false), 'null_001').toBe(true);
  });
  it('null_002: null instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_002), false), 'null_002').toBe(true);
  });
  it('null_003: null instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_003), false), 'null_003').toBe(true);
  });
  it('null_004: null instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_004), false), 'null_004').toBe(true);
  });
  it('null_005: null instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_005), false), 'null_005').toBe(true);
  });
  it('null_006: null instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_006), false), 'null_006').toBe(true);
  });
  it('null_007: null instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_007), false), 'null_007').toBe(true);
  });
  it('null_008: null instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_008), false), 'null_008').toBe(true);
  });
  it('null_009: null instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_009), false), 'null_009').toBe(true);
  });
  it('null_010: null instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_010), false), 'null_010').toBe(true);
  });
  it('null_012: null instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.null_012), false), 'null_012').toBe(true);
  });
  it('number_001: number instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_001), true), 'number_001').toBe(true);
  });
  it('number_002: number instance of number is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_002), true), 'number_002').toBe(true);
  });
  it('number_003: number instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_003), false), 'number_003').toBe(true);
  });
  it('number_004: number instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_004), false), 'number_004').toBe(true);
  });
  it('number_005: number instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_005), false), 'number_005').toBe(true);
  });
  it('number_006: number instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_006), false), 'number_006').toBe(true);
  });
  it('number_007: number instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_007), false), 'number_007').toBe(true);
  });
  it('number_008: number instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_008), false), 'number_008').toBe(true);
  });
  it('number_009: number instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_009), false), 'number_009').toBe(true);
  });
  it('number_010: number instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_010), false), 'number_010').toBe(true);
  });
  it('number_012: number instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_012), false), 'number_012').toBe(true);
  });
  it('string_001: string instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_001), true), 'string_001').toBe(true);
  });
  it('string_002: string instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_002), false), 'string_002').toBe(true);
  });
  it('string_003: string instance of string is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_003), true), 'string_003').toBe(true);
  });
  it('string_004: string instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_004), false), 'string_004').toBe(true);
  });
  it('string_005: string instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_005), false), 'string_005').toBe(true);
  });
  it('string_006: string instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_006), false), 'string_006').toBe(true);
  });
  it('string_007: string instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_007), false), 'string_007').toBe(true);
  });
  it('string_008: string instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_008), false), 'string_008').toBe(true);
  });
  it('string_009: string instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_009), false), 'string_009').toBe(true);
  });
  it('string_010: string instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_010), false), 'string_010').toBe(true);
  });
  it('string_012: string instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_012), false), 'string_012').toBe(true);
  });
  it('boolean_001: boolean instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_001), true), 'boolean_001').toBe(true);
  });
  it('boolean_002: boolean instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_002), false), 'boolean_002').toBe(true);
  });
  it('boolean_003: boolean instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_003), false), 'boolean_003').toBe(true);
  });
  it('boolean_004: boolean instance of boolean is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_004), true), 'boolean_004').toBe(true);
  });
  it('boolean_005: boolean instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_005), false), 'boolean_005').toBe(true);
  });
  it('boolean_006: boolean instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_006), false), 'boolean_006').toBe(true);
  });
  it('boolean_007: boolean instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_007), false), 'boolean_007').toBe(true);
  });
  it('boolean_008: boolean instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_008), false), 'boolean_008').toBe(true);
  });
  it('boolean_009: boolean instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_009), false), 'boolean_009').toBe(true);
  });
  it('boolean_010: boolean instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_010), false), 'boolean_010').toBe(true);
  });
  it('boolean_012: boolean instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_012), false), 'boolean_012').toBe(true);
  });
  it('date_001: date instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_001), true), 'date_001').toBe(true);
  });
  it('date_002: date instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_002), false), 'date_002').toBe(true);
  });
  it('date_003: date instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_003), false), 'date_003').toBe(true);
  });
  it('date_004: date instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_004), false), 'date_004').toBe(true);
  });
  it('date_005: date instance of date is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_005), true), 'date_005').toBe(true);
  });
  it('date_006: date instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_006), false), 'date_006').toBe(true);
  });
  it('date_007: date instance of date and time is false - spec 1.2 "Examples of equivalence\n            and conformance relations" table shows date and confirming to date\n            and time - which I believe is wrong - it is the other way around', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_007), false), 'date_007').toBe(true);
  });
  it('date_008: date instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_008), false), 'date_008').toBe(true);
  });
  it('date_009: date instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_009), false), 'date_009').toBe(true);
  });
  it('date_010: date instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_010), false), 'date_010').toBe(true);
  });
  it('date_012: date instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_012), false), 'date_012').toBe(true);
  });
  it('time_001: time instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_001), true), 'time_001').toBe(true);
  });
  it('time_002: time instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_002), false), 'time_002').toBe(true);
  });
  it('time_003: time instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_003), false), 'time_003').toBe(true);
  });
  it('time_004: time instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_004), false), 'time_004').toBe(true);
  });
  it('time_005: time instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_005), false), 'time_005').toBe(true);
  });
  it('time_006: time instance of time is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_006), true), 'time_006').toBe(true);
  });
  it('time_007: time instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_007), false), 'time_007').toBe(true);
  });
  it('time_008: time instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_008), false), 'time_008').toBe(true);
  });
  it('time_009: time instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_009), false), 'time_009').toBe(true);
  });
  it('time_010: time instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_010), false), 'time_010').toBe(true);
  });
  it('time_012: time instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_012), false), 'time_012').toBe(true);
  });
  it('list_001: list instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_001), true), 'list_001').toBe(true);
  });
  it('list_002: list instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_002), false), 'list_002').toBe(true);
  });
  it('list_003: list instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_003), false), 'list_003').toBe(true);
  });
  it('list_004: list instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_004), false), 'list_004').toBe(true);
  });
  it('list_005: list instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_005), false), 'list_005').toBe(true);
  });
  it('list_006: list instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_006), false), 'list_006').toBe(true);
  });
  it('list_007: list instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_007), false), 'list_007').toBe(true);
  });
  it('list_008: list instance of list is rrue', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_008), true), 'list_008').toBe(true);
  });
  it('list_009: list instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_009), false), 'list_009').toBe(true);
  });
  it('list_010: list instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_010), false), 'list_010').toBe(true);
  });
  it('list_012: list instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_012), false), 'list_012').toBe(true);
  });
  it('list_016: singleton list is not instance of element type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_016), false), 'list_016').toBe(true);
  });
  it('list_020: list is an instance of inline list of inline context type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.list_020), true), 'list_020').toBe(true);
  });
  it('ym_duration_001: years and months duration instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_001), true), 'ym_duration_001').toBe(true);
  });
  it('ym_duration_002: years and months duration instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_002), false), 'ym_duration_002').toBe(true);
  });
  it('ym_duration_003: years and months duration instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_003), false), 'ym_duration_003').toBe(true);
  });
  it('ym_duration_004: years and months duration instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_004), false), 'ym_duration_004').toBe(true);
  });
  it('ym_duration_005: years and months duration instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_005), false), 'ym_duration_005').toBe(true);
  });
  it('ym_duration_006: years and months duration instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_006), false), 'ym_duration_006').toBe(true);
  });
  it('ym_duration_007: years and months duration instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_007), false), 'ym_duration_007').toBe(true);
  });
  it('ym_duration_008: years and months duration instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_008), false), 'ym_duration_008').toBe(true);
  });
  it('ym_duration_009: years and months duration instance of years and months duration is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_009), true), 'ym_duration_009').toBe(true);
  });
  it('ym_duration_010: years and months duration instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_010), false), 'ym_duration_010').toBe(true);
  });
  it('ym_duration_012: years and months duration instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_012), false), 'ym_duration_012').toBe(true);
  });
  it('dt_duration_001: days and time duration instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_001), true), 'dt_duration_001').toBe(true);
  });
  it('dt_duration_002: days and time duration instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_002), false), 'dt_duration_002').toBe(true);
  });
  it('dt_duration_003: days and time duration instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_003), false), 'dt_duration_003').toBe(true);
  });
  it('dt_duration_004: days and time duration instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_004), false), 'dt_duration_004').toBe(true);
  });
  it('dt_duration_005: days and time duration instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_005), false), 'dt_duration_005').toBe(true);
  });
  it('dt_duration_006: days and time duration instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_006), false), 'dt_duration_006').toBe(true);
  });
  it('dt_duration_007: days and time duration instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_007), false), 'dt_duration_007').toBe(true);
  });
  it('dt_duration_008: days and time durationinstance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_008), false), 'dt_duration_008').toBe(true);
  });
  it('dt_duration_009: days and time duration instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_009), false), 'dt_duration_009').toBe(true);
  });
  it('dt_duration_010: days and time duration instance of days and time duration is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_010), true), 'dt_duration_010').toBe(true);
  });
  it('dt_duration_012: days and time duration instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_012), false), 'dt_duration_012').toBe(true);
  });
  it('context_001: context instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_001), true), 'context_001').toBe(true);
  });
  it('context_002: context instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_002), false), 'context_002').toBe(true);
  });
  it('context_003: context instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_003), false), 'context_003').toBe(true);
  });
  it('context_004: context instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_004), false), 'context_004').toBe(true);
  });
  it('context_005: context instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_005), false), 'context_005').toBe(true);
  });
  it('context_006: context instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_006), false), 'context_006').toBe(true);
  });
  it('context_007: context instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_007), false), 'context_007').toBe(true);
  });
  it('context_008: context instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_008), false), 'context_008').toBe(true);
  });
  it('context_009: context instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_009), false), 'context_009').toBe(true);
  });
  it('context_010: context instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_010), false), 'context_010').toBe(true);
  });
  it('context_012: context instance of function is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_012), false), 'context_012').toBe(true);
  });
  it('context_018: context instance conforms to equivalent type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_018), true), 'context_018').toBe(true);
  });
  it('context_019: context with null value conforms to specific type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_019), true), 'context_019').toBe(true);
  });
  it('context_020: context with multiple properties conforms to type with equivalent single property ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_020), true), 'context_020').toBe(true);
  });
  it('context_021: context with multiple properties conforms to type with equivalent multiple properties ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_021), true), 'context_021').toBe(true);
  });
  it('context_022: context with non-conforming property does not match type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_022), false), 'context_022').toBe(true);
  });
  it('context_023: context with nested context conforms to type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_023), true), 'context_023').toBe(true);
  });
  it('context_024: context with nested context dot not conform to type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_024), false), 'context_024').toBe(true);
  });
  it('function_001: function instance of Any is true', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_001), true), 'function_001').toBe(true);
  });
  it('function_002: function instance of number is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_002), false), 'function_002').toBe(true);
  });
  it('function_003: function instance of string is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_003), false), 'function_003').toBe(true);
  });
  it('function_004: function instance of boolean is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_004), false), 'function_004').toBe(true);
  });
  it('function_005: function instance of date is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_005), false), 'function_005').toBe(true);
  });
  it('function_006: function instance of time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_006), false), 'function_006').toBe(true);
  });
  it('function_007: function instance of date and time is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_007), false), 'function_007').toBe(true);
  });
  it('function_008: function instance of list is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_008), false), 'function_008').toBe(true);
  });
  it('function_009: function instance of years and months duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_009), false), 'function_009').toBe(true);
  });
  it('function_010: function instance of days and time duration is false', () => {
    const ctx = run({});
    expect(aeq(n(ctx.function_010), false), 'function_010').toBe(true);
  });
});
