// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['number_001', '0 between 1 and 10'],
  ['number_002', '1 between 1 and 10'],
  ['number_003', '5 between 1 and 10'],
  ['number_004', '10 between 1 and 10'],
  ['number_005', '11 between 1 and 10'],
  ['string_001', '"a" between "b" and "d"'],
  ['string_002', '"b" between "b" and "d"'],
  ['string_003', '"c" between "b" and "d"'],
  ['string_004', '"d" between "b" and "d"'],
  ['string_005', '"e" between "b" and "d"'],
  ['date_001', 'date("2018-12-01") between date("2018-12-02") and date("2018-12-04")'],
  ['date_002', 'date("2018-12-02") between date("2018-12-02") and date("2018-12-04")'],
  ['date_003', 'date("2018-12-03") between date("2018-12-02") and date("2018-12-04")'],
  ['date_004', 'date("2018-12-04") between date("2018-12-02") and date("2018-12-04")'],
  ['date_005', 'date("2018-12-05") between date("2018-12-02") and date("2018-12-04")'],
  ['time_001', 'time("10:31:00") between time("10:32:00") and time("10:34:00")'],
  ['time_002', 'time("10:32:00") between time("10:32:00") and time("10:34:00")'],
  ['time_003', 'time("10:33:00") between time("10:32:00") and time("10:34:00")'],
  ['time_004', 'time("10:34:00") between time("10:32:00") and time("10:34:00")'],
  ['time_005', 'time("10:35:00") between time("10:32:00") and time("10:34:00")'],
  [
    'datetime_001',
    'date and time("2018-12-01T10:30:00") between date and time("2018-12-02T10:30:00") and date and time("2018-12-04T10:30:00")',
  ],
  [
    'datetime_002',
    'date and time("2018-12-02T10:30:00") between date and time("2018-12-02T10:30:00") and date and time("2018-12-04T10:30:00")',
  ],
  [
    'datetime_003',
    'date and time("2018-12-03T10:30:00") between date and time("2018-12-02T10:30:00") and date and time("2018-12-04T10:30:00")',
  ],
  [
    'datetime_004',
    'date and time("2018-12-04T10:30:00") between date and time("2018-12-02T10:30:00") and date and time("2018-12-04T10:30:00")',
  ],
  [
    'datetime_005',
    'date and time("2018-12-05T10:30:00") between date and time("2018-12-02T10:30:00") and date and time("2018-12-04T10:30:00")',
  ],
  ['ym_duration_001', 'duration("P1Y") between duration("P2Y") and duration("P4Y")'],
  ['ym_duration_002', 'duration("P2Y") between duration("P2Y") and duration("P4Y")'],
  ['ym_duration_003', 'duration("P3Y") between duration("P2Y") and duration("P4Y")'],
  ['ym_duration_004', 'duration("P4Y") between duration("P2Y") and duration("P4Y")'],
  ['ym_duration_005', 'duration("P5Y") between duration("P2Y") and duration("P4Y")'],
  ['dt_duration_001', 'duration("P1D") between duration("P2D") and duration("P4D")'],
  ['dt_duration_002', 'duration("P2D") between duration("P2D") and duration("P4D")'],
  ['dt_duration_003', 'duration("P3D") between duration("P2D") and duration("P4D")'],
  ['dt_duration_004', 'duration("P4D") between duration("P2D") and duration("P4D")'],
  ['dt_duration_005', 'duration("P5D") between duration("P2D") and duration("P4D")'],
  ['null_001', 'null between 1 and 10'],
  ['null_002', '2 between null and 10'],
  ['null_003', '2 between 1 and null'],
];

describe('FEEL TCK / 0071-feel-between', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('number_001: before', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_001), false), 'number_001').toBe(true);
  });
  it('number_002: start', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_002), true), 'number_002').toBe(true);
  });
  it('number_003: between', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_003), true), 'number_003').toBe(true);
  });
  it('number_004: end', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_004), true), 'number_004').toBe(true);
  });
  it('number_005: after', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_005), false), 'number_005').toBe(true);
  });
  it('string_001: before', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_001), false), 'string_001').toBe(true);
  });
  it('string_002: start', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_002), true), 'string_002').toBe(true);
  });
  it('string_003: between', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_003), true), 'string_003').toBe(true);
  });
  it('string_004: end', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_004), true), 'string_004').toBe(true);
  });
  it('string_005: after', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_005), false), 'string_005').toBe(true);
  });
  it('date_001: before', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_001), false), 'date_001').toBe(true);
  });
  it('date_002: start', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_002), true), 'date_002').toBe(true);
  });
  it('date_003: between', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_003), true), 'date_003').toBe(true);
  });
  it('date_004: end', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_004), true), 'date_004').toBe(true);
  });
  it('date_005: after', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_005), false), 'date_005').toBe(true);
  });
  it('time_001: before', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_001), false), 'time_001').toBe(true);
  });
  it('time_002: start', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_002), true), 'time_002').toBe(true);
  });
  it('time_003: between', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_003), true), 'time_003').toBe(true);
  });
  it('time_004: end', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_004), true), 'time_004').toBe(true);
  });
  it('time_005: after', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_005), false), 'time_005').toBe(true);
  });
  it('datetime_001: before', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_001), false), 'datetime_001').toBe(true);
  });
  it('datetime_002: start', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_002), true), 'datetime_002').toBe(true);
  });
  it('datetime_003: between', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_003), true), 'datetime_003').toBe(true);
  });
  it('datetime_004: end', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_004), true), 'datetime_004').toBe(true);
  });
  it('datetime_005: after', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_005), false), 'datetime_005').toBe(true);
  });
  it('ym_duration_001: before', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_001), false), 'ym_duration_001').toBe(true);
  });
  it('ym_duration_002: start', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_002), true), 'ym_duration_002').toBe(true);
  });
  it('ym_duration_003: between', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_003), true), 'ym_duration_003').toBe(true);
  });
  it('ym_duration_004: end', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_004), true), 'ym_duration_004').toBe(true);
  });
  it('ym_duration_005: after', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_005), false), 'ym_duration_005').toBe(true);
  });
  it('dt_duration_001: before', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_001), false), 'dt_duration_001').toBe(true);
  });
  it('dt_duration_002: start', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_002), true), 'dt_duration_002').toBe(true);
  });
  it('dt_duration_003: between', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_003), true), 'dt_duration_003').toBe(true);
  });
  it('dt_duration_004: end', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_004), true), 'dt_duration_004').toBe(true);
  });
  it('dt_duration_005: after', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_005), false), 'dt_duration_005').toBe(true);
  });
  it('null_001: null test value', () => {
    const ctx = run({});
    expect(n(ctx.null_001)).toBeNull();
  });
  it('null_002: null start value', () => {
    const ctx = run({});
    expect(n(ctx.null_002)).toBeNull();
  });
  it('null_003: null end value', () => {
    const ctx = run({});
    expect(n(ctx.null_003)).toBeNull();
  });
});
