// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['context_001', '{a: "foo"}.a'],
  ['date_001', 'date("2018-12-10").year'],
  ['date_002', 'date("2018-12-10").month'],
  ['date_003', 'date("2018-12-10").day'],
  ['date_004', 'date("2018-12-10").weekday'],
  ['dateTime_001', 'date and time("2018-12-10T10:30:01").year'],
  ['dateTime_002', 'date and time("2018-12-10T10:30:01").month'],
  ['dateTime_003', 'date and time("2018-12-10T10:30:01").day'],
  ['dateTime_004', 'date and time("2018-12-10T10:30:01").weekday'],
  ['dateTime_005', 'date and time("2018-12-10T10:30:01").hour'],
  ['dateTime_005_a', 'date and time("2018-12-10").hour'],
  ['dateTime_006', 'date and time("2018-12-10T10:30:01").minute'],
  ['dateTime_006_a', 'date and time("2018-12-10").minute'],
  ['dateTime_007', 'date and time("2018-12-10T10:30:01").second'],
  ['dateTime_007_a', 'date and time("2018-12-10").second'],
  ['dateTime_008', 'date and time("2018-12-10T10:30:00+05:00").time offset'],
  ['dateTime_008_a', 'date and time("2018-12-10T10:30:00").time offset'],
  ['dateTime_009', 'date and time("2018-12-10T10:30:00@Etc/UTC").timezone'],
  ['dateTime_009_a', 'date and time("2018-12-10T10:30:00").timezone'],
  ['time_001', 'time("10:30:01").hour'],
  ['time_002', 'time("10:30:01").minute'],
  ['time_003', 'time("10:30:01").second'],
  ['time_004', 'time("10:30:00+05:00").time offset'],
  ['time_004_a', 'time("10:30:00").time offset'],
  ['time_005', 'time("10:30:00@Etc/UTC").timezone'],
  ['time_005_a', 'time("10:30:00").timezone'],
  ['ym_duration_001', 'duration("P1Y2M").years'],
  ['ym_duration_001_a', 'duration("P2M").years'],
  ['ym_duration_002', 'duration("P2M").months'],
  ['ym_duration_002_a', 'duration("P1Y").months'],
  ['ym_duration_003', 'duration("P1Y").days'],
  ['ym_duration_004', 'duration("P1Y").hours'],
  ['ym_duration_005', 'duration("P1Y").minutes'],
  ['ym_duration_006', 'duration("P1Y").seconds'],
  ['dt_duration_001', 'duration("P1D").years'],
  ['dt_duration_002', 'duration("P1D").months'],
  ['dt_duration_003', 'duration("P1D").days'],
  ['dt_duration_003_a', 'duration("PT2H").days'],
  ['dt_duration_004', 'duration("PT2H").hours'],
  ['dt_duration_004_a', 'duration("P1D").hours'],
  ['dt_duration_005', 'duration("PT2M").minutes'],
  ['dt_duration_005_a', 'duration("P1D").minutes'],
  ['dt_duration_006', 'duration("PT2S").seconds'],
  ['dt_duration_006_a', 'duration("P1D").seconds'],
];

describe('FEEL TCK / 0074-feel-properties', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('context_001', () => {
    const ctx = run({});
    expect(aeq(n(ctx.context_001), 'foo'), 'context_001').toBe(true);
  });
  it('date_001: date - year', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_001), 2018), 'date_001').toBe(true);
  });
  it('date_002: date - month', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_002), 12), 'date_002').toBe(true);
  });
  it('date_003: date - day', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_003), 10), 'date_003').toBe(true);
  });
  it('date_004: date - weekday', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_004), 1), 'date_004').toBe(true);
  });
  it('dateTime_001: dateTime -  year', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_001), 2018), 'dateTime_001').toBe(true);
  });
  it('dateTime_002: dateTime -  month', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_002), 12), 'dateTime_002').toBe(true);
  });
  it('dateTime_003: dateTime -  day', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_003), 10), 'dateTime_003').toBe(true);
  });
  it('dateTime_004: dateTime -  weekday', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_004), 1), 'dateTime_004').toBe(true);
  });
  it('dateTime_005: dateTime -  hour', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_005), 10), 'dateTime_005').toBe(true);
  });
  it('dateTime_005_a: dateTime -  hour when no time specified', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_005_a), 0), 'dateTime_005_a').toBe(true);
  });
  it('dateTime_006: dateTime -  minute', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_006), 30), 'dateTime_006').toBe(true);
  });
  it('dateTime_006_a: dateTime -  minute when no time specified', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_006_a), 0), 'dateTime_006_a').toBe(true);
  });
  it('dateTime_007: dateTime -  second', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_007), 1), 'dateTime_007').toBe(true);
  });
  it('dateTime_007_a: dateTime -  second when no time specified', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_007_a), 0), 'dateTime_007_a').toBe(true);
  });
  it('dateTime_008: dateTime -  time offset when set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_008), 'PT5H'), 'dateTime_008').toBe(true);
  });
  it('dateTime_008_a: dateTime -  time offset when not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_008_a), null), 'dateTime_008_a').toBe(true);
  });
  it('dateTime_009: dateTime -  timezone when set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_009), 'Etc/UTC'), 'dateTime_009').toBe(true);
  });
  it('dateTime_009_a: dateTime -  timezone when not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dateTime_009_a), null), 'dateTime_009_a').toBe(true);
  });
  it('time_001: time -  hour', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_001), 10), 'time_001').toBe(true);
  });
  it('time_002: time -  minute', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_002), 30), 'time_002').toBe(true);
  });
  it('time_003: time -  second', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_003), 1), 'time_003').toBe(true);
  });
  it('time_004: time -  time offset when set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_004), 'PT5H'), 'time_004').toBe(true);
  });
  it('time_004_a: time -  time offset when not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_004_a), null), 'time_004_a').toBe(true);
  });
  it('time_005_a: time -  timezone when not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_005_a), null), 'time_005_a').toBe(true);
  });
  it('ym_duration_001: ym duration -  years', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_001), 1), 'ym_duration_001').toBe(true);
  });
  it('ym_duration_001_a: ym duration - years not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_001_a), 0), 'ym_duration_001_a').toBe(true);
  });
  it('ym_duration_002: ym duration - month', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_002), 2), 'ym_duration_002').toBe(true);
  });
  it('ym_duration_002_a: ym duration - months not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_002_a), 0), 'ym_duration_002_a').toBe(true);
  });
  it('ym_duration_003: ym duration - days is null', () => {
    const ctx = run({});
    expect(n(ctx.ym_duration_003)).toBeNull();
  });
  it('ym_duration_004: ym duration - hours is null', () => {
    const ctx = run({});
    expect(n(ctx.ym_duration_004)).toBeNull();
  });
  it('ym_duration_005: ym duration - minutes is null', () => {
    const ctx = run({});
    expect(n(ctx.ym_duration_005)).toBeNull();
  });
  it('ym_duration_006: ym duration - seconds is null', () => {
    const ctx = run({});
    expect(n(ctx.ym_duration_006)).toBeNull();
  });
  it('dt_duration_001: dt duration - years is null', () => {
    const ctx = run({});
    expect(n(ctx.dt_duration_001)).toBeNull();
  });
  it('dt_duration_002: dt duration - months is null', () => {
    const ctx = run({});
    expect(n(ctx.dt_duration_002)).toBeNull();
  });
  it('dt_duration_003: dt duration - days', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_003), 1), 'dt_duration_003').toBe(true);
  });
  it('dt_duration_003_a: dt duration - days is not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_003_a), 0), 'dt_duration_003_a').toBe(true);
  });
  it('dt_duration_004: dt duration - hours', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_004), 2), 'dt_duration_004').toBe(true);
  });
  it('dt_duration_004_a: dt duration - hours is not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_004_a), 0), 'dt_duration_004_a').toBe(true);
  });
  it('dt_duration_005: dt duration - minutes', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_005), 2), 'dt_duration_005').toBe(true);
  });
  it('dt_duration_005_a: dt duration - minutes is not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_005_a), 0), 'dt_duration_005_a').toBe(true);
  });
  it('dt_duration_006: dt duration - seconds', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_006), 2), 'dt_duration_006').toBe(true);
  });
  it('dt_duration_006_a: dt duration - seconds is not set', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_006_a), 0), 'dt_duration_006_a').toBe(true);
  });
});
