// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [['decision_001', '0.0 / 0.0']];

describe('FEEL TCK / 0077-feel-nan', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('decision_001: NaN from zero integer division', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_001), null), 'decision_001').toBe(true);
  });
});
