// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision_001', 'get entries()'],
  ['decision_002', 'get entries({a: "foo"}, {b: "bar"})'],
  ['decision_003', 'get entries(null)'],
  ['decision_004', 'get entries({a: "foo", b: "bar"})'],
  ['decision_005', 'get entries(m:{a: "foo", b: "bar"})'],
  ['decision_006', 'get entries(map:{a: "foo", b: "bar"})'],
  ['decision_007', 'get entries(123)'],
  ['decision_008', 'get entries([1,2,3])'],
  ['decision_009', 'get entries({})'],
];

describe('FEEL TCK / 0081-feel-getentries-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('decision_001: no param', () => {
    const ctx = run({});
    expect(n(ctx.decision_001)).toBeNull();
  });
  it('decision_002: two many params', () => {
    const ctx = run({});
    expect(n(ctx.decision_002)).toBeNull();
  });
  it('decision_003: null params', () => {
    const ctx = run({});
    expect(n(ctx.decision_003)).toBeNull();
  });
  it('decision_004: get a value', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx.decision_004), [
        { key: 'a', value: 'foo' },
        { key: 'b', value: 'bar' },
      ]),
      'decision_004',
    ).toBe(true);
  });
  it('decision_005: named param', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx.decision_005), [
        { key: 'a', value: 'foo' },
        { key: 'b', value: 'bar' },
      ]),
      'decision_005',
    ).toBe(true);
  });
  it('decision_006: bad named param', () => {
    const ctx = run({});
    expect(n(ctx.decision_006)).toBeNull();
  });
  it('decision_007: not a map as param', () => {
    const ctx = run({});
    expect(n(ctx.decision_007)).toBeNull();
  });
  it('decision_008: not a map as param', () => {
    const ctx = run({});
    expect(n(ctx.decision_008)).toBeNull();
  });
  it('decision_009: empty map as param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_009), []), 'decision_009').toBe(true);
  });
});
