// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision_001', 'string length("\\u0009")'],
  ['decision_001_a', 'string length("\\U01F40E")'],
  ['decision_001_b', '"\\U01F40E" = "🐎"'],
  ['decision_002', 'string length("\\\\u0009")'],
  ['decision_003', 'string length("\\uD83D\\uDCA9")'],
  ['decision_003_a', 'string length("\\ud83d\\udca9")'],
  ['decision_004', 'string length("\\ud83d\\udc0e\\uD83D\\uDE00")'],
  ['decision_004_a', 'string length("🐎😀")'],
  ['decision_005', 'contains("\\ud83d\\udc0e\\uD83D\\uDE00", "\\uD83D\\uDE00")'],
  ['decision_005_a', 'contains("\\ud83d\\udc0e\\uD83D\\uDE00", "😀")'],
  ['decision_006', '{🐎: "bar"}'],
  ['decision_007', '{🐎: "😀"}'],
  ['endswith_001', 'ends with("\\ud83d\\udc0e\\uD83D\\uDE00", "\\uD83D\\uDE00")'],
  ['endswith_002', 'ends with("\\ud83d\\udc0e\\uD83D\\uDE00", "😀")'],
  ['substring_004', 'substring("\\U01F40Efoo", 2) = "foo"'],
];

describe('FEEL TCK / 0083-feel-unicode', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('decision_001: Assert length of string with 4 digit unicode char', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_001), 1), 'decision_001').toBe(true);
  });
  it('decision_001_a: Assert length of string with 6 digit unicode char', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_001_a), 1), 'decision_001_a').toBe(true);
  });
  it('decision_001_b: Assert string with 6 digit unicode char', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_001_b), true), 'decision_001_b').toBe(true);
  });
  it('decision_002: Escaped encoded unicode', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_002), 6), 'decision_002').toBe(true);
  });
  it('decision_003: encoded unicode - supplementary char (uppercase)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_003), 1), 'decision_003').toBe(true);
  });
  it('decision_003_a: encoded unicode - supplementary char (lowercase)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_003_a), 1), 'decision_003_a').toBe(true);
  });
  it('decision_004: encoded unicode - string literal with supplementary chars', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_004), 2), 'decision_004').toBe(true);
  });
  it('decision_004_a: literal unicode - supplementary 2 char - in string literal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_004_a), 2), 'decision_004_a').toBe(true);
  });
  it('decision_005: encoded unicode - string contains with supplementary chars', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_005), true), 'decision_005').toBe(true);
  });
  it('decision_005_a: literal unicode - string contains with supplementary chars', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_005_a), true), 'decision_005_a').toBe(true);
  });
  it('decision_006: literal unicode - context property name as supplementary character', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_006), { '🐎': 'bar' }), 'decision_006').toBe(true);
  });
  it('decision_007: literal unicode - context property and value supplementary characters', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_007), { '🐎': '😀' }), 'decision_007').toBe(true);
  });
  it('endswith_001: literal unicode - string ends with with supplementary chars', () => {
    const ctx = run({});
    expect(aeq(n(ctx.endswith_001), true), 'endswith_001').toBe(true);
  });
  it('substring_004: escape 6 digit unicode substring', () => {
    const ctx = run({});
    expect(aeq(n(ctx.substring_004), true), 'substring_004').toBe(true);
  });
});
