// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision_001', 'for i in [1,2,3] return i + 1'],
  ['decision_002', 'for i in [1,2,3], j in [4,5] return i + j'],
  ['decision_003', 'for i in [] return i'],
  ['decision_007', 'for i in 2..4 return i'],
  ['decision_008', 'for i in 4..2 return i'],
  ['decision_009', 'for i in -1..1 return i'],
  ['decision_010', 'for i in 1..-1 return i'],
  ['decision_011', 'for i in 1..1 return i'],
  ['decision_012', 'for i in 1+1..1+3 return i'],
  ['decision_013', 'for i in 0..4 return if i = 0 then 1 else i * partial[-1]'],
  ['days in weekend', '["saturday", "sunday"]'],
  ['decision_014', 'for i in days in weekend return if i = "sunday" then true else false'],
  ['decision_015', 'for x in [ [1,2], [3,4] ], y in x return y'],
  ['decision_016', 'for x in [ [1,2], [3,4] ] return for y in x return y'],
  ['decision_017', 'for i in @"1980-01-01"..@"1980-01-03" return i'],
  ['decision_018', 'for i in @"1980-01-03"..@"1980-01-01" return i'],
  ['decision_019', 'for i in "a".."z" return i'],
  ['decision_019_a', 'for i in ["a".."z"] return i'],
  ['decision_020', 'for i in @"1980-01-03T00:00:00"..@"1980-01-01T00:00:00" return i'],
  ['decision_020_a', 'for i in [@"1980-01-03T00:00:00"..@"1980-01-01T00:00:00"] return i'],
  ['decision_021', 'for i in @"00:00:00"..@"00:00:00" return i'],
  ['decision_021_a', 'for i in [@"00:00:00"..@"00:00:00"] return i'],
  ['decision_022', 'for i in @"P1D"..@"P2D" return i'],
  ['decision_022_a', 'for i in [@"P1D"..@"P2D"] return i'],
  ['decision_025', 'for i in [2..1] return i'],
];

describe('FEEL TCK / 0084-feel-for-loops', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('decision_001: Loop over number list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_001), [2, 3, 4]), 'decision_001').toBe(true);
  });
  it('decision_002: two iteration context loop over number list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_002), [5, 6, 6, 7, 7, 8]), 'decision_002').toBe(true);
  });
  it('decision_003: loop over empty list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_003), []), 'decision_003').toBe(true);
  });
  it('decision_007: numeric range iteration context - no delimiters', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_007), [2, 3, 4]), 'decision_007').toBe(true);
  });
  it('decision_008: numeric descending range iteration context - no delimiters', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_008), [4, 3, 2]), 'decision_008').toBe(true);
  });
  it('decision_009: numeric range iteration context - no delimiters - ascending from negative', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_009), [-1, 0, 1]), 'decision_009').toBe(true);
  });
  it('decision_010: numeric range iteration context - no delimiters - descending to negative', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_010), [1, 0, -1]), 'decision_010').toBe(true);
  });
  it('decision_011: numeric range iteration context - same endpoints', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_011), [1]), 'decision_011').toBe(true);
  });
  it('decision_012: expressions in range', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_012), [2, 3, 4]), 'decision_012').toBe(true);
  });
  it("decision_013: special variable 'partial' doing factorial list", () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_013), [1, 1, 2, 6, 24]), 'decision_013').toBe(true);
  });
  it("decision_014: 'in' may appear in list identifier", () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_014), [false, true]), 'decision_014').toBe(true);
  });
  it('decision_015: for loop with second iterator depending on first iterator', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_015), [1, 2, 3, 4]), 'decision_015').toBe(true);
  });
  it('decision_016: nested loops', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx.decision_016), [
        [1, 2],
        [3, 4],
      ]),
      'decision_016',
    ).toBe(true);
  });
  it('decision_017: date range increment upwards', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx.decision_017), ['1980-01-01', '1980-01-02', '1980-01-03']),
      'decision_017',
    ).toBe(true);
  });
  it('decision_018: date range increment downwards', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx.decision_018), ['1980-01-03', '1980-01-02', '1980-01-01']),
      'decision_018',
    ).toBe(true);
  });
  it('decision_019: string iteration context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_019)).toBeNull();
  });
  it('decision_019_a: string range iteration context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_019_a)).toBeNull();
  });
  it('decision_020: datetime iteration context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_020)).toBeNull();
  });
  it('decision_020_a: datetime range iteration context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_020_a)).toBeNull();
  });
  it('decision_021: time iteration context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_021)).toBeNull();
  });
  it('decision_021_a: time range iteration context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_021_a)).toBeNull();
  });
  it('decision_022: duration iteration context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_022)).toBeNull();
  });
  it('decision_022_a: duration range iteration context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_022_a)).toBeNull();
  });
  it('decision_025: invalid (descending) range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_025)).toBeNull();
  });
});
