// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision_001_2', 'function (a: number) 1 + a'],
  ['decision_001_1', 'decision_001_2(2)'],
  ['decision_002_1', 'decision_002_2(3)'],
  ['decision_007_2', 'function (a: number) a * input_007_1'],
  ['decision_007_1', 'decision_007_2(5)'],
  ['decision_010_1', 'decision_010_2(5)'],
  ['decision_010_1_a', 'decision_010_2_a(5)'],
  ['decision_013_2', 'input_013_1 * 10'],
  ['decision_018', 'sort(["a","z", "a", "z"], bkm_018)'],
];

describe('FEEL TCK / 0092-feel-lambda', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: A decision may return a user-defined-function (UDF) lambda', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_001_1), 3), 'decision_001_1').toBe(true);
  });
  it('007: A decision may return a UDF lambda with a closed over info requirement value', () => {
    const ctx = run({ input_007_1: 20 });
    expect(aeq(n(ctx.decision_007_1), 100), 'decision_007_1').toBe(true);
  });
  it('018: BKM may be passed to sort func', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_018), ['a', 'a', 'z', 'z']), 'decision_018').toBe(true);
  });
});
