// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['test_001', '@"foo"'],
  ['date_001', '@"2019-03-31" instance of date'],
  ['date_002', '@"2019-03-31"'],
  ['datetime_001', '@"2018-12-08T10:30:11" instance of date and time'],
  ['datetime_002', '@"2018-12-08T10:30:11"'],
  ['datetime_003', '@"2018-12-08T10:30:11@Australia/Melbourne" instance of date and time'],
  ['datetime_004', 'string(@"2018-12-08T10:30:11@Australia/Melbourne")'],
  ['datetime_005', '@"2018-12-08T10:30:11+11:00" instance of date and time'],
  ['datetime_006', '@"2018-12-08T10:30:11+11:00"'],
  ['time_001', '@"10:30:11" instance of time'],
  ['time_002', '@"10:30:11"'],
  ['time_003', '@"10:30:11+11:00" instance of time'],
  ['time_004', '@"10:30:11+11:00"'],
  ['time_005', '@"10:30:11@Australia/Melbourne" instance of time'],
  ['time_006', 'string(@"10:30:11@Australia/Melbourne")'],
  ['dt_duration_001', '@"P10D" instance of days and time duration'],
  ['dt_duration_002', '@"P10D"'],
  ['ym_duration_001', '@"P10Y" instance of years and months duration'],
  ['ym_duration_002', '@"P10Y"'],
];

describe('FEEL TCK / 0093-feel-at-literals', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('test_001: invalid value has null value', () => {
    const ctx = run({});
    expect(n(ctx.test_001)).toBeNull();
  });
  it('date_001: will parse date to date type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_001), true), 'date_001').toBe(true);
  });
  it('date_002: will parse date value', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_002), '2019-03-31'), 'date_002').toBe(true);
  });
  it('datetime_001: will parse to date time type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_001), true), 'datetime_001').toBe(true);
  });
  it('datetime_002: will parse date time value', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_002), '2018-12-08T10:30:11'), 'datetime_002').toBe(true);
  });
  it('datetime_003: will parse to date time with zone', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_003), true), 'datetime_003').toBe(true);
  });
  it('datetime_004: will parse date time value with zone', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx.datetime_004), '2018-12-08T10:30:11@Australia/Melbourne'),
      'datetime_004',
    ).toBe(true);
  });
  it('datetime_005: will parse to date time value with offset', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_005), true), 'datetime_005').toBe(true);
  });
  it('datetime_006: will parse date time value with offset', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_006), '2018-12-08T10:30:11+11:00'), 'datetime_006').toBe(true);
  });
  it('time_001: will parse to time type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_001), true), 'time_001').toBe(true);
  });
  it('time_002: will parse time value', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_002), '10:30:11'), 'time_002').toBe(true);
  });
  it('time_003: will parse to time + offset', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_003), true), 'time_003').toBe(true);
  });
  it('time_004: will parse time value + offset', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_004), '10:30:11+11:00'), 'time_004').toBe(true);
  });
  it('time_005: will parse to time + zone', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_005), true), 'time_005').toBe(true);
  });
  it('time_006: will parse time value + zone', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_006), '10:30:11@Australia/Melbourne'), 'time_006').toBe(true);
  });
  it('dt_duration_001: will parse to days and time duration type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_001), true), 'dt_duration_001').toBe(true);
  });
  it('dt_duration_002: will parse days and time duration value', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_002), 'P10D'), 'dt_duration_002').toBe(true);
  });
  it('ym_duration_001: will parse to years and months duration type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_001), true), 'ym_duration_001').toBe(true);
  });
  it('ym_duration_002: will parse years and months duration value', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_002), 'P10Y'), 'ym_duration_002').toBe(true);
  });
});
