// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'product([6, 3, 9, 6, 6])'],
  ['decision002', 'product([])'],
  ['decision003', 'product()'],
  ['decision003_a', 'product(null)'],
  ['decision004', 'product([1,2,null,4])'],
  ['decision005', 'product([1,2,"foo",4])'],
  ['decision006', 'product([2.5, 1, 2.5, 3])'],
  ['decision007', 'product(2,3,4)'],
  ['decision008', 'product(6)'],
  ['decision008_a', 'product([6])'],
  ['decision011', 'product(list:[6, 3, 9, 6, 6])'],
  ['decision012', 'product(list:null)'],
  ['decision013', 'product(l:[2, 4, 7, 5])'],
];

describe('FEEL TCK / 0094-feel-product-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: will return product for list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), 5832), 'decision001').toBe(true);
  });
  it('002: will return null when empty list', () => {
    const ctx = run({});
    expect(n(ctx.decision002)).toBeNull();
  });
  it('003: will return null when no params', () => {
    const ctx = run({});
    expect(n(ctx.decision003)).toBeNull();
  });
  it('003_a: will error when null param', () => {
    const ctx = run({});
    expect(n(ctx.decision003_a)).toBeNull();
  });
  it('004: will error when list item not a number', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: will error when list item not a number', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: will multiple decimals', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), 18.75), 'decision006').toBe(true);
  });
  it('007: will multiply varargs number list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007), 24), 'decision007').toBe(true);
  });
  it('008: product of single item is itself', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008), 6), 'decision008').toBe(true);
  });
  it('008_a: product of single item list is value of first item', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008_a), 6), 'decision008_a').toBe(true);
  });
  it('011: will return product for named params', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011), 5832), 'decision011').toBe(true);
  });
  it('012: will error when null named param', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('013: will error when wrongly named param', () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
});
