// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { parseDuration } from '../../../src/temporal/duration.js';
import { parseDate, parseDateTime, parseTime } from '../../../src/temporal/index.js';
import { aeq, type Ctx, n } from '../utils.js';

const d = parseDate,
  _t = parseTime,
  dt = parseDateTime,
  _dur = parseDuration;

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['date_001', 'week of year(@"2019-09-17")'],
  ['date_002', 'week of year(@"2003-12-29")'],
  ['date_003', 'week of year(@"2003-12-31")'],
  ['date_004', 'week of year(@"2004-01-01")'],
  ['date_005', 'week of year(@"2010-01-01")'],
  ['date_006', 'week of year(date_input_001)'],
  ['date_007', 'week of year(date: @"2019-09-17")'],
  ['datetime_001', 'week of year(@"1970-01-01T10:10:10")'],
  ['datetime_004', 'week of year(date_input_001)'],
  ['datetime_005', 'week of year(date: @"2019-09-17T10:10:10")'],
  ['null_001', 'week of year(null)'],
  ['null_002', 'week of year()'],
  ['null_003', 'week of year("foo")'],
  ['null_004', 'week of year(date: null)'],
  ['null_005', 'week of year(date: "foo")'],
  ['null_006', 'week of year(value: @"1970-01-01")'],
  ['null_007', 'week of year(date_input_001)'],
  ['null_008', 'week of year(@"1970-01-01", @"1970-01-01")'],
];

describe('FEEL TCK / 0098-feel-week-of-year-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('date_001: date: during year 2019-09-17', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_001), 38), 'date_001').toBe(true);
  });
  it('date_002: date: @"2003-12-29"', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_002), 1), 'date_002').toBe(true);
  });
  it('date_003: date: @"2003-12-31"', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_003), 1), 'date_003').toBe(true);
  });
  it('date_004: date: @"2004-01-01"', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_004), 1), 'date_004').toBe(true);
  });
  it('date_005: date: @"2010-01-01"', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_005), 53), 'date_005').toBe(true);
  });
  it('date_006: date: unknown type at compile time with valid date as runtime input', () => {
    const ctx = run({ date_input_001: d('1970-01-01') });
    expect(aeq(n(ctx.date_006), 1), 'date_006').toBe(true);
  });
  it('date_007: date: will accept date as named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_007), 38), 'date_007').toBe(true);
  });
  it('datetime_001: datetime: first day of year', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_001), 1), 'datetime_001').toBe(true);
  });
  it('datetime_004: datetime: unknown type at compile time with valid datetime as runtime input', () => {
    const ctx = run({ date_input_001: dt('1970-01-01T10:10:10') });
    expect(aeq(n(ctx.datetime_004), 1), 'datetime_004').toBe(true);
  });
  it('datetime_005: datetime: will accept date time as named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_005), 38), 'datetime_005').toBe(true);
  });
  it('null_001: null param gives null result', () => {
    const ctx = run({});
    expect(n(ctx.null_001)).toBeNull();
  });
  it('null_002: no param gives null result', () => {
    const ctx = run({});
    expect(n(ctx.null_002)).toBeNull();
  });
  it('null_003: invalid param type gives null result', () => {
    const ctx = run({});
    expect(n(ctx.null_003)).toBeNull();
  });
  it('null_004: null value named param gives null result', () => {
    const ctx = run({});
    expect(n(ctx.null_004)).toBeNull();
  });
  it('null_005: invalid type as named param gives null result', () => {
    const ctx = run({});
    expect(n(ctx.null_005)).toBeNull();
  });
  it('null_006: invalidly named param gives null result', () => {
    const ctx = run({});
    expect(n(ctx.null_006)).toBeNull();
  });
  it('null_007: unknown type at compile time with invalid type as runtime input', () => {
    const ctx = run({ date_input_001: 'foo' });
    expect(n(ctx.null_007)).toBeNull();
  });
  it('null_008: too many params gives null result', () => {
    const ctx = run({});
    expect(n(ctx.null_008)).toBeNull();
  });
});
