// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision_001', '-10'],
  ['decision_002', '--10'],
  ['decision_003', '-@"P1D"'],
  ['decision_003_a', '-@"-P1D"'],
  ['decision_004', '-@"P1Y"'],
  ['decision_004_a', '-@"-P1Y"'],
  ['decision_005', '-@"2021-01-01"'],
  ['decision_006', '-@"2021-01-01T10:10:10"'],
  ['decision_007', '-@"10:10:10"'],
  ['decision_008', '-{a: 1}'],
  ['decision_009', '-"10"'],
  ['decision_010', '-[10]'],
  ['decision_011', '-[1..5]'],
  ['decision_012', '-(function(a) a)(10)'],
];

describe('FEEL TCK / 0099-arithmetic-negation', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('decision_001: negate number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_001), -10), 'decision_001').toBe(true);
  });
  it('decision_002: negate negative number', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_002), 10), 'decision_002').toBe(true);
  });
  it('decision_003: negate days and time duration', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_003), '-P1D'), 'decision_003').toBe(true);
  });
  it('decision_003_a: negate a negative days and time duration', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_003_a), 'P1D'), 'decision_003_a').toBe(true);
  });
  it('decision_004: negate years and months duration', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_004), '-P1Y'), 'decision_004').toBe(true);
  });
  it('decision_004_a: negate a negative years and months duration', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_004_a), 'P1Y'), 'decision_004_a').toBe(true);
  });
  it('decision_005: negate date gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_005)).toBeNull();
  });
  it('decision_006: negate datetime gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_006)).toBeNull();
  });
  it('decision_007: negate time gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_007)).toBeNull();
  });
  it('decision_008: negate context gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_008)).toBeNull();
  });
  it('decision_009: negate string gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_009)).toBeNull();
  });
  it('decision_010: negate singleton list gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_010)).toBeNull();
  });
  it('decision_011: negate range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision_011)).toBeNull();
  });
  it('decision_012: negate expression result', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision_012), -10), 'decision_012').toBe(true);
  });
});
