// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['number_001', 'is(1, 1)'],
  ['number_002', 'is(1, 2)'],
  ['boolean_001', 'is(true, true)'],
  ['boolean_002', 'is(true, false)'],
  ['string_001', 'is("foo", "foo")'],
  ['string_002', 'is("foo", "bar")'],
  ['date_001', 'is(@"2012-12-25", @"2012-12-25")'],
  ['date_002', 'is(@"2011-12-25", @"2012-12-25")'],
  ['date_003', 'is(@"2012-12-25", @"2012-11-25")'],
  ['date_004', 'is(@"2012-12-25", @"2012-12-26")'],
  ['date_005', 'is(@"2012-12-25", @"2012-12-25T00:00:00Z")'],
  ['time_001', 'is(@"23:00:50", @"23:00:50")'],
  ['time_002', 'is(@"23:00:50+11:00", @"23:00:50+11:00")'],
  ['time_003', 'is(@"23:00:50@Australia/Melbourne", @"23:00:50@Australia/Melbourne")'],
  ['time_004', 'is(@"23:00:50Z", @"23:00:50+00:00")'],
  ['time_005', 'is(@"23:00:50", @"23:00:50Z")'],
  ['time_006', 'is(@"23:00:50@Australia/Melbourne", @"23:00:50+10:00")'],
  ['time_007', 'is(@"23:00:50@Etc/GMT", @"23:00:50Z")'],
  ['time_008', 'is(@"22:00:50", @"23:00:50")'],
  ['time_009', 'is(@"23:01:50", @"23:00:50")'],
  ['time_010', 'is(@"23:00:51", @"23:00:50")'],
  ['time_011', 'is(@"23:00:50+10:00", @"23:00:50+11:00")'],
  ['time_012', 'is(@"23:00:50@Australia/Melbourne", @"23:00:50@Australia/Sydney")'],
  ['time_013', 'is(@"20:00:50+00:00", @"21:00:50+01:00")'],
  ['datetime_001', 'is(@"2012-12-25T10:10:10", @"2012-12-25T10:10:10")'],
  ['datetime_002', 'is(@"2012-12-25T10:10:10+11:00", @"2012-12-25T10:10:10+11:00")'],
  [
    'datetime_003',
    'is(@"2012-12-25T10:10:10@Australia/Melbourne", @"2012-12-25T10:10:10@Australia/Melbourne")',
  ],
  ['datetime_004', 'is(@"2002-04-02T12:00:00-01:00", @"2002-04-02T17:00:00+04:00")'],
  ['datetime_005', 'is(@"2002-04-02T12:00:00-05:00", @"2002-04-02T23:00:00+06:00")'],
  ['datetime_006', 'is(@"2002-04-02T23:00:00-04:00", @"2002-04-03T02:00:00-01:00")'],
  ['datetime_007', 'is(@"2002-04-02T23:00:00", @"2001-04-02T23:00:00")'],
  ['datetime_008', 'is(@"2002-04-02T23:00:00", @"2002-05-02T23:00:00")'],
  ['datetime_009', 'is(@"2002-04-02T23:00:00", @"2002-04-03T23:00:00")'],
  ['datetime_010', 'is(@"2002-04-02T23:00:00", @"2002-04-02T22:00:00")'],
  ['datetime_011', 'is(@"2002-04-02T23:00:00", @"2002-04-02T23:01:00")'],
  ['datetime_012', 'is(@"2002-04-02T23:00:00", @"2002-04-02T23:00:01")'],
  ['datetime_013', 'is(@"2002-04-02T23:00:00+10:00", @"2002-04-02T23:00:00+11:00")'],
  [
    'datetime_014',
    'is(@"2002-04-02T23:00:00@Australia/Melbourne", @"2002-04-02T23:00:00@Australia/Sydney")',
  ],
  ['datetime_015', 'is(@"23:00:50Z", @"23:00:50+00:00")'],
  ['datetime_016', 'is(@"2021-04-02T23:00:00@Australia/Melbourne", @"2021-04-02T23:00:00+11:00")'],
  ['datetime_017', 'is(@"2021-10-02T23:00:00@Australia/Melbourne", @"2021-10-02T23:00:00+10:00")'],
  ['dt_duration_001', 'is(@"P1D", @"P1D")'],
  ['dt_duration_002', 'is(@"P1D", @"PT24H")'],
  ['ym_duration_001', 'is(@"P1Y", @"P1Y")'],
  ['ym_duration_002', 'is(@"P1Y", @"P12M")'],
  ['zero_duration_001', 'is(@"P0Y", @"P0D")'],
  ['named_params_001', 'is(value1: @"2021-02-13" , value2: @"2021-02-13")'],
  ['named_params_002', 'is(value1: @"2021-02-13")'],
  ['named_params_003', 'is(value2: @"2021-02-13")'],
  ['named_params_004', 'is(value1: @"2021-02-13" , value2: @"2021-02-13", value3: @"2020-01-01")'],
];

describe('FEEL TCK / 0103-feel-is-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('number_001: number: is equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_001), true), 'number_001').toBe(true);
  });
  it('number_002: number: is not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.number_002), false), 'number_002').toBe(true);
  });
  it('boolean_001: boolean: is equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_001), true), 'boolean_001').toBe(true);
  });
  it('boolean_002: boolean: is not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.boolean_002), false), 'boolean_002').toBe(true);
  });
  it('string_001: string: is equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_001), true), 'string_001').toBe(true);
  });
  it('string_002: string: is not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.string_002), false), 'string_002').toBe(true);
  });
  it('date_001: date: is equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_001), true), 'date_001').toBe(true);
  });
  it('date_002: date: is not equal when year differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_002), false), 'date_002').toBe(true);
  });
  it('date_003: date: is not equal when months differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_003), false), 'date_003').toBe(true);
  });
  it('date_004: date: is not equal when days differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_004), false), 'date_004').toBe(true);
  });
  it('date_005: date: is not equal to UTC zero time of same date', () => {
    const ctx = run({});
    expect(aeq(n(ctx.date_005), false), 'date_005').toBe(true);
  });
  it('time_001: time: is equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_001), true), 'time_001').toBe(true);
  });
  it('time_002: time: is equal with same offset', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_002), true), 'time_002').toBe(true);
  });
  it('time_003: time: is equal with same timezone', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_003), true), 'time_003').toBe(true);
  });
  it('time_004: time: is equal - UTC zone and UTC offset', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_004), true), 'time_004').toBe(true);
  });
  it('time_005: time: is not equal - no zone time vs UTC zone time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_005), false), 'time_005').toBe(true);
  });
  it('time_006: time: is not equal - @ zone time with same offset zone time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_006), false), 'time_006').toBe(true);
  });
  it('time_007: time: is not equal - @ GMT vs zero offset zone time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_007), false), 'time_007').toBe(true);
  });
  it('time_008: time: is not equal when hour differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_008), false), 'time_008').toBe(true);
  });
  it('time_009: time: is not equal when minute differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_009), false), 'time_009').toBe(true);
  });
  it('time_010: time: is not equal when second differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_010), false), 'time_010').toBe(true);
  });
  it('time_011: time: is not equal when offset differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_011), false), 'time_011').toBe(true);
  });
  it('time_012: time: is not equal when zone differs but offset is same', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_012), false), 'time_012').toBe(true);
  });
  it('time_013: time: is not equal when equivalent time in different zones', () => {
    const ctx = run({});
    expect(aeq(n(ctx.time_013), false), 'time_013').toBe(true);
  });
  it('datetime_001: datetime: is equal with same date and time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_001), true), 'datetime_001').toBe(true);
  });
  it('datetime_002: datetime: is equal with same date and time and offset', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_002), true), 'datetime_002').toBe(true);
  });
  it('datetime_003: datetime: is equal with same date and time and timezone', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_003), true), 'datetime_003').toBe(true);
  });
  it('datetime_004: datetime: not equals despite being equal points in time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_004), false), 'datetime_004').toBe(true);
  });
  it('datetime_005: datetime: not equals despite being equal points in time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_005), false), 'datetime_005').toBe(true);
  });
  it('datetime_006: datetime: not equals despite being equal points in time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_006), false), 'datetime_006').toBe(true);
  });
  it('datetime_007: datetime: not equals when year differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_007), false), 'datetime_007').toBe(true);
  });
  it('datetime_008: datetime: not equals when month differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_008), false), 'datetime_008').toBe(true);
  });
  it('datetime_009: datetime: not equals when day differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_009), false), 'datetime_009').toBe(true);
  });
  it('datetime_010: datetime: not equals when hour differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_010), false), 'datetime_010').toBe(true);
  });
  it('datetime_011: datetime: not equals when minute differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_011), false), 'datetime_011').toBe(true);
  });
  it('datetime_012: datetime: not equals when seconds differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_012), false), 'datetime_012').toBe(true);
  });
  it('datetime_013: datetime: not equals when offset differs', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_013), false), 'datetime_013').toBe(true);
  });
  it('datetime_014: datetime: not equals when region differs even though offset is same', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_014), false), 'datetime_014').toBe(true);
  });
  it('datetime_015: datetime: is equal - UTC zone vs UTC offset', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_015), true), 'datetime_015').toBe(true);
  });
  it('datetime_016: datetime: is not equal - zone vs offset - DST', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_016), false), 'datetime_016').toBe(true);
  });
  it('datetime_017: datetime: is not equal - zone vs offset - outside DST', () => {
    const ctx = run({});
    expect(aeq(n(ctx.datetime_017), false), 'datetime_017').toBe(true);
  });
  it('dt_duration_001: days and time duration: same stuff is equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_001), true), 'dt_duration_001').toBe(true);
  });
  it('dt_duration_002: days and time duration: same duration in different units is equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.dt_duration_002), true), 'dt_duration_002').toBe(true);
  });
  it('ym_duration_001: years and months duration: not a permitted type', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_001), true), 'ym_duration_001').toBe(true);
  });
  it('ym_duration_002: years and months duration: same duration in different units is equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.ym_duration_002), true), 'ym_duration_002').toBe(true);
  });
  it('zero_duration_001: zero durations are not equal', () => {
    const ctx = run({});
    expect(aeq(n(ctx.zero_duration_001), false), 'zero_duration_001').toBe(true);
  });
  it('named_params_001: correct names params okay', () => {
    const ctx = run({});
    expect(aeq(n(ctx.named_params_001), true), 'named_params_001').toBe(true);
  });
  it('named_params_002: value1 param is nullable', () => {
    const ctx = run({});
    expect(aeq(n(ctx.named_params_002), false), 'named_params_002').toBe(true);
  });
  it('named_params_003: value2 param is nullable', () => {
    const ctx = run({});
    expect(aeq(n(ctx.named_params_003), false), 'named_params_003').toBe(true);
  });
  it('named_params_004: will return null when unknown named params', () => {
    const ctx = run({});
    expect(n(ctx.named_params_004)).toBeNull();
  });
});
