// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-decimal-function_001_af177e63fc', 'decimal(1/3, 2)'],
  ['feel-decimal-function_002_f4ed9cd487', 'decimal(1/3, 2.5)'],
  ['feel-decimal-function_003_2d50ec7ffc', 'decimal(1.5, 0)'],
  ['feel-decimal-function_004_bb6f445d2c', 'decimal(2.5, 0)'],
  ['feel-decimal-function_005_55d33eadf6', 'decimal(0, 0)'],
  ['feel-decimal-function_006_d9661e1d45', 'decimal(0.0, 1)'],
  ['feel-decimal-function_007_49f7a22058', 'decimal(0.515, 2)'],
  ['feel-decimal-function_008_73e4f1c8b9', 'decimal(65.123456, 6)'],
  ['feel-decimal-function_009_398b94286e', 'decimal(n:15/7,scale:3)'],
  ['feel-decimal-function_010_4b46e59c8b', 'decimal(n:15/78*2,scale:3)'],
];

describe('FEEL TCK / 1100-feel-decimal-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_af177e63fc', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_001_af177e63fc']), 0.33),
      'feel-decimal-function_001_af177e63fc',
    ).toBe(true);
  });
  it('002_f4ed9cd487', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_002_f4ed9cd487']), 0.33),
      'feel-decimal-function_002_f4ed9cd487',
    ).toBe(true);
  });
  it('003_2d50ec7ffc', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_003_2d50ec7ffc']), 2),
      'feel-decimal-function_003_2d50ec7ffc',
    ).toBe(true);
  });
  it('004_bb6f445d2c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_004_bb6f445d2c']), 2),
      'feel-decimal-function_004_bb6f445d2c',
    ).toBe(true);
  });
  it('005_55d33eadf6', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_005_55d33eadf6']), 0),
      'feel-decimal-function_005_55d33eadf6',
    ).toBe(true);
  });
  it('006_d9661e1d45', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_006_d9661e1d45']), 0),
      'feel-decimal-function_006_d9661e1d45',
    ).toBe(true);
  });
  it('007_49f7a22058', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_007_49f7a22058']), 0.52),
      'feel-decimal-function_007_49f7a22058',
    ).toBe(true);
  });
  it('008_73e4f1c8b9', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_008_73e4f1c8b9']), 65.123456),
      'feel-decimal-function_008_73e4f1c8b9',
    ).toBe(true);
  });
  it('009_398b94286e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_009_398b94286e']), 2.143),
      'feel-decimal-function_009_398b94286e',
    ).toBe(true);
  });
  it('010_4b46e59c8b', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-decimal-function_010_4b46e59c8b']), 0.385),
      'feel-decimal-function_010_4b46e59c8b',
    ).toBe(true);
  });
});
