// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'ceiling(1.5)'],
  ['decision002', 'ceiling(-1.5)'],
  ['decision003', 'ceiling(-0.3333)'],
  ['decision004', 'ceiling(1.56, 1)'],
  ['decision005', 'ceiling(-1.56, 1)'],
  ['decision006', 'ceiling(null, 1)'],
  ['decision007', 'ceiling(n:null, scale:1)'],
  ['decision008', 'ceiling(1.56, null)'],
  ['decision009', 'ceiling(n:1.56, scale:null)'],
  ['decision010', 'ceiling()'],
  ['decision011', 'ceiling(1.5, 1, 2)'],
  ['decision012', 'ceiling(n:1.5, scale:1, stuff:2)'],
  ['decision013', 'ceiling(n:1.5, scal:1)'],
  ['decision014', 'ceiling("1.5")'],
  ['decision015', 'ceiling(1.5, "1")'],
  ['decision016', 'ceiling(n:"1.5")'],
  ['decision017', 'ceiling(n:1.5, scale:"1")'],
];

describe('FEEL TCK / 1102-feel-ceiling-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Will round up positive number to nearest integer when no scale', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), 2), 'decision001').toBe(true);
  });
  it('002: Will round up negative number to nearest integer when no scale', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), -1), 'decision002').toBe(true);
  });
  it('003: Will round up negative number to nearest integer when no scale', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), 0), 'decision003').toBe(true);
  });
  it('004: Will round up positive decimal to given scale', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), 1.6), 'decision004').toBe(true);
  });
  it('005: Will round up negative decimal to given scale', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005), -1.5), 'decision005').toBe(true);
  });
  it("006: Will give null when 'n' is null", () => {
    const ctx = run({});
    expect(n(ctx.decision006)).toBeNull();
  });
  it("007: Will give null when named param 'n' is null", () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it("008: Will give null when 'scale' is null", () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it("009: Will give null when named param 'scale' is null", () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it('010: No params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision010)).toBeNull();
  });
  it('011: Too many params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision011)).toBeNull();
  });
  it('012: Additional unknown named param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('013: Unknown named param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
  it("014: Invalid type for 'n' gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision014)).toBeNull();
  });
  it("015: Invalid type for named param 'n' gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision015)).toBeNull();
  });
  it("016: Invalid type for 'scale' gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision016)).toBeNull();
  });
  it("017: Invalid type for named param 'scale' gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision017)).toBeNull();
  });
});
