// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-substring-function_001_53051b5628', 'substring("f",1)'],
  ['feel-substring-function_002_03d12b93f0', 'substring("f",1,1)'],
  ['feel-substring-function_003_6d06b1d2ec', 'substring("foobar",6)'],
  ['feel-substring-function_004_938a24e7af', 'substring("foobar",1,6)'],
  ['feel-substring-function_005_21fcca286c', 'substring("foobar",3)'],
  ['feel-substring-function_006_253e533bc6', 'substring("foobar",3,3)'],
  ['feel-substring-function_007_3e021f33a8', 'substring("foobar",-2,1)'],
  ['feel-substring-function_008_ddeffdc93e', 'substring("foob r",-2,1)'],
  ['feel-substring-function_009_b52405c384', 'substring("foobar",-6,6)'],
  ['feel-substring-function_010_fbf9a89fde', 'substring("foobar",3,3.8)'],
  ['feel-substring-function_011_a559ce6410', 'substring(string:"foobar",start position :3)'],
];

describe('FEEL TCK / 1103-feel-substring-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_53051b5628', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_001_53051b5628']), 'f'),
      'feel-substring-function_001_53051b5628',
    ).toBe(true);
  });
  it('002_03d12b93f0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_002_03d12b93f0']), 'f'),
      'feel-substring-function_002_03d12b93f0',
    ).toBe(true);
  });
  it('003_6d06b1d2ec', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_003_6d06b1d2ec']), 'r'),
      'feel-substring-function_003_6d06b1d2ec',
    ).toBe(true);
  });
  it('004_938a24e7af', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_004_938a24e7af']), 'foobar'),
      'feel-substring-function_004_938a24e7af',
    ).toBe(true);
  });
  it('005_21fcca286c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_005_21fcca286c']), 'obar'),
      'feel-substring-function_005_21fcca286c',
    ).toBe(true);
  });
  it('006_253e533bc6', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_006_253e533bc6']), 'oba'),
      'feel-substring-function_006_253e533bc6',
    ).toBe(true);
  });
  it('007_3e021f33a8', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_007_3e021f33a8']), 'a'),
      'feel-substring-function_007_3e021f33a8',
    ).toBe(true);
  });
  it('008_ddeffdc93e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_008_ddeffdc93e']), ' '),
      'feel-substring-function_008_ddeffdc93e',
    ).toBe(true);
  });
  it('009_b52405c384', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_009_b52405c384']), 'foobar'),
      'feel-substring-function_009_b52405c384',
    ).toBe(true);
  });
  it('010_fbf9a89fde', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_010_fbf9a89fde']), 'oba'),
      'feel-substring-function_010_fbf9a89fde',
    ).toBe(true);
  });
  it('011_a559ce6410', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-function_011_a559ce6410']), 'obar'),
      'feel-substring-function_011_a559ce6410',
    ).toBe(true);
  });
});
