// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-string-length-function_001_1afe6930d1', 'string length("")'],
  ['feel-string-length-function_002_249c23050d', 'string length("a")'],
  ['feel-string-length-function_003_e1df507dee', 'string length("abc")'],
  ['feel-string-length-function_004_f4c02fac3d', 'string length(string:"xyz123")'],
  ['feel-string-length-function_005_ca834dabac', 'string length(string:"aaaaa dddd")'],
  ['feel-string-length-function_006_6c4930a0eb', 'string length(string:"aaaaa dddd ")'],
];

describe('FEEL TCK / 1104-feel-string-length-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_1afe6930d1', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-string-length-function_001_1afe6930d1']), 0),
      'feel-string-length-function_001_1afe6930d1',
    ).toBe(true);
  });
  it('002_249c23050d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-string-length-function_002_249c23050d']), 1),
      'feel-string-length-function_002_249c23050d',
    ).toBe(true);
  });
  it('003_e1df507dee', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-string-length-function_003_e1df507dee']), 3),
      'feel-string-length-function_003_e1df507dee',
    ).toBe(true);
  });
  it('004_f4c02fac3d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-string-length-function_004_f4c02fac3d']), 6),
      'feel-string-length-function_004_f4c02fac3d',
    ).toBe(true);
  });
  it('005_ca834dabac', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-string-length-function_005_ca834dabac']), 10),
      'feel-string-length-function_005_ca834dabac',
    ).toBe(true);
  });
  it('006_6c4930a0eb', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-string-length-function_006_6c4930a0eb']), 11),
      'feel-string-length-function_006_6c4930a0eb',
    ).toBe(true);
  });
});
