// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-upper-case-function_001_2395aaad55', 'upper case("a")'],
  ['feel-upper-case-function_002_991789dded', 'upper case("abc")'],
  ['feel-upper-case-function_003_d8306d8d00', 'upper case("")'],
  ['feel-upper-case-function_004_310caf7262', 'upper case("1")'],
  ['feel-upper-case-function_005_b316d773ac', 'upper case("?@{")'],
  ['feel-upper-case-function_006_d9bd3c14bc', 'upper case(string:"AbDcF")'],
  ['feel-upper-case-function_007_31fc6c1967', 'upper case(string:"xyZ ")'],
  ['feel-upper-case-function_008_26e369a9d9', 'upper case(string:"123ABC")'],
];

describe('FEEL TCK / 1105-feel-upper-case-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_2395aaad55', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-upper-case-function_001_2395aaad55']), 'A'),
      'feel-upper-case-function_001_2395aaad55',
    ).toBe(true);
  });
  it('002_991789dded', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-upper-case-function_002_991789dded']), 'ABC'),
      'feel-upper-case-function_002_991789dded',
    ).toBe(true);
  });
  it('003_d8306d8d00', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-upper-case-function_003_d8306d8d00']), ''),
      'feel-upper-case-function_003_d8306d8d00',
    ).toBe(true);
  });
  it('004_310caf7262', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-upper-case-function_004_310caf7262']), '1'),
      'feel-upper-case-function_004_310caf7262',
    ).toBe(true);
  });
  it('005_b316d773ac', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-upper-case-function_005_b316d773ac']), '?@{'),
      'feel-upper-case-function_005_b316d773ac',
    ).toBe(true);
  });
  it('006_d9bd3c14bc', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-upper-case-function_006_d9bd3c14bc']), 'ABDCF'),
      'feel-upper-case-function_006_d9bd3c14bc',
    ).toBe(true);
  });
  it('007_31fc6c1967', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-upper-case-function_007_31fc6c1967']), 'XYZ '),
      'feel-upper-case-function_007_31fc6c1967',
    ).toBe(true);
  });
  it('008_26e369a9d9', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-upper-case-function_008_26e369a9d9']), '123ABC'),
      'feel-upper-case-function_008_26e369a9d9',
    ).toBe(true);
  });
});
