// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-substring-before-function_001_2e948ccdc7', 'substring before("foobar","bar")'],
  ['feel-substring-before-function_002_f4de663db7', 'substring before("foobar","o")'],
  ['feel-substring-before-function_003_60bc15bade', 'substring before("foobar","x")'],
  ['feel-substring-before-function_004_6f93aa7654', 'substring before("","")'],
  ['feel-substring-before-function_005_c8e030633c', 'substring before("abc","")'],
  ['feel-substring-before-function_006_1c3d39811d', 'substring before("abc","a")'],
  ['feel-substring-before-function_007_ea4e4a38b0', 'substring before("abc","c")'],
  [
    'feel-substring-before-function_008_501b0a5990',
    'substring before(string:"foobar",match:"bar")',
  ],
  ['feel-substring-before-function_009_a79c5a4111', 'substring before(string:"foobar",match:"b")'],
];

describe('FEEL TCK / 1107-feel-substring-before-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_2e948ccdc7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_001_2e948ccdc7']), 'foo'),
      'feel-substring-before-function_001_2e948ccdc7',
    ).toBe(true);
  });
  it('002_f4de663db7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_002_f4de663db7']), 'f'),
      'feel-substring-before-function_002_f4de663db7',
    ).toBe(true);
  });
  it('003_60bc15bade', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_003_60bc15bade']), ''),
      'feel-substring-before-function_003_60bc15bade',
    ).toBe(true);
  });
  it('004_6f93aa7654', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_004_6f93aa7654']), ''),
      'feel-substring-before-function_004_6f93aa7654',
    ).toBe(true);
  });
  it('005_c8e030633c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_005_c8e030633c']), ''),
      'feel-substring-before-function_005_c8e030633c',
    ).toBe(true);
  });
  it('006_1c3d39811d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_006_1c3d39811d']), ''),
      'feel-substring-before-function_006_1c3d39811d',
    ).toBe(true);
  });
  it('007_ea4e4a38b0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_007_ea4e4a38b0']), 'ab'),
      'feel-substring-before-function_007_ea4e4a38b0',
    ).toBe(true);
  });
  it('008_501b0a5990', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_008_501b0a5990']), 'foo'),
      'feel-substring-before-function_008_501b0a5990',
    ).toBe(true);
  });
  it('009_a79c5a4111', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-before-function_009_a79c5a4111']), 'foo'),
      'feel-substring-before-function_009_a79c5a4111',
    ).toBe(true);
  });
});
