// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-substring-after-function_001_f532be66f2', 'substring after("foobar","ob")'],
  ['feel-substring-after-function_002_f20d66fc1e', 'substring after("foobar","o")'],
  ['feel-substring-after-function_003_367612fc8b', 'substring after("foobar","x")'],
  ['feel-substring-after-function_004_e448ee2dad', 'substring after("","")'],
  ['feel-substring-after-function_005_429efdafd0', 'substring after("","a")'],
  ['feel-substring-after-function_006_bf89d6b618', 'substring after("abc","")'],
  ['feel-substring-after-function_007_529baaeb0b', 'substring after("abc","c")'],
  ['feel-substring-after-function_008_1e611924ea', 'substring after("abc","a")'],
  ['feel-substring-after-function_009_712fe2842f', 'substring after(string:"foobar",match:"ob")'],
  ['feel-substring-after-function_010_40e159d07a', 'substring after(string:"foobar",match:"b")'],
];

describe('FEEL TCK / 1108-feel-substring-after-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_f532be66f2', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_001_f532be66f2']), 'ar'),
      'feel-substring-after-function_001_f532be66f2',
    ).toBe(true);
  });
  it('002_f20d66fc1e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_002_f20d66fc1e']), 'obar'),
      'feel-substring-after-function_002_f20d66fc1e',
    ).toBe(true);
  });
  it('003_367612fc8b', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_003_367612fc8b']), ''),
      'feel-substring-after-function_003_367612fc8b',
    ).toBe(true);
  });
  it('004_e448ee2dad', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_004_e448ee2dad']), ''),
      'feel-substring-after-function_004_e448ee2dad',
    ).toBe(true);
  });
  it('005_429efdafd0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_005_429efdafd0']), ''),
      'feel-substring-after-function_005_429efdafd0',
    ).toBe(true);
  });
  it('006_bf89d6b618', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_006_bf89d6b618']), 'abc'),
      'feel-substring-after-function_006_bf89d6b618',
    ).toBe(true);
  });
  it('007_529baaeb0b', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_007_529baaeb0b']), ''),
      'feel-substring-after-function_007_529baaeb0b',
    ).toBe(true);
  });
  it('008_1e611924ea', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_008_1e611924ea']), 'bc'),
      'feel-substring-after-function_008_1e611924ea',
    ).toBe(true);
  });
  it('009_712fe2842f', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_009_712fe2842f']), 'ar'),
      'feel-substring-after-function_009_712fe2842f',
    ).toBe(true);
  });
  it('010_40e159d07a', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-substring-after-function_010_40e159d07a']), 'ar'),
      'feel-substring-after-function_010_40e159d07a',
    ).toBe(true);
  });
});
