// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-contains-function_ErrorCase_001_2a4d7448c6', 'contains(null,null)'],
  ['feel-contains-function_ErrorCase_002_d2a1831b5c', 'contains(null,"bar")'],
  ['feel-contains-function_ErrorCase_003_df56e0a1ad', 'contains("bar",null)'],
  ['feel-contains-function_004_805503b274', 'contains("foobar","bar")'],
  ['feel-contains-function_005_5c1269db16', 'contains("foobar","o")'],
  ['feel-contains-function_006_babdaf4f36', 'contains("abc","")'],
  ['feel-contains-function_007_d24a599180', 'contains("","ab")'],
  ['feel-contains-function_008_cf1311586a', 'contains("","")'],
  ['feel-contains-function_009_c4b50ad623', 'contains(string:"foobar",match:"bar")'],
  ['feel-contains-function_010_9ae03e0e59', 'contains(string:"foobar",match:"b")'],
];

describe('FEEL TCK / 1110-feel-contains-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_2a4d7448c6', () => {
    const ctx = run({});
    expect(n(ctx['feel-contains-function_ErrorCase_001_2a4d7448c6'])).toBeNull();
  });
  it('002_d2a1831b5c', () => {
    const ctx = run({});
    expect(n(ctx['feel-contains-function_ErrorCase_002_d2a1831b5c'])).toBeNull();
  });
  it('003_df56e0a1ad', () => {
    const ctx = run({});
    expect(n(ctx['feel-contains-function_ErrorCase_003_df56e0a1ad'])).toBeNull();
  });
  it('004_805503b274', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-contains-function_004_805503b274']), true),
      'feel-contains-function_004_805503b274',
    ).toBe(true);
  });
  it('005_5c1269db16', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-contains-function_005_5c1269db16']), true),
      'feel-contains-function_005_5c1269db16',
    ).toBe(true);
  });
  it('006_babdaf4f36', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-contains-function_006_babdaf4f36']), true),
      'feel-contains-function_006_babdaf4f36',
    ).toBe(true);
  });
  it('007_d24a599180', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-contains-function_007_d24a599180']), false),
      'feel-contains-function_007_d24a599180',
    ).toBe(true);
  });
  it('008_cf1311586a', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-contains-function_008_cf1311586a']), true),
      'feel-contains-function_008_cf1311586a',
    ).toBe(true);
  });
  it('009_c4b50ad623', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-contains-function_009_c4b50ad623']), true),
      'feel-contains-function_009_c4b50ad623',
    ).toBe(true);
  });
  it('010_9ae03e0e59', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-contains-function_010_9ae03e0e59']), true),
      'feel-contains-function_010_9ae03e0e59',
    ).toBe(true);
  });
});
