// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['fn-null-input', 'matches(null, "pattern")'],
  ['fn-null-pattern', 'matches("input", null)'],
  ['fn-null-flags', 'matches("abracadabra", "bra", null)'],
  ['fn-matches2args-1', 'matches("This is a characte","This is a characte")'],
  ['fn-matchesErr-1', 'matches("abracadabra", "bra", "p")'],
  ['fn-matches-27', 'matches("\\nabcd\\ndefg\\n", "^$", "m")'],
  ['fn-matches-28', 'matches("abcd\\n\\ndefg\\n ", "^$", "m")'],
  ['fn-matches-45', 'matches("Mary\\u000DJones", "Mary.Jones")'],
  ['caselessmatch01', 'matches("abc", "ABC", "i")'],
  ['caselessmatch02', 'matches("abZ", "[A-Z]*", "i")'],
  ['caselessmatch03', 'matches("abZ", "[a-z]*", "i")'],
  ['caselessmatch07', 'matches("\\u212A", "k", "i")'],
  ['caselessmatch08', 'matches("x", "[A-Z-[OI]]", "i")'],
  ['caselessmatch09', 'matches("X", "[A-Z-[OI]]", "i")'],
  ['caselessmatch10', 'matches("O", "[A-Z-[OI]]", "i")'],
  ['caselessmatch11', 'matches("i", "[A-Z-[OI]]", "i")'],
  ['caselessmatch12', 'matches("Q", "[^Q]", "i")'],
  ['caselessmatch13', 'matches("q", "[^Q]", "i")'],
  ['K-MatchesFunc-1', 'matches("input", [])'],
  ['K-MatchesFunc-2', 'matches("input")'],
  ['K-MatchesFunc-3', 'matches("input", "pattern", [])'],
  ['K-MatchesFunc-4', 'matches("input", "pattern", "", [])'],
  ['K-MatchesFunc-5', 'matches("input", "pattern", " ")'],
  ['K-MatchesFunc-6', 'matches("input", "pattern", "X")'],
  ['K2-MatchesFunc-1', 'matches("hello world", "hello\\ sworld", "x")'],
  ['K2-MatchesFunc-2', 'matches("hello world", " hello[ ]world", "x")'],
  ['K2-MatchesFunc-3', 'matches("hello world", "hello[ ]world ", "x")'],
  ['K2-MatchesFunc-4', 'matches("hello world", "he ll o[ ]worl d", "x")'],
  ['K2-MatchesFunc-5', 'matches("hello world", "\\p{ IsBasicLatin}+", "x")'],
  ['K2-MatchesFunc-6', 'matches("hello world", "\\p{ I s B a s i c L a t i n }+", "x")'],
  ['K2-MatchesFunc-7', 'matches("hello world", "\\p{ IsBasicLatin}+")'],
  ['K2-MatchesFunc-8', 'matches("h", "(.)\\3")'],
  ['K2-MatchesFunc-9', 'matches("h", "(.)\\2")'],
  ['K2-MatchesFunc-10', 'matches("input", "\\3")'],
  ['K2-MatchesFunc-11', 'matches("abcd", "(asd)[\\1]")'],
  ['K2-MatchesFunc-12', 'matches("abcd", "(asd)[asd\\1]")'],
  ['K2-MatchesFunc-13', 'matches("abcd", "(asd)[asd\\0]")'],
  ['K2-MatchesFunc-14', 'matches("abcd", "1[asd\\0]")'],
  ['K2-MatchesFunc-15', '[matches("a", "a[^b]"), matches("a ", "a[^b]")]'],
  ['K2-MatchesFunc-16', 'matches("input", "[0-9-.]*/")'],
  ['K2-MatchesFunc-17', 'matches("aA", "(a)\\1", "i")'],
];

describe('FEEL TCK / 1111-feel-matches-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('fn-null-input: Evaluates "matches" function with null input', () => {
    const ctx = run({});
    expect(n(ctx['fn-null-input'])).toBeNull();
  });
  it('fn-null-pattern: Evaluates "matches" function with null pattern', () => {
    const ctx = run({});
    expect(n(ctx['fn-null-pattern'])).toBeNull();
  });
  it('fn-null-flags: Evaluates "matches" function with null flags', () => {
    const ctx = run({});
    expect(aeq(n(ctx['fn-null-flags']), true), 'fn-null-flags').toBe(true);
  });
  it('fn-matches2args-1: Evaluates The "matches" function with the arguments set as follows: $input = xs:string(lower bound)\n            $pattern = xs:string(lower bound)\n        ', () => {
    const ctx = run({});
    expect(aeq(n(ctx['fn-matches2args-1']), true), 'fn-matches2args-1').toBe(true);
  });
  it('fn-matchesErr-1: Invalid flag for third argument of matches.', () => {
    const ctx = run({});
    expect(n(ctx['fn-matchesErr-1'])).toBeNull();
  });
  it('fn-matches-27: Check for the correct behavior of ^ and $ in multi-line mode This test case was motivated by the\n            resolution of Bug Report 4543\n        ', () => {
    const ctx = run({});
    expect(aeq(n(ctx['fn-matches-27']), true), 'fn-matches-27').toBe(true);
  });
  it('fn-matches-28: Check for the correct behavior of ^ and $ in multi-line mode This test case was motivated by the\n            resolution of Bug Report 4543\n        ', () => {
    const ctx = run({});
    expect(aeq(n(ctx['fn-matches-28']), true), 'fn-matches-28').toBe(true);
  });
  it('fn-matches-45: "." does NOT match CR in default mode', () => {
    const ctx = run({});
    expect(aeq(n(ctx['fn-matches-45']), false), 'fn-matches-45').toBe(true);
  });
  it('caselessmatch01: Simple call of matches() with "i" flag', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch01), true), 'caselessmatch01').toBe(true);
  });
  it('caselessmatch02: Call of matches() with "i" flag and a character range', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch02), true), 'caselessmatch02').toBe(true);
  });
  it('caselessmatch03: Call of matches() with "i" flag and a character range', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch03), true), 'caselessmatch03').toBe(true);
  });
  it('caselessmatch07: Call of matches() with "i" flag and Kelvin sign Kelvin sign', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch07), true), 'caselessmatch07').toBe(true);
  });
  it('caselessmatch08: Call of matches() with "i" flag and range subtraction', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch08), true), 'caselessmatch08').toBe(true);
  });
  it('caselessmatch09: Call of matches() with "i" flag and range subtraction', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch09), true), 'caselessmatch09').toBe(true);
  });
  it('caselessmatch10: Call of matches() with "i" flag and range subtraction', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch10), false), 'caselessmatch10').toBe(true);
  });
  it('caselessmatch11: Call of matches() with "i" flag and range subtraction', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch11), false), 'caselessmatch11').toBe(true);
  });
  it('caselessmatch12: Call of matches() with "i" flag and negation', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch12), false), 'caselessmatch12').toBe(true);
  });
  it('caselessmatch13: Call of matches() with "i" flag and negation', () => {
    const ctx = run({});
    expect(aeq(n(ctx.caselessmatch13), false), 'caselessmatch13').toBe(true);
  });
  it("K-MatchesFunc-1: The pattern can't be the empty sequence.", () => {
    const ctx = run({});
    expect(n(ctx['K-MatchesFunc-1'])).toBeNull();
  });
  it('K-MatchesFunc-2: matches() takes at least two arguments, not one.', () => {
    const ctx = run({});
    expect(n(ctx['K-MatchesFunc-2'])).toBeNull();
  });
  it('K-MatchesFunc-3: The third argument cannot be the empty sequence.', () => {
    const ctx = run({});
    expect(n(ctx['K-MatchesFunc-3'])).toBeNull();
  });
  it('K-MatchesFunc-4: Only three arguments are accepted.', () => {
    const ctx = run({});
    expect(n(ctx['K-MatchesFunc-4'])).toBeNull();
  });
  it('K-MatchesFunc-5: The flags argument cannot contain whitespace.', () => {
    const ctx = run({});
    expect(n(ctx['K-MatchesFunc-5'])).toBeNull();
  });
  it("K-MatchesFunc-6: The flags argument cannot contain 'X'.", () => {
    const ctx = run({});
    expect(n(ctx['K-MatchesFunc-6'])).toBeNull();
  });
  it('K2-MatchesFunc-1: Whitespace in the regexp is collapsed.', () => {
    const ctx = run({});
    expect(aeq(n(ctx['K2-MatchesFunc-1']), true), 'K2-MatchesFunc-1').toBe(true);
  });
  it('K2-MatchesFunc-2: Whitespace(before) in the regexp is collapsed, but not inside a character class.', () => {
    const ctx = run({});
    expect(aeq(n(ctx['K2-MatchesFunc-2']), true), 'K2-MatchesFunc-2').toBe(true);
  });
  it('K2-MatchesFunc-3: Whitespace(after) in the regexp is collapsed, but not inside a character class.', () => {
    const ctx = run({});
    expect(aeq(n(ctx['K2-MatchesFunc-3']), true), 'K2-MatchesFunc-3').toBe(true);
  });
  it('K2-MatchesFunc-4: Whitespace(in the middle) in the regexp is collapsed, but not inside a character class.\n        ', () => {
    const ctx = run({});
    expect(aeq(n(ctx['K2-MatchesFunc-4']), true), 'K2-MatchesFunc-4').toBe(true);
  });
  it('K2-MatchesFunc-5: whitespace in the regexp is collapsed, and should therefore compile.', () => {
    const ctx = run({});
    expect(aeq(n(ctx['K2-MatchesFunc-5']), true), 'K2-MatchesFunc-5').toBe(true);
  });
  it('K2-MatchesFunc-6: whitespace in the regexp is collapsed completely, and should therefore compile and match.\n        ', () => {
    const ctx = run({});
    expect(aeq(n(ctx['K2-MatchesFunc-6']), true), 'K2-MatchesFunc-6').toBe(true);
  });
  it('K2-MatchesFunc-7: whitespace in the regexp is not collapsed, and should therefore not compile.', () => {
    const ctx = run({});
    expect(n(ctx['K2-MatchesFunc-7'])).toBeNull();
  });
  it('K2-MatchesFunc-8: Since no string is captured by the back-reference, the single character is matched.', () => {
    const ctx = run({});
    expect(n(ctx['K2-MatchesFunc-8'])).toBeNull();
  });
  it('K2-MatchesFunc-9: Since no string is captured by the back-reference, the single character is matched(#2).\n        ', () => {
    const ctx = run({});
    expect(n(ctx['K2-MatchesFunc-9'])).toBeNull();
  });
  it('K2-MatchesFunc-10: A non-matching backwards-reference matches the empty string.', () => {
    const ctx = run({});
    expect(n(ctx['K2-MatchesFunc-10'])).toBeNull();
  });
  it('K2-MatchesFunc-11: Use a back reference inside a character class.', () => {
    const ctx = run({});
    expect(n(ctx['K2-MatchesFunc-11'])).toBeNull();
  });
  it('K2-MatchesFunc-12: Use a back reference inside a character class(#2).', () => {
    const ctx = run({});
    expect(n(ctx['K2-MatchesFunc-12'])).toBeNull();
  });
  it('K2-MatchesFunc-13: Use a back reference inside a character class(#3).', () => {
    const ctx = run({});
    expect(n(ctx['K2-MatchesFunc-13'])).toBeNull();
  });
  it('K2-MatchesFunc-14: Use a back reference inside a character class(#3).', () => {
    const ctx = run({});
    expect(n(ctx['K2-MatchesFunc-14'])).toBeNull();
  });
  it('K2-MatchesFunc-15:  A negative character class never match a non-character. ', () => {
    const ctx = run({});
    expect(aeq(n(ctx['K2-MatchesFunc-15']), [false, true]), 'K2-MatchesFunc-15').toBe(true);
  });
  it('K2-MatchesFunc-17: Caseless match with back-reference.', () => {
    const ctx = run({});
    expect(aeq(n(ctx['K2-MatchesFunc-17']), true), 'K2-MatchesFunc-17').toBe(true);
  });
});
