// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-time-function_ErrorCase_001_bdf26fdc72', 'time(null)'],
  ['feel-time-function_ErrorCase_002_9d2e399b96', 'time(null,11,45,duration("P0D"))'],
  ['feel-time-function_ErrorCase_003_d1f0ea5bb9', 'time(12,null,45,duration("P0D"))'],
  ['feel-time-function_ErrorCase_004_57aea91d1c', 'time(12,0,null,duration("P0D"))'],
  ['feel-time-function_ErrorCase_005_32ea20b34f', 'time(null,null,45,duration("P0D"))'],
  ['feel-time-function_ErrorCase_006_e266498180', 'time(null,11,null,duration("P0D"))'],
  ['feel-time-function_ErrorCase_007_ee82c7bf12', 'time(null,11,45,null)'],
  ['feel-time-function_ErrorCase_008_08078c6c29', 'time(12,null,null,duration("P0D"))'],
  ['feel-time-function_ErrorCase_009_804c21ed52', 'time(12,11,null,null)'],
  ['feel-time-function_ErrorCase_010_cc773bb44b', 'time(12,null,null,null)'],
  ['feel-time-function_ErrorCase_011_ad5b3a26b5', 'time(null,0,null,null)'],
  ['feel-time-function_ErrorCase_012_3c2f416fc9', 'time(null,null,15,null)'],
  ['feel-time-function_ErrorCase_013_7f22c0bda8', 'time(null,null,null,duration("P0D"))'],
  ['feel-time-function_ErrorCase_014_0dc13176e8', 'time(null,null,null,null)'],
  ['feel-time-function_015_376d693a79', 'time(12,00,00,null)'],
  ['feel-time-function_ErrorCase_016_c3cccff405', 'time()'],
  ['feel-time-function_017_f3683885f5', 'time("01:02:03")'],
  ['feel-time-function_018_35f1f2cce8', 'time("00:00:00")'],
  ['feel-time-function_019_879be89d63', 'time("11:22:33.444")'],
  ['feel-time-function_020_72b421086e', 'time("11:22:33.123456789")'],
  ['feel-time-function_021_5c50fa1dff', 'time("23:59:00Z")'],
  ['feel-time-function_022_55e76d3595', 'time("11:00:00Z")'],
  ['feel-time-function_023_5cbbb85435', 'time("00:00:00Z")'],
  ['feel-time-function_024_5f7f735e8f', 'time("13:20:00+02:00")'],
  ['feel-time-function_025_139b25b795', 'time("13:20:00-05:00")'],
  ['feel-time-function_026_c5208af118', 'time("11:22:33-00:00")'],
  ['feel-time-function_027_45082fd26c', 'time("11:22:33+00:00")'],
  ['feel-time-function_028_eaea7a943c', 'string(time("00:01:00@Etc/UTC"))'],
  ['feel-time-function_029_f0d5c2c16a', 'string(time("00:01:00@Europe/Paris"))'],
  ['feel-time-function_030_390d4f4648', 'time(date and time("2017-08-10T10:20:00"))'],
  ['feel-time-function_031_4d086a3b59', 'time(date and time("2017-08-10T10:20:00+00:00"))'],
  ['feel-time-function_032_d9b0d7f931', 'time(date and time("2017-08-10T10:20:00-00:00"))'],
  ['feel-time-function_033_8420160da1', 'time(date and time("2017-08-10T10:20:00+01:00"))'],
  ['feel-time-function_034_13c312c376', 'time(date and time("2017-08-10T10:20:00-01:00"))'],
  ['feel-time-function_035_fbfce88ac4', 'time(date and time("2017-08-10T10:20:00Z"))'],
  [
    'feel-time-function_036_eb05fabc01',
    'string(time(date and time("2017-08-10T10:20:00@Europe/Paris")))',
  ],
  [
    'feel-time-function_037_eed195f693',
    'string(time(date and time("2017-09-04T11:20:00@Asia/Dhaka")))',
  ],
  ['feel-time-function_038_05b311131c', 'time(11, 59, 45, null)'],
  ['feel-time-function_039_5b65992f0d', 'time(11, 59, 45, duration("PT0H"))'],
  ['feel-time-function_040_6c9d17b491', 'time(11, 59, 45, duration("PT2H"))'],
  ['feel-time-function_041_29a448d57e', 'time(11, 59, 45, duration("-PT2H"))'],
  ['feel-time-function_042_00146f2977', 'time(11, 59, 00, duration("PT2H1M"))'],
  ['feel-time-function_043_2edfae8414', 'time(11, 59, 00, duration("-PT2H1M"))'],
  ['feel-time-function_044_3073ffd026', 'time(11, 59, 00, duration("PT2H1M0S"))'],
  ['feel-time-function_045_ad1339e858', 'time(11, 59, 00, duration("-PT2H1M0S"))'],
  ['feel-time-function_046_7b80221ec1', 'string(time(11, 59, 45, duration("PT2H45M55S")))'],
  ['feel-time-function_047_33cd7b9b15', 'string(time(11, 59, 45, duration("-PT2H45M55S")))'],
  ['feel-time-function_048_9bedd52886', 'time(11, 59, 45, duration("-PT0H"))'],
  [
    'feel-time-function_049_617d9e09d6',
    'time(date and time(date and time("2017-08-10T10:20:00"),time("23:59:01")))',
  ],
  [
    'feel-time-function_050_524d9a8146',
    'time(date and time(date and time("2017-08-10T10:20:00"),time("23:59:01.987654321")))',
  ],
  [
    'feel-time-function_051_a71d2a08f7',
    'time(date and time(date and time("2017-09-05T10:20:00"),time("09:15:30+02:00")))',
  ],
  [
    'feel-time-function_052_d825d58888',
    'time(date and time(date and time("2017-09-05T10:20:00"),time("09:15:30Z")))',
  ],
  ['feel-time-function_053_3d956966c0', 'time(date("2017-08-10"))'],
  ['feel-time-function_ErrorCase_054_fdc3094237', 'time(2017)'],
  ['feel-time-function_ErrorCase_055_9b47db6ea4', 'time([])'],
  ['feel-time-function_ErrorCase_056_a8e828d64d', 'time("")'],
  ['feel-time-function_ErrorCase_057_d039115cce', 'time("23:59:60")'],
  ['feel-time-function_ErrorCase_058_81dd4b1639', 'time("24:00:01")'],
  ['feel-time-function_ErrorCase_059_c7e1705fe1', 'time("24:01:00")'],
  ['feel-time-function_ErrorCase_060_0cf4734fae', 'time("25:00:00")'],
  ['feel-time-function_ErrorCase_061_da2717f085', 'time("00:60:00")'],
  ['feel-time-function_ErrorCase_062_6cd1313fa9', 'time("00:00:61")'],
  ['feel-time-function_ErrorCase_063_e85c40b474', 'time("7:00:00")'],
  ['feel-time-function_ErrorCase_064_df74038c67', 'time("07:1:00")'],
  ['feel-time-function_ErrorCase_065_79eaef6fee', 'time("07:01:2")'],
  ['feel-time-function_ErrorCase_066_5116e12fd3', 'time("13:20:00@xyz/abc")'],
  ['feel-time-function_ErrorCase_067_8285edad7b', 'time("13:20:00+19:00")'],
  ['feel-time-function_ErrorCase_068_ad528abb23', 'time("13:20:00-19:00")'],
  ['feel-time-function_ErrorCase_069_5096701e2e', 'time("13:20:00+5:00")'],
  ['feel-time-function_ErrorCase_070_8b2e39f570', 'time("13:20:00+5")'],
  ['feel-time-function_ErrorCase_071_cf9417648b', 'time("13:20:00+02:00@Europe/Paris")'],
  ['feel-time-function_ErrorCase_072_4c8c3835e4', 'time("7:20")'],
  ['feel-time-function_ErrorCase_073_a5fc245959', 'time("07:2")'],
  ['feel-time-function_ErrorCase_074_387d4411ea', 'time("11:30:00T")'],
  ['feel-time-function_ErrorCase_075_1606dda03d', 'time("2012T-12-2511:00:00Z")'],
  ['feel-time-function_ErrorCase_076_cb117ca612', 'time(24, 59, 45, null)'],
  ['feel-time-function_ErrorCase_077_a4daad060c', 'time(-24, 59, 45, null)'],
  ['feel-time-function_ErrorCase_078_c2fe73418b', 'time(23, 60, 45, null)'],
  ['feel-time-function_ErrorCase_079_d2d226c3cd', 'time(23, 59, 60, null)'],
  ['feel-time-function_080_2bbb8c86af', 'time(from:date and time("2012-12-24T23:59:00"))'],
  ['feel-time-function_081_69f4e0231e', 'time(from: "12:45:00")'],
  [
    'feel-time-function_082_36a78e5396',
    'time(hour:11, minute:59, second:0, offset: duration("PT2H1M0S"))',
  ],
  [
    'feel-time-function_083_6b608254c7',
    'time(hour:11, minute:59, second:0, offset: duration("-PT2H"))',
  ],
];

describe('FEEL TCK / 1116-feel-time-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_bdf26fdc72', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_001_bdf26fdc72'])).toBeNull();
  });
  it('002_9d2e399b96', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_002_9d2e399b96'])).toBeNull();
  });
  it('003_d1f0ea5bb9', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_003_d1f0ea5bb9'])).toBeNull();
  });
  it('004_57aea91d1c', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_004_57aea91d1c'])).toBeNull();
  });
  it('005_32ea20b34f', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_005_32ea20b34f'])).toBeNull();
  });
  it('006_e266498180', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_006_e266498180'])).toBeNull();
  });
  it('007_ee82c7bf12', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_007_ee82c7bf12'])).toBeNull();
  });
  it('008_08078c6c29', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_008_08078c6c29'])).toBeNull();
  });
  it('009_804c21ed52', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_009_804c21ed52'])).toBeNull();
  });
  it('010_cc773bb44b', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_010_cc773bb44b'])).toBeNull();
  });
  it('011_ad5b3a26b5', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_011_ad5b3a26b5'])).toBeNull();
  });
  it('012_3c2f416fc9', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_012_3c2f416fc9'])).toBeNull();
  });
  it('013_7f22c0bda8', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_013_7f22c0bda8'])).toBeNull();
  });
  it('014_0dc13176e8', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_014_0dc13176e8'])).toBeNull();
  });
  it('015_376d693a79', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_015_376d693a79']), '12:00:00'),
      'feel-time-function_015_376d693a79',
    ).toBe(true);
  });
  it('016_c3cccff405', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_016_c3cccff405'])).toBeNull();
  });
  it('017_f3683885f5', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_017_f3683885f5']), '01:02:03'),
      'feel-time-function_017_f3683885f5',
    ).toBe(true);
  });
  it('018_35f1f2cce8', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_018_35f1f2cce8']), '00:00:00'),
      'feel-time-function_018_35f1f2cce8',
    ).toBe(true);
  });
  it('019_879be89d63', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_019_879be89d63']), '11:22:33.444'),
      'feel-time-function_019_879be89d63',
    ).toBe(true);
  });
  it('020_72b421086e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_020_72b421086e']), '11:22:33.123456789'),
      'feel-time-function_020_72b421086e',
    ).toBe(true);
  });
  it('021_5c50fa1dff', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_021_5c50fa1dff']), '23:59:00Z'),
      'feel-time-function_021_5c50fa1dff',
    ).toBe(true);
  });
  it('022_55e76d3595', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_022_55e76d3595']), '11:00:00Z'),
      'feel-time-function_022_55e76d3595',
    ).toBe(true);
  });
  it('023_5cbbb85435', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_023_5cbbb85435']), '00:00:00Z'),
      'feel-time-function_023_5cbbb85435',
    ).toBe(true);
  });
  it('024_5f7f735e8f', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_024_5f7f735e8f']), '13:20:00+02:00'),
      'feel-time-function_024_5f7f735e8f',
    ).toBe(true);
  });
  it('025_139b25b795', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_025_139b25b795']), '13:20:00-05:00'),
      'feel-time-function_025_139b25b795',
    ).toBe(true);
  });
  it('026_c5208af118', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_026_c5208af118']), '11:22:33Z'),
      'feel-time-function_026_c5208af118',
    ).toBe(true);
  });
  it('027_45082fd26c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_027_45082fd26c']), '11:22:33Z'),
      'feel-time-function_027_45082fd26c',
    ).toBe(true);
  });
  it('028_eaea7a943c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_028_eaea7a943c']), '00:01:00@Etc/UTC'),
      'feel-time-function_028_eaea7a943c',
    ).toBe(true);
  });
  it('029_f0d5c2c16a', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_029_f0d5c2c16a']), '00:01:00@Europe/Paris'),
      'feel-time-function_029_f0d5c2c16a',
    ).toBe(true);
  });
  it('030_390d4f4648', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_030_390d4f4648']), '10:20:00'),
      'feel-time-function_030_390d4f4648',
    ).toBe(true);
  });
  it('031_4d086a3b59', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_031_4d086a3b59']), '10:20:00Z'),
      'feel-time-function_031_4d086a3b59',
    ).toBe(true);
  });
  it('032_d9b0d7f931', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_032_d9b0d7f931']), '10:20:00Z'),
      'feel-time-function_032_d9b0d7f931',
    ).toBe(true);
  });
  it('033_8420160da1', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_033_8420160da1']), '10:20:00+01:00'),
      'feel-time-function_033_8420160da1',
    ).toBe(true);
  });
  it('034_13c312c376', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_034_13c312c376']), '10:20:00-01:00'),
      'feel-time-function_034_13c312c376',
    ).toBe(true);
  });
  it('035_fbfce88ac4', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_035_fbfce88ac4']), '10:20:00Z'),
      'feel-time-function_035_fbfce88ac4',
    ).toBe(true);
  });
  it('036_eb05fabc01', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_036_eb05fabc01']), '10:20:00@Europe/Paris'),
      'feel-time-function_036_eb05fabc01',
    ).toBe(true);
  });
  it('037_eed195f693', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_037_eed195f693']), '11:20:00@Asia/Dhaka'),
      'feel-time-function_037_eed195f693',
    ).toBe(true);
  });
  it('038_05b311131c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_038_05b311131c']), '11:59:45'),
      'feel-time-function_038_05b311131c',
    ).toBe(true);
  });
  it('039_5b65992f0d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_039_5b65992f0d']), '11:59:45Z'),
      'feel-time-function_039_5b65992f0d',
    ).toBe(true);
  });
  it('040_6c9d17b491', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_040_6c9d17b491']), '11:59:45+02:00'),
      'feel-time-function_040_6c9d17b491',
    ).toBe(true);
  });
  it('041_29a448d57e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_041_29a448d57e']), '11:59:45-02:00'),
      'feel-time-function_041_29a448d57e',
    ).toBe(true);
  });
  it('042_00146f2977', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_042_00146f2977']), '11:59:00+02:01'),
      'feel-time-function_042_00146f2977',
    ).toBe(true);
  });
  it('043_2edfae8414', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_043_2edfae8414']), '11:59:00-02:01'),
      'feel-time-function_043_2edfae8414',
    ).toBe(true);
  });
  it('044_3073ffd026', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_044_3073ffd026']), '11:59:00+02:01'),
      'feel-time-function_044_3073ffd026',
    ).toBe(true);
  });
  it('045_ad1339e858', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_045_ad1339e858']), '11:59:00-02:01'),
      'feel-time-function_045_ad1339e858',
    ).toBe(true);
  });
  it('046_7b80221ec1', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_046_7b80221ec1']), '11:59:45+02:45:55'),
      'feel-time-function_046_7b80221ec1',
    ).toBe(true);
  });
  it('047_33cd7b9b15', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_047_33cd7b9b15']), '11:59:45-02:45:55'),
      'feel-time-function_047_33cd7b9b15',
    ).toBe(true);
  });
  it('048_9bedd52886', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_048_9bedd52886']), '11:59:45Z'),
      'feel-time-function_048_9bedd52886',
    ).toBe(true);
  });
  it('049_617d9e09d6', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_049_617d9e09d6']), '23:59:01'),
      'feel-time-function_049_617d9e09d6',
    ).toBe(true);
  });
  it('050_524d9a8146', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_050_524d9a8146']), '23:59:01.987654321'),
      'feel-time-function_050_524d9a8146',
    ).toBe(true);
  });
  it('051_a71d2a08f7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_051_a71d2a08f7']), '09:15:30+02:00'),
      'feel-time-function_051_a71d2a08f7',
    ).toBe(true);
  });
  it('052_d825d58888', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_052_d825d58888']), '09:15:30Z'),
      'feel-time-function_052_d825d58888',
    ).toBe(true);
  });
  it('053_3d956966c0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_053_3d956966c0']), '00:00:00Z'),
      'feel-time-function_053_3d956966c0',
    ).toBe(true);
  });
  it('054_fdc3094237', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_054_fdc3094237'])).toBeNull();
  });
  it('055_9b47db6ea4', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_055_9b47db6ea4'])).toBeNull();
  });
  it('056_a8e828d64d', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_056_a8e828d64d'])).toBeNull();
  });
  it('057_d039115cce', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_057_d039115cce'])).toBeNull();
  });
  it('058_81dd4b1639', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_058_81dd4b1639'])).toBeNull();
  });
  it('059_c7e1705fe1', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_059_c7e1705fe1'])).toBeNull();
  });
  it('060_0cf4734fae', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_060_0cf4734fae'])).toBeNull();
  });
  it('061_da2717f085', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_061_da2717f085'])).toBeNull();
  });
  it('062_6cd1313fa9', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_062_6cd1313fa9'])).toBeNull();
  });
  it('063_e85c40b474', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_063_e85c40b474'])).toBeNull();
  });
  it('064_df74038c67', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_064_df74038c67'])).toBeNull();
  });
  it('065_79eaef6fee', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_065_79eaef6fee'])).toBeNull();
  });
  it('066_5116e12fd3', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_066_5116e12fd3'])).toBeNull();
  });
  it('067_8285edad7b', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_067_8285edad7b'])).toBeNull();
  });
  it('068_ad528abb23', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_068_ad528abb23'])).toBeNull();
  });
  it('069_5096701e2e', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_069_5096701e2e'])).toBeNull();
  });
  it('070_8b2e39f570', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_070_8b2e39f570'])).toBeNull();
  });
  it('071_cf9417648b', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_071_cf9417648b'])).toBeNull();
  });
  it('072_4c8c3835e4', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_072_4c8c3835e4'])).toBeNull();
  });
  it('073_a5fc245959', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_073_a5fc245959'])).toBeNull();
  });
  it('074_387d4411ea', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_074_387d4411ea'])).toBeNull();
  });
  it('075_1606dda03d', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_075_1606dda03d'])).toBeNull();
  });
  it('076_cb117ca612', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_076_cb117ca612'])).toBeNull();
  });
  it('077_a4daad060c', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_077_a4daad060c'])).toBeNull();
  });
  it('078_c2fe73418b', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_078_c2fe73418b'])).toBeNull();
  });
  it('079_d2d226c3cd', () => {
    const ctx = run({});
    expect(n(ctx['feel-time-function_ErrorCase_079_d2d226c3cd'])).toBeNull();
  });
  it('080_2bbb8c86af', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_080_2bbb8c86af']), '23:59:00'),
      'feel-time-function_080_2bbb8c86af',
    ).toBe(true);
  });
  it('081_69f4e0231e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_081_69f4e0231e']), '12:45:00'),
      'feel-time-function_081_69f4e0231e',
    ).toBe(true);
  });
  it('082_36a78e5396', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_082_36a78e5396']), '11:59:00+02:01'),
      'feel-time-function_082_36a78e5396',
    ).toBe(true);
  });
  it('083_6b608254c7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-time-function_083_6b608254c7']), '11:59:00-02:00'),
      'feel-time-function_083_6b608254c7',
    ).toBe(true);
  });
});
