// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-date-and-time-function_ErrorCase_001_05fd7d6215', 'date and time(null)'],
  ['feel-date-and-time-function_ErrorCase_002_8c66ed2d1a', 'date and time(null,null)'],
  [
    'feel-date-and-time-function_ErrorCase_003_335cff371a',
    'date and time(date and time("2017-08-10T10:20:00"),null)',
  ],
  [
    'feel-date-and-time-function_ErrorCase_004_28ef3e7882',
    'date and time(date("2017-08-10"),null)',
  ],
  ['feel-date-and-time-function_ErrorCase_005_15df95b27a', 'date and time(null,time("23:59:01"))'],
  ['feel-date-and-time-function_ErrorCase_006_8c794da0bb', 'date and time()'],
  ['feel-date-and-time-function_007_59863d1b57', 'date and time("2012-12-24")'],
  ['feel-date-and-time-function_008_83eb9a93ba', 'date and time("2017-12-31T00:00:00")'],
  ['feel-date-and-time-function_009_1982fa549c', 'date and time("2017-12-31T11:22:33")'],
  ['feel-date-and-time-function_010_59f5b47012', 'date and time("-2017-12-31T11:22:33")'],
  ['feel-date-and-time-function_011_eec2d5bdcd', 'string(date and time("99999-12-31T11:22:33"))'],
  ['feel-date-and-time-function_012_225a105eef', 'string(date and time("-99999-12-31T11:22:33"))'],
  ['feel-date-and-time-function_013_c4fd0a0e8d', 'date and time("2017-12-31T11:22:33.345")'],
  ['feel-date-and-time-function_014_ded0e5fe2f', 'date and time("2017-12-31T11:22:33.123456789")'],
  ['feel-date-and-time-function_015_9e27148afd', 'date and time("2017-12-31T11:22:33Z")'],
  ['feel-date-and-time-function_016_c08e4d417a', 'date and time("2017-12-31T11:22:33.567Z")'],
  ['feel-date-and-time-function_017_47816add0e', 'date and time("2017-12-31T11:22:33+01:00")'],
  ['feel-date-and-time-function_018_0614e473e7', 'date and time("2017-12-31T11:22:33-02:00")'],
  ['feel-date-and-time-function_019_c312e3dfe3', 'date and time("2017-12-31T11:22:33+01:35")'],
  ['feel-date-and-time-function_020_29e0585b6f', 'date and time("2017-12-31T11:22:33-01:35")'],
  ['feel-date-and-time-function_021_99f0215b60', 'date and time("2017-12-31T11:22:33.456+01:35")'],
  ['feel-date-and-time-function_022_b8b20f0328', 'date and time("-2017-12-31T11:22:33.456+01:35")'],
  [
    'feel-date-and-time-function_023_2e41497673',
    'string(date and time("2011-12-31T10:15:30@Europe/Paris"))',
  ],
  [
    'feel-date-and-time-function_024_b4d1fb8735',
    'string(date and time("2011-12-31T10:15:30@Etc/UTC"))',
  ],
  [
    'feel-date-and-time-function_025_0cb7f83ec6',
    'string(date and time("2011-12-31T10:15:30.987@Europe/Paris"))',
  ],
  [
    'feel-date-and-time-function_026_5ba081cd5f',
    'string(date and time("2011-12-31T10:15:30.123456789@Europe/Paris"))',
  ],
  [
    'feel-date-and-time-function_027_ae365197dd',
    'string(date and time("999999999-12-31T23:59:59.999999999@Europe/Paris"))',
  ],
  [
    'feel-date-and-time-function_028_1c3d56275f',
    'string(date and time("-999999999-12-31T23:59:59.999999999+02:00"))',
  ],
  [
    'feel-date-and-time-function_029_e3a5e786a0',
    'date and time(date("2017-01-01"),time("23:59:01"))',
  ],
  [
    'feel-date-and-time-function_030_2f97bff606',
    'date and time(date("2017-01-01"),time("23:59:01Z"))',
  ],
  [
    'feel-date-and-time-function_031_61e70c285f',
    'date and time(date("2017-01-01"),time("23:59:01+02:00"))',
  ],
  [
    'feel-date-and-time-function_032_1e95e8726e',
    'string(date and time(date("2017-01-01"),time("23:59:01@Europe/Paris")))',
  ],
  [
    'feel-date-and-time-function_033_2fac4d6807',
    'string(date and time(date("2017-01-01"),time("23:59:01.123456789@Europe/Paris")))',
  ],
  [
    'feel-date-and-time-function_034_75580be3aa',
    'date and time(date and time("2017-08-10T10:20:00"),time("23:59:01"))',
  ],
  [
    'feel-date-and-time-function_035_831b1ad0c5',
    'date and time(date and time("2017-08-10T10:20:00"),time("23:59:01.987654321"))',
  ],
  [
    'feel-date-and-time-function_036_189e1c3095',
    'date and time(date and time("2017-09-05T10:20:00"),time("09:15:30+02:00"))',
  ],
  [
    'feel-date-and-time-function_037_c7aec7ecf7',
    'date and time(date and time("2017-09-05T10:20:00"),time("09:15:30Z"))',
  ],
  [
    'feel-date-and-time-function_038_1493e6d873',
    'date and time(date and time("2017-09-05T10:20:00"),time("09:15:30.987654321+02:00"))',
  ],
  [
    'feel-date-and-time-function_039_593292b25c',
    'date and time(date and time("2017-09-05T10:20:00"),time("09:15:30.123456Z"))',
  ],
  [
    'feel-date-and-time-function_040_d9116e1daa',
    'string(date and time(date and time("2017-09-05T10:20:00"),time("09:15:30.987654321@Europe/Paris")))',
  ],
  [
    'feel-date-and-time-function_041_c6decfe6a3',
    'date and time(date and time("2017-08-10T10:20:00+02:00"),time("23:59:01"))',
  ],
  [
    'feel-date-and-time-function_042_0cbcc3d1dc',
    'date and time(date and time("2017-08-10T10:20:00+02:00"),time("23:59:01.987654321"))',
  ],
  [
    'feel-date-and-time-function_043_2e4177d00c',
    'date and time(date and time("2017-09-05T10:20:00-01:00"),time("09:15:30+02:00"))',
  ],
  [
    'feel-date-and-time-function_044_9404547f9d',
    'date and time(date and time("2017-09-05T10:20:00-01:00"),time("09:15:30Z"))',
  ],
  [
    'feel-date-and-time-function_045_5d93a541eb',
    'date and time(date and time("2017-09-05T10:20:00+02:00"),time("09:15:30.987654321+02:00"))',
  ],
  [
    'feel-date-and-time-function_046_89c1cd8daa',
    'date and time(date and time("2017-09-05T10:20:00+02:00"),time("09:15:30.123456Z"))',
  ],
  [
    'feel-date-and-time-function_047_60ea7838ce',
    'string(date and time(date and time("2017-09-05T10:20:00-01:00"),time("09:15:30.987654321@Europe/Paris")))',
  ],
  [
    'feel-date-and-time-function_048_e387922273',
    'date and time(date and time("2017-08-10T10:20:00@Europe/Paris"),time("23:59:01"))',
  ],
  [
    'feel-date-and-time-function_049_eb9cd1f777',
    'date and time(date and time("2017-08-10T10:20:00@Europe/Paris"),time("23:59:01.987654321"))',
  ],
  [
    'feel-date-and-time-function_050_2d960354af',
    'date and time(date and time("2017-09-05T10:20:00@Europe/Paris"),time("09:15:30+02:00"))',
  ],
  [
    'feel-date-and-time-function_051_46bdaa00b0',
    'date and time(date and time("2017-09-05T10:20:00@Europe/Paris"),time("09:15:30Z"))',
  ],
  [
    'feel-date-and-time-function_052_911dbd0a24',
    'date and time(date and time("2017-09-05T10:20:00@Europe/Paris"),time("09:15:30.987654321+02:00"))',
  ],
  [
    'feel-date-and-time-function_053_283c083df9',
    'date and time(date and time("2017-09-05T10:20:00@Europe/Paris"),time("09:15:30.123456Z"))',
  ],
  [
    'feel-date-and-time-function_054_2561a406fc',
    'string(date and time(date and time("2017-09-05T10:20:00@Europe/Paris"),time("09:15:30.987654321@Europe/Paris")))',
  ],
  ['feel-date-and-time-function_ErrorCase_055_6ce9202e17', 'date and time(2017)'],
  ['feel-date-and-time-function_ErrorCase_056_e66397568e', 'date and time([])'],
  ['feel-date-and-time-function_ErrorCase_057_0452ca8719', 'date and time("")'],
  ['feel-date-and-time-function_ErrorCase_058_588040ceaa', 'date and time("11:00:00")'],
  ['feel-date-and-time-function_ErrorCase_059_dfc62a3ebc', 'date and time("2011-12-0310:15:30")'],
  [
    'feel-date-and-time-function_ErrorCase_060_890c302575',
    'date and time("2011-12-03T10:15:30+01:00@Europe/Paris")',
  ],
  [
    'feel-date-and-time-function_ErrorCase_061_38ea1fc94d',
    'date and time("9999999999-12-27T11:22:33")',
  ],
  ['feel-date-and-time-function_ErrorCase_062_528aa370a3', 'date and time("2017-13-10T11:22:33")'],
  ['feel-date-and-time-function_ErrorCase_063_2c94303011', 'date and time("2017-00-10T11:22:33")'],
  ['feel-date-and-time-function_ErrorCase_064_926a372666', 'date and time("2017-13-32T11:22:33")'],
  ['feel-date-and-time-function_ErrorCase_065_a13de18ee4', 'date and time("2017-13-0T11:22:33")'],
  ['feel-date-and-time-function_ErrorCase_066_e9f3d6d2c2', 'date and time("998-12-31T11:22:33")'],
  ['feel-date-and-time-function_ErrorCase_067_35fef99b53', 'date and time("01211-12-31T11:22:33")'],
  [
    'feel-date-and-time-function_ErrorCase_068_abaa1c2774',
    'date and time("+99999-12-01T11:22:33")',
  ],
  ['feel-date-and-time-function_ErrorCase_069_ca84e9c806', 'date and time("2017-12-31T24:00:01")'],
  ['feel-date-and-time-function_ErrorCase_070_889c75a0cf', 'date and time("2017-12-31T24:01:00")'],
  ['feel-date-and-time-function_ErrorCase_071_e90b813dfe', 'date and time("2017-12-31T25:00:00")'],
  ['feel-date-and-time-function_ErrorCase_072_9f3e9b9c21', 'date and time("2017-12-31T00:60:00")'],
  ['feel-date-and-time-function_ErrorCase_073_717548bec6', 'date and time("2017-12-31T00:00:61")'],
  ['feel-date-and-time-function_ErrorCase_074_a15e7f8d29', 'date and time("2017-12-31T7:00:00")'],
  ['feel-date-and-time-function_ErrorCase_075_4c3b8e7097', 'date and time("2017-12-31T07:1:00")'],
  ['feel-date-and-time-function_ErrorCase_076_4d31fed18e', 'date and time("2017-12-31T07:01:2")'],
  [
    'feel-date-and-time-function_ErrorCase_077_f83b3ac8bb',
    'date and time("2017-12-31T13:20:00@xyz/abc")',
  ],
  [
    'feel-date-and-time-function_ErrorCase_078_e113dabcdd',
    'date and time("2017-12-31T13:20:00+19:00")',
  ],
  [
    'feel-date-and-time-function_ErrorCase_079_2e6f80eb94',
    'date and time("2017-12-31T13:20:00-19:00")',
  ],
  [
    'feel-date-and-time-function_ErrorCase_080_69de952053',
    'date and time("2017-12-31T13:20:00+05:0")',
  ],
  [
    'feel-date-and-time-function_ErrorCase_081_e063215a7c',
    'date and time("2017-12-31T13:20:00+5:00")',
  ],
  [
    'feel-date-and-time-function_ErrorCase_082_5b6ed4e801',
    'date and time("2017-12-31T13:20:00+5")',
  ],
  [
    'feel-date-and-time-function_ErrorCase_083_4f41731f2a',
    'date and time("2017-12-31T13:20:00+02:00@Europe/Paris")',
  ],
  ['feel-date-and-time-function_ErrorCase_084_c633b01603', 'date and time("2017-12-31T7:20")'],
  ['feel-date-and-time-function_ErrorCase_085_a604a1bc80', 'date and time("2017-12-31T07:2")'],
  ['feel-date-and-time-function_086_12ca8ac1d3', 'date and time(from:"2012-12-24T23:59:00")'],
  [
    'feel-date-and-time-function_087_e9fd32063a',
    'date and time(date:date("2017-01-01"),time:time("23:59:01"))',
  ],
  [
    'feel-date-and-time-function_088_1db0287718',
    'date and time(date:date and time("2017-01-01T00:00:00"),time:time("23:59:01"))',
  ],
];

describe('FEEL TCK / 1117-feel-date-and-time-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_05fd7d6215', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_001_05fd7d6215'])).toBeNull();
  });
  it('002_8c66ed2d1a', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_002_8c66ed2d1a'])).toBeNull();
  });
  it('003_335cff371a', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_003_335cff371a'])).toBeNull();
  });
  it('004_28ef3e7882', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_004_28ef3e7882'])).toBeNull();
  });
  it('005_15df95b27a', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_005_15df95b27a'])).toBeNull();
  });
  it('006_8c794da0bb', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_006_8c794da0bb'])).toBeNull();
  });
  it('007_59863d1b57', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_007_59863d1b57']), '2012-12-24T00:00:00'),
      'feel-date-and-time-function_007_59863d1b57',
    ).toBe(true);
  });
  it('008_83eb9a93ba', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_008_83eb9a93ba']), '2017-12-31T00:00:00'),
      'feel-date-and-time-function_008_83eb9a93ba',
    ).toBe(true);
  });
  it('009_1982fa549c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_009_1982fa549c']), '2017-12-31T11:22:33'),
      'feel-date-and-time-function_009_1982fa549c',
    ).toBe(true);
  });
  it('010_59f5b47012', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_010_59f5b47012']), '-2017-12-31T11:22:33'),
      'feel-date-and-time-function_010_59f5b47012',
    ).toBe(true);
  });
  it('011_eec2d5bdcd', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_011_eec2d5bdcd']), '99999-12-31T11:22:33'),
      'feel-date-and-time-function_011_eec2d5bdcd',
    ).toBe(true);
  });
  it('012_225a105eef', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_012_225a105eef']), '-99999-12-31T11:22:33'),
      'feel-date-and-time-function_012_225a105eef',
    ).toBe(true);
  });
  it('013_c4fd0a0e8d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_013_c4fd0a0e8d']), '2017-12-31T11:22:33.345'),
      'feel-date-and-time-function_013_c4fd0a0e8d',
    ).toBe(true);
  });
  it('014_ded0e5fe2f', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_014_ded0e5fe2f']), '2017-12-31T11:22:33.123456789'),
      'feel-date-and-time-function_014_ded0e5fe2f',
    ).toBe(true);
  });
  it('015_9e27148afd', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_015_9e27148afd']), '2017-12-31T11:22:33Z'),
      'feel-date-and-time-function_015_9e27148afd',
    ).toBe(true);
  });
  it('016_c08e4d417a', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_016_c08e4d417a']), '2017-12-31T11:22:33.567Z'),
      'feel-date-and-time-function_016_c08e4d417a',
    ).toBe(true);
  });
  it('017_47816add0e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_017_47816add0e']), '2017-12-31T11:22:33+01:00'),
      'feel-date-and-time-function_017_47816add0e',
    ).toBe(true);
  });
  it('018_0614e473e7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_018_0614e473e7']), '2017-12-31T11:22:33-02:00'),
      'feel-date-and-time-function_018_0614e473e7',
    ).toBe(true);
  });
  it('019_c312e3dfe3', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_019_c312e3dfe3']), '2017-12-31T11:22:33+01:35'),
      'feel-date-and-time-function_019_c312e3dfe3',
    ).toBe(true);
  });
  it('020_29e0585b6f', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_020_29e0585b6f']), '2017-12-31T11:22:33-01:35'),
      'feel-date-and-time-function_020_29e0585b6f',
    ).toBe(true);
  });
  it('021_99f0215b60', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_021_99f0215b60']), '2017-12-31T11:22:33.456+01:35'),
      'feel-date-and-time-function_021_99f0215b60',
    ).toBe(true);
  });
  it('022_b8b20f0328', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_022_b8b20f0328']), '-2017-12-31T11:22:33.456+01:35'),
      'feel-date-and-time-function_022_b8b20f0328',
    ).toBe(true);
  });
  it('023_2e41497673', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_023_2e41497673']), '2011-12-31T10:15:30@Europe/Paris'),
      'feel-date-and-time-function_023_2e41497673',
    ).toBe(true);
  });
  it('024_b4d1fb8735', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_024_b4d1fb8735']), '2011-12-31T10:15:30@Etc/UTC'),
      'feel-date-and-time-function_024_b4d1fb8735',
    ).toBe(true);
  });
  it('025_0cb7f83ec6', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_025_0cb7f83ec6']),
        '2011-12-31T10:15:30.987@Europe/Paris',
      ),
      'feel-date-and-time-function_025_0cb7f83ec6',
    ).toBe(true);
  });
  it('026_5ba081cd5f', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_026_5ba081cd5f']),
        '2011-12-31T10:15:30.123456789@Europe/Paris',
      ),
      'feel-date-and-time-function_026_5ba081cd5f',
    ).toBe(true);
  });
  it('027_ae365197dd', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_027_ae365197dd']),
        '999999999-12-31T23:59:59.999999999@Europe/Paris',
      ),
      'feel-date-and-time-function_027_ae365197dd',
    ).toBe(true);
  });
  it('028_1c3d56275f', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_028_1c3d56275f']),
        '-999999999-12-31T23:59:59.999999999+02:00',
      ),
      'feel-date-and-time-function_028_1c3d56275f',
    ).toBe(true);
  });
  it('029_e3a5e786a0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_029_e3a5e786a0']), '2017-01-01T23:59:01'),
      'feel-date-and-time-function_029_e3a5e786a0',
    ).toBe(true);
  });
  it('030_2f97bff606', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_030_2f97bff606']), '2017-01-01T23:59:01Z'),
      'feel-date-and-time-function_030_2f97bff606',
    ).toBe(true);
  });
  it('031_61e70c285f', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_031_61e70c285f']), '2017-01-01T23:59:01+02:00'),
      'feel-date-and-time-function_031_61e70c285f',
    ).toBe(true);
  });
  it('032_1e95e8726e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_032_1e95e8726e']), '2017-01-01T23:59:01@Europe/Paris'),
      'feel-date-and-time-function_032_1e95e8726e',
    ).toBe(true);
  });
  it('033_2fac4d6807', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_033_2fac4d6807']),
        '2017-01-01T23:59:01.123456789@Europe/Paris',
      ),
      'feel-date-and-time-function_033_2fac4d6807',
    ).toBe(true);
  });
  it('034_75580be3aa', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_034_75580be3aa']), '2017-08-10T23:59:01'),
      'feel-date-and-time-function_034_75580be3aa',
    ).toBe(true);
  });
  it('035_831b1ad0c5', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_035_831b1ad0c5']), '2017-08-10T23:59:01.987654321'),
      'feel-date-and-time-function_035_831b1ad0c5',
    ).toBe(true);
  });
  it('036_189e1c3095', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_036_189e1c3095']), '2017-09-05T09:15:30+02:00'),
      'feel-date-and-time-function_036_189e1c3095',
    ).toBe(true);
  });
  it('037_c7aec7ecf7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_037_c7aec7ecf7']), '2017-09-05T09:15:30Z'),
      'feel-date-and-time-function_037_c7aec7ecf7',
    ).toBe(true);
  });
  it('038_1493e6d873', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_038_1493e6d873']),
        '2017-09-05T09:15:30.987654321+02:00',
      ),
      'feel-date-and-time-function_038_1493e6d873',
    ).toBe(true);
  });
  it('039_593292b25c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_039_593292b25c']), '2017-09-05T09:15:30.123456Z'),
      'feel-date-and-time-function_039_593292b25c',
    ).toBe(true);
  });
  it('040_d9116e1daa', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_040_d9116e1daa']),
        '2017-09-05T09:15:30.987654321@Europe/Paris',
      ),
      'feel-date-and-time-function_040_d9116e1daa',
    ).toBe(true);
  });
  it('041_c6decfe6a3', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_041_c6decfe6a3']), '2017-08-10T23:59:01'),
      'feel-date-and-time-function_041_c6decfe6a3',
    ).toBe(true);
  });
  it('042_0cbcc3d1dc', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_042_0cbcc3d1dc']), '2017-08-10T23:59:01.987654321'),
      'feel-date-and-time-function_042_0cbcc3d1dc',
    ).toBe(true);
  });
  it('043_2e4177d00c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_043_2e4177d00c']), '2017-09-05T09:15:30+02:00'),
      'feel-date-and-time-function_043_2e4177d00c',
    ).toBe(true);
  });
  it('044_9404547f9d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_044_9404547f9d']), '2017-09-05T09:15:30Z'),
      'feel-date-and-time-function_044_9404547f9d',
    ).toBe(true);
  });
  it('045_5d93a541eb', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_045_5d93a541eb']),
        '2017-09-05T09:15:30.987654321+02:00',
      ),
      'feel-date-and-time-function_045_5d93a541eb',
    ).toBe(true);
  });
  it('046_89c1cd8daa', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_046_89c1cd8daa']), '2017-09-05T09:15:30.123456Z'),
      'feel-date-and-time-function_046_89c1cd8daa',
    ).toBe(true);
  });
  it('047_60ea7838ce', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_047_60ea7838ce']),
        '2017-09-05T09:15:30.987654321@Europe/Paris',
      ),
      'feel-date-and-time-function_047_60ea7838ce',
    ).toBe(true);
  });
  it('048_e387922273', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_048_e387922273']), '2017-08-10T23:59:01'),
      'feel-date-and-time-function_048_e387922273',
    ).toBe(true);
  });
  it('049_eb9cd1f777', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_049_eb9cd1f777']), '2017-08-10T23:59:01.987654321'),
      'feel-date-and-time-function_049_eb9cd1f777',
    ).toBe(true);
  });
  it('050_2d960354af', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_050_2d960354af']), '2017-09-05T09:15:30+02:00'),
      'feel-date-and-time-function_050_2d960354af',
    ).toBe(true);
  });
  it('051_46bdaa00b0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_051_46bdaa00b0']), '2017-09-05T09:15:30Z'),
      'feel-date-and-time-function_051_46bdaa00b0',
    ).toBe(true);
  });
  it('052_911dbd0a24', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_052_911dbd0a24']),
        '2017-09-05T09:15:30.987654321+02:00',
      ),
      'feel-date-and-time-function_052_911dbd0a24',
    ).toBe(true);
  });
  it('053_283c083df9', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_053_283c083df9']), '2017-09-05T09:15:30.123456Z'),
      'feel-date-and-time-function_053_283c083df9',
    ).toBe(true);
  });
  it('054_2561a406fc', () => {
    const ctx = run({});
    expect(
      aeq(
        n(ctx['feel-date-and-time-function_054_2561a406fc']),
        '2017-09-05T09:15:30.987654321@Europe/Paris',
      ),
      'feel-date-and-time-function_054_2561a406fc',
    ).toBe(true);
  });
  it('055_6ce9202e17', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_055_6ce9202e17'])).toBeNull();
  });
  it('056_e66397568e', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_056_e66397568e'])).toBeNull();
  });
  it('057_0452ca8719', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_057_0452ca8719'])).toBeNull();
  });
  it('058_588040ceaa', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_058_588040ceaa'])).toBeNull();
  });
  it('059_dfc62a3ebc', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_059_dfc62a3ebc'])).toBeNull();
  });
  it('060_890c302575', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_060_890c302575'])).toBeNull();
  });
  it('061_38ea1fc94d', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_061_38ea1fc94d'])).toBeNull();
  });
  it('062_528aa370a3', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_062_528aa370a3'])).toBeNull();
  });
  it('063_2c94303011', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_063_2c94303011'])).toBeNull();
  });
  it('064_926a372666', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_064_926a372666'])).toBeNull();
  });
  it('065_a13de18ee4', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_065_a13de18ee4'])).toBeNull();
  });
  it('066_e9f3d6d2c2', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_066_e9f3d6d2c2'])).toBeNull();
  });
  it('067_35fef99b53', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_067_35fef99b53'])).toBeNull();
  });
  it('068_abaa1c2774', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_068_abaa1c2774'])).toBeNull();
  });
  it('069_ca84e9c806', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_069_ca84e9c806'])).toBeNull();
  });
  it('070_889c75a0cf', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_070_889c75a0cf'])).toBeNull();
  });
  it('071_e90b813dfe', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_071_e90b813dfe'])).toBeNull();
  });
  it('072_9f3e9b9c21', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_072_9f3e9b9c21'])).toBeNull();
  });
  it('073_717548bec6', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_073_717548bec6'])).toBeNull();
  });
  it('074_a15e7f8d29', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_074_a15e7f8d29'])).toBeNull();
  });
  it('075_4c3b8e7097', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_075_4c3b8e7097'])).toBeNull();
  });
  it('076_4d31fed18e', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_076_4d31fed18e'])).toBeNull();
  });
  it('077_f83b3ac8bb', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_077_f83b3ac8bb'])).toBeNull();
  });
  it('078_e113dabcdd', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_078_e113dabcdd'])).toBeNull();
  });
  it('079_2e6f80eb94', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_079_2e6f80eb94'])).toBeNull();
  });
  it('080_69de952053', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_080_69de952053'])).toBeNull();
  });
  it('081_e063215a7c', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_081_e063215a7c'])).toBeNull();
  });
  it('082_5b6ed4e801', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_082_5b6ed4e801'])).toBeNull();
  });
  it('083_4f41731f2a', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_083_4f41731f2a'])).toBeNull();
  });
  it('084_c633b01603', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_084_c633b01603'])).toBeNull();
  });
  it('085_a604a1bc80', () => {
    const ctx = run({});
    expect(n(ctx['feel-date-and-time-function_ErrorCase_085_a604a1bc80'])).toBeNull();
  });
  it('086_12ca8ac1d3', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_086_12ca8ac1d3']), '2012-12-24T23:59:00'),
      'feel-date-and-time-function_086_12ca8ac1d3',
    ).toBe(true);
  });
  it('087_e9fd32063a', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_087_e9fd32063a']), '2017-01-01T23:59:01'),
      'feel-date-and-time-function_087_e9fd32063a',
    ).toBe(true);
  });
  it('088_1db0287718', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-date-and-time-function_088_1db0287718']), '2017-01-01T23:59:01'),
      'feel-date-and-time-function_088_1db0287718',
    ).toBe(true);
  });
});
