// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['feel-duration-function_ErrorCase_001_f2c6cd6866', 'duration(null)'],
  ['feel-duration-function_ErrorCase_002_ddca5756ca', 'duration()'],
  ['feel-duration-function_003_951e1d1c31', 'duration("P1D")'],
  ['feel-duration-function_004_6b31e7cde7', 'duration("PT2H")'],
  ['feel-duration-function_005_202d863d07', 'duration("PT3M")'],
  ['feel-duration-function_006_a885f926d9', 'duration("PT4S")'],
  ['feel-duration-function_007_2f0ad399f3', 'duration("PT0.999S")'],
  ['feel-duration-function_008_747f56743d', 'duration("P1DT2H3M4.123456789S")'],
  ['feel-duration-function_009_cef3c1ed26', 'duration("PT0S")'],
  ['feel-duration-function_010_5b452a4975', 'duration("PT0.000S")'],
  ['feel-duration-function_011_2169615b94', 'duration("PT0.S")'],
  ['feel-duration-function_012_2affe6d169', 'duration("PT0M")'],
  ['feel-duration-function_013_0e8e26513c', 'duration("PT0H")'],
  ['feel-duration-function_014_598ba6fabd', 'duration("P0D")'],
  ['feel-duration-function_015_ce2cb09830', 'duration("-PT1H2M")'],
  ['feel-duration-function_016_af3e37fdbd', 'duration("PT1000M")'],
  ['feel-duration-function_017_4f4549fda4', 'duration("PT1000M0.999999999S")'],
  ['feel-duration-function_018_f5ec776811', 'duration("PT555M")'],
  ['feel-duration-function_019_2e6885755a', 'duration("PT61M")'],
  ['feel-duration-function_020_af58b3766e', 'duration("PT24H")'],
  ['feel-duration-function_021_e48e70ad4e', 'duration("PT240H")'],
  ['feel-duration-function_022_668f24bed7', 'duration("P2DT100M")'],
  ['feel-duration-function_023_6fc32087db', 'duration("PT3600S")'],
  ['feel-duration-function_024_fd7000d72f', 'duration("P2DT274M")'],
  ['feel-duration-function_025_f8ffbd8658', 'duration("P1Y2M")'],
  ['feel-duration-function_026_e6c47f0cae', 'duration("P1Y")'],
  ['feel-duration-function_027_33b7fb8704', 'duration("P0Y")'],
  ['feel-duration-function_028_971b94f16d', 'duration("P0M")'],
  ['feel-duration-function_029_1a12a226cc', 'duration("-P1Y")'],
  ['feel-duration-function_030_afac0f2062', 'duration("P26M")'],
  ['feel-duration-function_031_1ddad718b9', 'duration("P1Y27M")'],
  ['feel-duration-function_032_72c46a9ec9', 'duration("P100M")'],
  ['feel-duration-function_033_5d1540abaf', 'duration("-P100M")'],
  ['feel-duration-function_034_aa9cbb21a6', 'duration("P999999999M")'],
  ['feel-duration-function_035_93eef01ae7', 'duration("-P999999999M")'],
  ['feel-duration-function_036_5f2775875e', 'duration("P99999999Y")'],
  ['feel-duration-function_037_8c9ea9c0e6', 'duration("-P99999999Y")'],
  ['feel-duration-function_038_67dc4c254c', 'duration(from:"P1Y")'],
  ['feel-duration-function_039_4aa0b67804', 'duration(from:"PT24H")'],
  ['feel-duration-function_040_7d8eae461f', 'duration(from:"P26M")'],
  ['feel-duration-function_ErrorCase_041_264bc9d682', 'duration("")'],
  ['feel-duration-function_ErrorCase_042_59a0000245', 'duration(2017)'],
  ['feel-duration-function_ErrorCase_043_253815dc6c', 'duration("2012T-12-2511:00:00Z")'],
  ['feel-duration-function_ErrorCase_044_f3b338d877', 'duration([])'],
  ['feel-duration-function_ErrorCase_045_2ffcc37801', 'duration("P")'],
  ['feel-duration-function_ErrorCase_046_eb637de5f6', 'duration("P0")'],
  ['feel-duration-function_ErrorCase_047_3210c46a5a', 'duration("1Y")'],
  ['feel-duration-function_ErrorCase_048_ab6244f767', 'duration("1D")'],
  ['feel-duration-function_ErrorCase_049_2225b503a0', 'duration("P1H")'],
  ['feel-duration-function_ErrorCase_050_dd2ef33bbd', 'duration("P1S")'],
];

describe('FEEL TCK / 1120-feel-duration-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_f2c6cd6866', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_001_f2c6cd6866'])).toBeNull();
  });
  it('002_ddca5756ca', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_002_ddca5756ca'])).toBeNull();
  });
  it('003_951e1d1c31', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_003_951e1d1c31']), 'P1D'),
      'feel-duration-function_003_951e1d1c31',
    ).toBe(true);
  });
  it('004_6b31e7cde7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_004_6b31e7cde7']), 'PT2H'),
      'feel-duration-function_004_6b31e7cde7',
    ).toBe(true);
  });
  it('005_202d863d07', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_005_202d863d07']), 'PT3M'),
      'feel-duration-function_005_202d863d07',
    ).toBe(true);
  });
  it('006_a885f926d9', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_006_a885f926d9']), 'PT4S'),
      'feel-duration-function_006_a885f926d9',
    ).toBe(true);
  });
  it('007_2f0ad399f3', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_007_2f0ad399f3']), 'PT0.999S'),
      'feel-duration-function_007_2f0ad399f3',
    ).toBe(true);
  });
  it('008_747f56743d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_008_747f56743d']), 'P1DT2H3M4.123456789S'),
      'feel-duration-function_008_747f56743d',
    ).toBe(true);
  });
  it('009_cef3c1ed26', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_009_cef3c1ed26']), 'P0D'),
      'feel-duration-function_009_cef3c1ed26',
    ).toBe(true);
  });
  it('010_5b452a4975', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_010_5b452a4975']), 'P0D'),
      'feel-duration-function_010_5b452a4975',
    ).toBe(true);
  });
  it('011_2169615b94', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_011_2169615b94']), 'P0D'),
      'feel-duration-function_011_2169615b94',
    ).toBe(true);
  });
  it('012_2affe6d169', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_012_2affe6d169']), 'P0D'),
      'feel-duration-function_012_2affe6d169',
    ).toBe(true);
  });
  it('013_0e8e26513c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_013_0e8e26513c']), 'P0D'),
      'feel-duration-function_013_0e8e26513c',
    ).toBe(true);
  });
  it('014_598ba6fabd', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_014_598ba6fabd']), 'P0D'),
      'feel-duration-function_014_598ba6fabd',
    ).toBe(true);
  });
  it('015_ce2cb09830', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_015_ce2cb09830']), '-PT1H2M'),
      'feel-duration-function_015_ce2cb09830',
    ).toBe(true);
  });
  it('016_af3e37fdbd', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_016_af3e37fdbd']), 'PT16H40M'),
      'feel-duration-function_016_af3e37fdbd',
    ).toBe(true);
  });
  it('017_4f4549fda4', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_017_4f4549fda4']), 'PT16H40M0.999999999S'),
      'feel-duration-function_017_4f4549fda4',
    ).toBe(true);
  });
  it('018_f5ec776811', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_018_f5ec776811']), 'PT9H15M'),
      'feel-duration-function_018_f5ec776811',
    ).toBe(true);
  });
  it('019_2e6885755a', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_019_2e6885755a']), 'PT1H1M'),
      'feel-duration-function_019_2e6885755a',
    ).toBe(true);
  });
  it('020_af58b3766e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_020_af58b3766e']), 'P1D'),
      'feel-duration-function_020_af58b3766e',
    ).toBe(true);
  });
  it('021_e48e70ad4e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_021_e48e70ad4e']), 'P10D'),
      'feel-duration-function_021_e48e70ad4e',
    ).toBe(true);
  });
  it('022_668f24bed7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_022_668f24bed7']), 'P2DT1H40M'),
      'feel-duration-function_022_668f24bed7',
    ).toBe(true);
  });
  it('023_6fc32087db', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_023_6fc32087db']), 'PT1H'),
      'feel-duration-function_023_6fc32087db',
    ).toBe(true);
  });
  it('024_fd7000d72f', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_024_fd7000d72f']), 'P2DT4H34M'),
      'feel-duration-function_024_fd7000d72f',
    ).toBe(true);
  });
  it('025_f8ffbd8658', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_025_f8ffbd8658']), 'P1Y2M'),
      'feel-duration-function_025_f8ffbd8658',
    ).toBe(true);
  });
  it('026_e6c47f0cae', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_026_e6c47f0cae']), 'P1Y'),
      'feel-duration-function_026_e6c47f0cae',
    ).toBe(true);
  });
  it('027_33b7fb8704', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_027_33b7fb8704']), 'P0Y'),
      'feel-duration-function_027_33b7fb8704',
    ).toBe(true);
  });
  it('028_971b94f16d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_028_971b94f16d']), 'P0Y'),
      'feel-duration-function_028_971b94f16d',
    ).toBe(true);
  });
  it('029_1a12a226cc', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_029_1a12a226cc']), '-P1Y'),
      'feel-duration-function_029_1a12a226cc',
    ).toBe(true);
  });
  it('030_afac0f2062', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_030_afac0f2062']), 'P2Y2M'),
      'feel-duration-function_030_afac0f2062',
    ).toBe(true);
  });
  it('031_1ddad718b9', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_031_1ddad718b9']), 'P3Y3M'),
      'feel-duration-function_031_1ddad718b9',
    ).toBe(true);
  });
  it('032_72c46a9ec9', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_032_72c46a9ec9']), 'P8Y4M'),
      'feel-duration-function_032_72c46a9ec9',
    ).toBe(true);
  });
  it('033_5d1540abaf', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_033_5d1540abaf']), '-P8Y4M'),
      'feel-duration-function_033_5d1540abaf',
    ).toBe(true);
  });
  it('034_aa9cbb21a6', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_034_aa9cbb21a6']), 'P83333333Y3M'),
      'feel-duration-function_034_aa9cbb21a6',
    ).toBe(true);
  });
  it('035_93eef01ae7', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_035_93eef01ae7']), '-P83333333Y3M'),
      'feel-duration-function_035_93eef01ae7',
    ).toBe(true);
  });
  it('036_5f2775875e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_036_5f2775875e']), 'P99999999Y'),
      'feel-duration-function_036_5f2775875e',
    ).toBe(true);
  });
  it('037_8c9ea9c0e6', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_037_8c9ea9c0e6']), '-P99999999Y'),
      'feel-duration-function_037_8c9ea9c0e6',
    ).toBe(true);
  });
  it('038_67dc4c254c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_038_67dc4c254c']), 'P1Y'),
      'feel-duration-function_038_67dc4c254c',
    ).toBe(true);
  });
  it('039_4aa0b67804', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_039_4aa0b67804']), 'P1D'),
      'feel-duration-function_039_4aa0b67804',
    ).toBe(true);
  });
  it('040_7d8eae461f', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-duration-function_040_7d8eae461f']), 'P2Y2M'),
      'feel-duration-function_040_7d8eae461f',
    ).toBe(true);
  });
  it('041_264bc9d682', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_041_264bc9d682'])).toBeNull();
  });
  it('042_59a0000245', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_042_59a0000245'])).toBeNull();
  });
  it('043_253815dc6c', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_043_253815dc6c'])).toBeNull();
  });
  it('044_f3b338d877', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_044_f3b338d877'])).toBeNull();
  });
  it('045_2ffcc37801', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_045_2ffcc37801'])).toBeNull();
  });
  it('046_eb637de5f6', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_046_eb637de5f6'])).toBeNull();
  });
  it('047_3210c46a5a', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_047_3210c46a5a'])).toBeNull();
  });
  it('048_ab6244f767', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_048_ab6244f767'])).toBeNull();
  });
  it('049_2225b503a0', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_049_2225b503a0'])).toBeNull();
  });
  it('050_dd2ef33bbd', () => {
    const ctx = run({});
    expect(n(ctx['feel-duration-function_ErrorCase_050_dd2ef33bbd'])).toBeNull();
  });
});
