// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  [
    'feel-years-and-months-duration-function_ErrorCase_001_b24a0c91f2',
    'years and months duration(null)',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_002_4e7651ae0e',
    'years and months duration(null,null)',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_003_0886738d31',
    'years and months duration(date("2017-08-11"),null)',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_004_1bdfef922b',
    'years and months duration(date and time("2017-12-31T13:00:00"),null)',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_005_d0a077da4e',
    'years and months duration(null,date("2017-08-11"))',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_006_f20de28d3f',
    'years and months duration(null,date and time("2019-10-01T12:32:59"))',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_007_0921c3d61a',
    'years and months duration()',
  ],
  [
    'feel-years-and-months-duration-function_008_015d35b442',
    'years and months duration(date("2011-12-22"),date("2013-08-24"))',
  ],
  [
    'feel-years-and-months-duration-function_009_635028a5d8',
    'years and months duration(date("2013-08-24"),date("2011-12-22"))',
  ],
  [
    'feel-years-and-months-duration-function_010_caaa2e5002',
    'years and months duration(date("2015-01-21"),date("2016-01-21"))',
  ],
  [
    'feel-years-and-months-duration-function_011_3fac022eb0',
    'years and months duration(date("2016-01-21"),date("2015-01-21"))',
  ],
  [
    'feel-years-and-months-duration-function_012_331ef38ce0',
    'years and months duration(date("2016-01-01"),date("2016-01-01"))',
  ],
  [
    'feel-years-and-months-duration-function_013_2f3cc46d9d',
    'years and months duration(date and time("2017-12-31T13:00:00"), date and time("2017-12-31T12:00:00"))',
  ],
  [
    'feel-years-and-months-duration-function_014_1fadbba7cd',
    'years and months duration(date and time("2016-09-30T23:25:00"), date and time("2017-12-28T12:12:12"))',
  ],
  [
    'feel-years-and-months-duration-function_015_0e496f94fc',
    'years and months duration(date and time("2010-05-30T03:55:58"), date and time("2017-12-15T00:59:59"))',
  ],
  [
    'feel-years-and-months-duration-function_016_b38662aa93',
    'years and months duration(date and time("2014-12-31T23:59:59"), date and time("2019-10-01T12:32:59"))',
  ],
  [
    'feel-years-and-months-duration-function_017_86744b9a54',
    'years and months duration(date and time("-2016-01-30T09:05:00"), date and time("-2017-02-28T02:02:02"))',
  ],
  [
    'feel-years-and-months-duration-function_018_8a9ed1d66d',
    'years and months duration(date and time("2014-12-31T23:59:59"), date and time("-2019-10-01T12:32:59"))',
  ],
  [
    'feel-years-and-months-duration-function_019_90c2084588',
    'years and months duration(date and time("2017-09-05T10:20:00-01:00"), date and time("-2019-10-01T12:32:59+02:00"))',
  ],
  [
    'feel-years-and-months-duration-function_020_8ead9a0377',
    'years and months duration(date and time("2017-09-05T10:20:00+05:00"), date and time("2019-10-01T12:32:59"))',
  ],
  [
    'feel-years-and-months-duration-function_021_8a7d311ae9',
    'years and months duration(date and time("2016-08-25T15:20:59+02:00"), date and time("2017-08-10T10:20:00@Europe/Paris"))',
  ],
  [
    'feel-years-and-months-duration-function_022_87e369773b',
    'years and months duration(date and time("2011-12-31T10:15:30@Etc/UTC"), date and time("2017-08-10T10:20:00@Europe/Paris"))',
  ],
  [
    'feel-years-and-months-duration-function_023_6385c7a83e',
    'years and months duration(date and time("2017-09-05T10:20:00@Etc/UTC"), date and time("2018-10-01T23:59:59"))',
  ],
  [
    'feel-years-and-months-duration-function_024_e96d1bd93a',
    'years and months duration(date and time("2011-08-25T15:59:59@Europe/Paris"), date and time("2015-08-25T15:20:59+02:00"))',
  ],
  [
    'feel-years-and-months-duration-function_025_161f6fca54',
    'years and months duration(date and time("2015-12-31T23:59:59.9999999"), date and time("2018-10-01T12:32:59.111111"))',
  ],
  [
    'feel-years-and-months-duration-function_026_fcc906b375',
    'years and months duration(date and time("2016-09-05T22:20:55.123456+05:00"), date and time("2019-10-01T12:32:59.32415645"))',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_027_3374dd86c6',
    'years and months duration(date(""),date(""))',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_028_77600e7b35',
    'years and months duration(2017)',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_029_15a0d0d9c1',
    'years and months duration("2012T-12-2511:00:00Z")',
  ],
  [
    'feel-years-and-months-duration-function_ErrorCase_030_ec16878596',
    'years and months duration([],[])',
  ],
  [
    'feel-years-and-months-duration-function_031_4fd9c09d89',
    'years and months duration(date("2013-08-24"), date and time("2017-12-15T00:59:59"))',
  ],
  [
    'feel-years-and-months-duration-function_032_2a09ac80d0',
    'years and months duration(date and time("2017-02-28T23:59:59"), date("2019-07-23") )',
  ],
  [
    'feel-years-and-months-duration-function_033_7333eca866',
    'years and months duration(from:date and time("2016-12-31T00:00:01"),to:date and time("2017-12-31T23:59:59"))',
  ],
  [
    'feel-years-and-months-duration-function_034_c2cc06724c',
    'years and months duration(from:date and time("2014-12-31T23:59:59"),to:date and time("2016-12-31T00:00:01"))',
  ],
  [
    'feel-years-and-months-duration-function_035_dc05f9555d',
    'years and months duration(from:date("2011-12-22"),to:date("2013-08-24"))',
  ],
  [
    'feel-years-and-months-duration-function_036_f8c8b02ba3',
    'years and months duration(from:date("2016-01-21"),to:date("2015-01-21"))',
  ],
];

describe('FEEL TCK / 1121-feel-years-and-months-duration-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001_b24a0c91f2', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_001_b24a0c91f2'])).toBeNull();
  });
  it('002_4e7651ae0e', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_002_4e7651ae0e'])).toBeNull();
  });
  it('003_0886738d31', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_003_0886738d31'])).toBeNull();
  });
  it('004_1bdfef922b', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_004_1bdfef922b'])).toBeNull();
  });
  it('005_d0a077da4e', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_005_d0a077da4e'])).toBeNull();
  });
  it('006_f20de28d3f', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_006_f20de28d3f'])).toBeNull();
  });
  it('007_0921c3d61a', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_007_0921c3d61a'])).toBeNull();
  });
  it('008_015d35b442', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_008_015d35b442']), 'P1Y8M'),
      'feel-years-and-months-duration-function_008_015d35b442',
    ).toBe(true);
  });
  it('009_635028a5d8', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_009_635028a5d8']), '-P1Y8M'),
      'feel-years-and-months-duration-function_009_635028a5d8',
    ).toBe(true);
  });
  it('010_caaa2e5002', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_010_caaa2e5002']), 'P1Y'),
      'feel-years-and-months-duration-function_010_caaa2e5002',
    ).toBe(true);
  });
  it('011_3fac022eb0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_011_3fac022eb0']), '-P1Y'),
      'feel-years-and-months-duration-function_011_3fac022eb0',
    ).toBe(true);
  });
  it('012_331ef38ce0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_012_331ef38ce0']), 'P0Y'),
      'feel-years-and-months-duration-function_012_331ef38ce0',
    ).toBe(true);
  });
  it('013_2f3cc46d9d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_013_2f3cc46d9d']), 'P0Y'),
      'feel-years-and-months-duration-function_013_2f3cc46d9d',
    ).toBe(true);
  });
  it('014_1fadbba7cd', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_014_1fadbba7cd']), 'P1Y2M'),
      'feel-years-and-months-duration-function_014_1fadbba7cd',
    ).toBe(true);
  });
  it('015_0e496f94fc', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_015_0e496f94fc']), 'P7Y6M'),
      'feel-years-and-months-duration-function_015_0e496f94fc',
    ).toBe(true);
  });
  it('016_b38662aa93', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_016_b38662aa93']), 'P4Y9M'),
      'feel-years-and-months-duration-function_016_b38662aa93',
    ).toBe(true);
  });
  it('017_86744b9a54', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_017_86744b9a54']), '-P11M'),
      'feel-years-and-months-duration-function_017_86744b9a54',
    ).toBe(true);
  });
  it('018_8a9ed1d66d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_018_8a9ed1d66d']), '-P4033Y2M'),
      'feel-years-and-months-duration-function_018_8a9ed1d66d',
    ).toBe(true);
  });
  it('019_90c2084588', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_019_90c2084588']), '-P4035Y11M'),
      'feel-years-and-months-duration-function_019_90c2084588',
    ).toBe(true);
  });
  it('020_8ead9a0377', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_020_8ead9a0377']), 'P2Y'),
      'feel-years-and-months-duration-function_020_8ead9a0377',
    ).toBe(true);
  });
  it('021_8a7d311ae9', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_021_8a7d311ae9']), 'P11M'),
      'feel-years-and-months-duration-function_021_8a7d311ae9',
    ).toBe(true);
  });
  it('022_87e369773b', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_022_87e369773b']), 'P5Y7M'),
      'feel-years-and-months-duration-function_022_87e369773b',
    ).toBe(true);
  });
  it('023_6385c7a83e', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_023_6385c7a83e']), 'P1Y'),
      'feel-years-and-months-duration-function_023_6385c7a83e',
    ).toBe(true);
  });
  it('024_e96d1bd93a', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_024_e96d1bd93a']), 'P4Y'),
      'feel-years-and-months-duration-function_024_e96d1bd93a',
    ).toBe(true);
  });
  it('025_161f6fca54', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_025_161f6fca54']), 'P2Y9M'),
      'feel-years-and-months-duration-function_025_161f6fca54',
    ).toBe(true);
  });
  it('026_fcc906b375', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_026_fcc906b375']), 'P3Y'),
      'feel-years-and-months-duration-function_026_fcc906b375',
    ).toBe(true);
  });
  it('027_3374dd86c6', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_027_3374dd86c6'])).toBeNull();
  });
  it('028_77600e7b35', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_028_77600e7b35'])).toBeNull();
  });
  it('029_15a0d0d9c1', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_029_15a0d0d9c1'])).toBeNull();
  });
  it('030_ec16878596', () => {
    const ctx = run({});
    expect(n(ctx['feel-years-and-months-duration-function_ErrorCase_030_ec16878596'])).toBeNull();
  });
  it('031_4fd9c09d89', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_031_4fd9c09d89']), 'P4Y3M'),
      'feel-years-and-months-duration-function_031_4fd9c09d89',
    ).toBe(true);
  });
  it('032_2a09ac80d0', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_032_2a09ac80d0']), 'P2Y4M'),
      'feel-years-and-months-duration-function_032_2a09ac80d0',
    ).toBe(true);
  });
  it('033_7333eca866', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_033_7333eca866']), 'P1Y'),
      'feel-years-and-months-duration-function_033_7333eca866',
    ).toBe(true);
  });
  it('034_c2cc06724c', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_034_c2cc06724c']), 'P2Y'),
      'feel-years-and-months-duration-function_034_c2cc06724c',
    ).toBe(true);
  });
  it('035_dc05f9555d', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_035_dc05f9555d']), 'P1Y8M'),
      'feel-years-and-months-duration-function_035_dc05f9555d',
    ).toBe(true);
  });
  it('036_f8c8b02ba3', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx['feel-years-and-months-duration-function_036_f8c8b02ba3']), '-P1Y'),
      'feel-years-and-months-duration-function_036_f8c8b02ba3',
    ).toBe(true);
  });
});
