// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'non_existing_function()'],
  ['decision002', 'null()'],
  ['decision003', '"some_func"()'],
  ['decision004', '"abs"(-1)'],
  ['decision005', '@"2023-11-11"()'],
  ['decision006', '123()'],
  ['decision007', 'true()'],
  ['decision008', 'false()'],
];

describe('FEEL TCK / 1131-feel-function-invocation', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Non existing function evaluates to null (10.3.2.13.2)', () => {
    const ctx = run({});
    expect(n(ctx.decision001)).toBeNull();
  });
  it('002: null evaluates to null', () => {
    const ctx = run({});
    expect(n(ctx.decision002)).toBeNull();
  });
  it('003: string evaluates to null', () => {
    const ctx = run({});
    expect(n(ctx.decision003)).toBeNull();
  });
  it('004: string (same name function in scope) evaluates to null', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: date evaluates to null', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: number evaluates to null', () => {
    const ctx = run({});
    expect(n(ctx.decision006)).toBeNull();
  });
  it('007: true evaluates to null', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it('008: false evaluates to null', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
});
