// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'string join(["a","b","c"])'],
  ['decision002', 'string join(["a","b","c"], " and ")'],
  ['decision003', 'string join(["a","b","c"], "")'],
  ['decision004', 'string join(["a","b","c"], null)'],
  ['decision005_a', 'string join(["a"])'],
  ['decision005_b', 'string join(["a"], "X")'],
  ['decision006_a', 'string join(["a",null,"c"])'],
  ['decision006_b', 'string join(["a",null,"c"], "X")'],
  ['decision007_a', 'string join([])'],
  ['decision007_b', 'string join([], "X")'],
  ['decision008', 'string join()'],
  ['decision009', 'string join(["a","c"], "X", "foo")'],
  ['decision010_a', 'string join(list: ["a","c"])'],
  ['decision010_b', 'string join(delimiter: "X", list: ["a","c"])'],
  ['decision011_a', 'string join(list: ["a","c"], delimitr: "X")'],
  ['decision011_b', 'string join(lst: ["a","c"], delimiter: "X")'],
  ['decision012_a', 'string join(null)'],
  ['decision012_b', 'string join(null, "X")'],
  ['decision013', 'string join([1,2,3], "X")'],
  ['decision014', 'string join(123, "X")'],
  ['decision015', 'string join("a", "X")'],
  ['decision016', 'string join(list: "a", delimiter: "X")'],
];

describe('FEEL TCK / 1140-feel-string-join-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Will join', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), 'abc'), 'decision001').toBe(true);
  });
  it('002: Will join (with delimiter)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), 'a and b and c'), 'decision002').toBe(true);
  });
  it('003: Will join with empty delimiter', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), 'abc'), 'decision003').toBe(true);
  });
  it('004: Will join with null delimiter', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), 'abc'), 'decision004').toBe(true);
  });
  it('005_a: Will join single element list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005_a), 'a'), 'decision005_a').toBe(true);
  });
  it('005_b: Will join single element list (with delimiter)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005_b), 'a'), 'decision005_b').toBe(true);
  });
  it('006_a: Will ignore null elements in list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006_a), 'ac'), 'decision006_a').toBe(true);
  });
  it('006_b: Will ignore null elements in list (with delimiter)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006_b), 'aXc'), 'decision006_b').toBe(true);
  });
  it('007_a: Will join empty list as ""', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_a), ''), 'decision007_a').toBe(true);
  });
  it('007_b: Will join empty list as "" (with delimiter)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_b), ''), 'decision007_b').toBe(true);
  });
  it('008: No params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('009: Too many params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it('010_a: Join with named param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision010_a), 'ac'), 'decision010_a').toBe(true);
  });
  it('010_b: Join with named params (with delimiter) ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision010_b), 'aXc'), 'decision010_b').toBe(true);
  });
  it('011_a: Incorrect named delimiter param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision011_a)).toBeNull();
  });
  it('011_b: Incorrect named list param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision011_b)).toBeNull();
  });
  it('012_a: null list gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision012_a)).toBeNull();
  });
  it('012_b: null list gives null (with delimiter)', () => {
    const ctx = run({});
    expect(n(ctx.decision012_b)).toBeNull();
  });
  it('013: Incorrect list type gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
  it('014: Non-list non-string list param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision014)).toBeNull();
  });
  it('015: Non-list string list param is coerced to list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision015), 'a'), 'decision015').toBe(true);
  });
  it('016: Non-list string named list param is coerced to list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision016), 'a'), 'decision016').toBe(true);
  });
});
