// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'round half up(5.5, 0)'],
  ['decision002', 'round half up(-5.5, 0)'],
  ['decision003', 'round half up(1.121, 2)'],
  ['decision004', 'round half up(-1.126, 2)'],
  ['decision005', 'round half up()'],
  ['decision007', 'round half up(null,0)'],
  ['decision008', 'round half up(1234,null)'],
  ['decision009', 'round half up(1234.12,1,2)'],
  ['decision010', 'round half up(n:5.5,scale:0)'],
  ['decision011_a', 'round half up(scale:0)'],
  ['decision012', 'round half up(n:5.5,scale:0,foo:123)'],
  ['decision013', 'round half up("123", 0)'],
  ['decision014', 'round half up(5.5, "0")'],
  ['decision016_b', 'round half up(5.5, (-6111 - 1))'],
  ['decision017_a', 'round half up(5.5, 6176)'],
  ['decision017_b', 'round half up(5.5, (6176 + 1))'],
];

describe('FEEL TCK / 1143-feel-round-half-up-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Will round to integer', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), 6), 'decision001').toBe(true);
  });
  it('002: Will round to negative to integer', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), -6), 'decision002').toBe(true);
  });
  it('003: Will round positive to scale', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), 1.12), 'decision003').toBe(true);
  });
  it('004: Will round negative to scale', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), -1.13), 'decision004').toBe(true);
  });
  it('005: No params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('007: null number gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it('008: null scale gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('009: Too many params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it('010: named params', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision010), 6), 'decision010').toBe(true);
  });
  it("011_a: Missing 'n' named param gives null ", () => {
    const ctx = run({});
    expect(n(ctx.decision011_a)).toBeNull();
  });
  it('012: Incorrect named param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it("013: Incorrect 'n' type gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
  it("014: Incorrect 'scale' type gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision014)).toBeNull();
  });
  it('016_b: less than min scale gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision016_b)).toBeNull();
  });
  it('017_a: Max scale is 6176', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision017_a), 5.5), 'decision017_a').toBe(true);
  });
  it('017_b: Greater than max scale gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision017_b)).toBeNull();
  });
});
