// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'context([{key:"a", value:1}, {key:"b", value:2}])'],
  ['decision002', 'context([{key:"a", value:1}])'],
  ['decision003', 'context([{key:"a", value:1},{key:"a", value:2}])'],
  ['decision004', 'context([]) = {}'],
  ['decision005', 'context({key:"a", value:1})'],
  ['decision006', 'context({value:1})'],
  ['decision007', 'context({key: null, value:1})'],
  ['decision008', 'context({key: "a"})'],
  ['decision009', 'context({key: "a", value: null})'],
  ['decision010', 'context({key: "", value: 1})'],
  ['decision011', 'context(null)'],
  ['decision012', 'context()'],
  ['decision013', 'context([], "foo")'],
  ['decision014_a', 'context(entries: [{key:"a", value:1}])'],
  ['decision014_b', 'context(entries: {key:"a", value:1})'],
  ['decision015', 'context(entris: {key:"a", value:1})'],
  ['decision016', 'context("foo")'],
  ['decision017', 'context(entries: [{key:"a", value:1, ignored: "foo"}])'],
];

describe('FEEL TCK / 1145-feel-context-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Will create context from entries', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), { a: 1, b: 2 }), 'decision001').toBe(true);
  });
  it('002: Will create context from single entry', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), { a: 1 }), 'decision002').toBe(true);
  });
  it('003: Will return null when duplicate entry keys', () => {
    const ctx = run({});
    expect(n(ctx.decision003)).toBeNull();
  });
  it('004: Will create empty context for empty entries array', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), true), 'decision004').toBe(true);
  });
  it('005: Will coerce single entry to list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005), { a: 1 }), 'decision005').toBe(true);
  });
  it('006: Will return null when entry is missing key', () => {
    const ctx = run({});
    expect(n(ctx.decision006)).toBeNull();
  });
  it('007: Will return null when entry key value is null', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it('008: Will return null when entry is missing value', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('009: Will permit null value', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009), { a: null }), 'decision009').toBe(true);
  });
  it('010: Will permit empty string as key', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision010), { '': 1 }), 'decision010').toBe(true);
  });
  it('011: Null entries list gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision011)).toBeNull();
  });
  it('012: Too few params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('013: Too many params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('014_a: named params', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision014_a), { a: 1 }), 'decision014_a').toBe(true);
  });
  it('014_b: will coerce non-list named param to list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision014_b), { a: 1 }), 'decision014_b').toBe(true);
  });
  it('015: Incorrect named param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision015)).toBeNull();
  });
  it("016: Incorrect 'entries' type gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision016)).toBeNull();
  });
  it("017: Will ignore extra fields beyond 'key' and 'value'", () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision017), { a: 1 }), 'decision017').toBe(true);
  });
});
