// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'context put({}, "a", 1)'],
  ['decision002', 'get entries(context put({"a": 1}, "b", 2))'],
  ['decision003', 'context put({"a": 1}, "a", 2)'],
  ['decision003_a', 'context put({"a":1, "b":2, "c":3 }, "b", 3)'],
  ['decision004', 'context put({}, "", 1)'],
  ['decision005', 'context put({}, null, 1)'],
  ['decision006', 'context put(null, "a", 1)'],
  ['decision007', 'context put({}, "a", null)'],
  ['decision008', 'context put({}, "a")'],
  ['decision009', 'context put({}, "a", 1, 1)'],
  ['decision010', 'context put(context: {}, key: "a", value: 1)'],
  ['decision011', 'context put(context: {}, ky: "a", value: 1)'],
  ['decision012', 'context put([], "a", 1)'],
  ['decision013', 'context put({}, 1, 1)'],
  ['decision014', 'context put(context01, "a", 2)'],
  ['nested001', 'context put({x:1, y: {a: 0} }, ["y", "a"], 2)'],
  ['nested001_a', 'context put({x:1, y: {a: 0} }, ["y", "b"], 2)'],
  ['nested002', 'context put({x:1, y: {a: 0} }, ["y", null], 2)'],
  ['nested003', 'context put({x:1, y: {a: 0} }, [null, "a"], 2)'],
  ['nested004', 'context put({x:1, y: {a: 0} }, [null], 2)'],
  ['nested005', 'context put({x:1, y: {a: 0} }, [], 2)'],
  ['nested006', 'context put({x:1, y: {a: {b: {c: 1}} }}, ["y", "a", "b", "c"], 2)'],
  ['nested007', 'context put(context: {x:1, y: {a: 0} }, keys: ["y", "a"], value: 2)'],
  ['nested008', 'context put(context: {x:1, y: {a: 0} }, key: ["y", "a"], value: 2)'],
  ['nested009', 'context put({x:1, y: {a: 0}}, ["y", "a", "b", "c"], 2)'],
  ['nested010', 'context put(nestedContext01, ["a", "b"], 2)'],
];

describe('FEEL TCK / 1146-feel-context-put-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Will add context entry', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), { a: 1 }), 'decision001').toBe(true);
  });
  it('002: Will add entry to end of context', () => {
    const ctx = run({});
    expect(
      aeq(n(ctx.decision002), [
        { key: 'a', value: 1 },
        { key: 'b', value: 2 },
      ]),
      'decision002',
    ).toBe(true);
  });
  it('003: Will overwrite existing context entry', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), { a: 2 }), 'decision003').toBe(true);
  });
  it('003_a: Will maintain key order when overwriting existing context entry', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_a), { a: 1, b: 3, c: 3 }), 'decision003_a').toBe(true);
  });
  it('004: Will permit empty key param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), { '': 1 }), 'decision004').toBe(true);
  });
  it('005: Null key param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: Null context param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision006)).toBeNull();
  });
  it('007: Will permit null value param', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007), { a: null }), 'decision007').toBe(true);
  });
  it('008: Too few params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision008)).toBeNull();
  });
  it('009: Too many params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it('010: named params', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision010), { a: 1 }), 'decision010').toBe(true);
  });
  it('011: Incorrect named param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision011)).toBeNull();
  });
  it("012: Incorrect 'context' type gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('013: Will return null when key is not a string', () => {
    const ctx = run({});
    expect(n(ctx.decision013)).toBeNull();
  });
  it('nested001: will overwrite value in nested context', () => {
    const ctx = run({});
    expect(aeq(n(ctx.nested001), { x: 1, y: { a: 2 } }), 'nested001').toBe(true);
  });
  it('nested001_a: will add value to nested context', () => {
    const ctx = run({});
    expect(aeq(n(ctx.nested001_a), { x: 1, y: { a: 0, b: 2 } }), 'nested001_a').toBe(true);
  });
  it('nested002: null key gives null (1)', () => {
    const ctx = run({});
    expect(n(ctx.nested002)).toBeNull();
  });
  it('nested003: null key gives null (2)', () => {
    const ctx = run({});
    expect(n(ctx.nested003)).toBeNull();
  });
  it('nested004: null key gives null (3)', () => {
    const ctx = run({});
    expect(n(ctx.nested004)).toBeNull();
  });
  it('nested005: empty keys array gives null', () => {
    const ctx = run({});
    expect(n(ctx.nested005)).toBeNull();
  });
  it('nested006: will recurse into nested contexts', () => {
    const ctx = run({});
    expect(aeq(n(ctx.nested006), { x: 1, y: { a: { b: { c: 2 } } } }), 'nested006').toBe(true);
  });
  it("nested007: named params - with 'keys'", () => {
    const ctx = run({});
    expect(aeq(n(ctx.nested007), { x: 1, y: { a: 2 } }), 'nested007').toBe(true);
  });
  it("nested008: named params - array value for 'key' gives null", () => {
    const ctx = run({});
    expect(n(ctx.nested008)).toBeNull();
  });
  it("nested009: named params - array value for 'key' gives null", () => {
    const ctx = run({});
    expect(n(ctx.nested009)).toBeNull();
  });
});
