// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'context merge([{"a": 1}])'],
  ['decision001_a', 'context merge([{}]) = {}'],
  ['decision002', 'context merge([{"a": 1}, {"b": 2}])'],
  ['decision003', 'context merge([{"a": 1}, {"a": 2}])'],
  ['decision004', 'context merge([{"a": {"aa": 1}}, {"a": {"bb": 2}}])'],
  ['decision005', 'context merge(null)'],
  ['decision006', 'context merge()'],
  ['decision007', 'context merge([],"foo")'],
  ['decision008', 'context merge(contexts: [{"a": 1}])'],
  ['decision009', 'context merge(context: [{"a": 1}])'],
  ['decision010', 'context merge([1,2,3])'],
  ['decision011', 'context merge([{"a": 1},2,{"b": 2}])'],
  ['decision012', 'context merge({"a": 1})'],
  ['decision013', 'context merge(contexts: {"a": 1})'],
];

describe('FEEL TCK / 1147-feel-context-merge-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Will merge a context', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), { a: 1 }), 'decision001').toBe(true);
  });
  it('001_a: Will merge empty context', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_a), true), 'decision001_a').toBe(true);
  });
  it('002: Will merge multiple contexts', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), { a: 1, b: 2 }), 'decision002').toBe(true);
  });
  it('003: Will overwrite existing context entry', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003), { a: 2 }), 'decision003').toBe(true);
  });
  it('004: Will overwrite (not merge) nested contexts', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision004), { a: { bb: 2 } }), 'decision004').toBe(true);
  });
  it('005: Null contexts param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: Too few params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision006)).toBeNull();
  });
  it('007: Too many params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it('008: named params', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008), { a: 1 }), 'decision008').toBe(true);
  });
  it('009: Incorrect named param gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision009)).toBeNull();
  });
  it("010: Incorrect 'contexts' type gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision010)).toBeNull();
  });
  it("011: Non-context entry in 'contexts' gives null", () => {
    const ctx = run({});
    expect(n(ctx.decision011)).toBeNull();
  });
  it('012: Will coerce single context to list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision012), { a: 1 }), 'decision012').toBe(true);
  });
  it('013: Will coerce single name param entry to list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision013), { a: 1 }), 'decision013').toBe(true);
  });
});
