// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'now() instance of date and time'],
  ['decision002', 'now(123)'],
];

describe('FEEL TCK / 1148-feel-now-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Will give date and time', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), true), 'decision001').toBe(true);
  });
  it('002: Too many params gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision002)).toBeNull();
  });
});
