// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', 'list replace([1,2,3], 2, 4)'],
  ['decision002', 'list replace([1,2,3], -1, 4)'],
  ['decision003', 'list replace([1,2,3], 0, 4)'],
  ['decision004', 'list replace([1,2,3], 4, 4)'],
  ['decision005', 'list replace([1,2,3], -4, 4)'],
  ['decision006', 'list replace(null, 1, 4)'],
  ['decision007', 'list replace([1,2,3], null, 4)'],
  ['decision008', 'list replace([1,2,3], 3, null)'],
  ['decision009', 'list replace ( [2, 4, 7, 8], function(item, newItem) item < newItem, 5)'],
  ['decision010', 'list replace([1,2,3], "2", 4)'],
  ['decision011', 'list replace([1,2,3], 2.5, 4)'],
  ['decision011_a', 'list replace([1,2,3], -1.5, 4)'],
  ['decision012', 'list replace(position: 2, newItem: 4, list: [1,2,3])'],
  [
    'decision013',
    'list replace(match: function(item, newItem) item = 2, newItem: 4, list: [1,2,3])',
  ],
  ['decision014', 'list replace([1,2,3], "2", 4, 4)'],
  ['decision015', 'list replace([1,2,3], "2")'],
  ['decision016', 'list replace(position: 2, newItem: 4, list: [1,2,3], foo: 1)'],
  ['decision017', 'list replace ( [2, 4], function(item, newItem, extraParam) item = 2, 5)'],
  ['decision018', 'list replace ( [2, 4], function(item) item = 2, 5)'],
  ['decision019', 'list replace ( [2, 4], function(item, newItem) item, 5)'],
  ['decision020', 'list replace ( [1, 2, 3, 4], function(item, newItem) true, 5)'],
  ['decision021', 'list replace ( 1, 1, 5)'],
];

describe('FEEL TCK / 1155-list-replace-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Replace element in list at 1-based position', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), [1, 4, 3]), 'decision001').toBe(true);
  });
  it('002: Replace last element in list using negative position', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), [1, 2, 4]), 'decision002').toBe(true);
  });
  it('003: A position of zero gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision003)).toBeNull();
  });
  it('004: A positive position outside the list bounds gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision004)).toBeNull();
  });
  it('005: A negative position outside the list bounds gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision005)).toBeNull();
  });
  it('006: list value may not be null', () => {
    const ctx = run({});
    expect(n(ctx.decision006)).toBeNull();
  });
  it('007: position value may not be null', () => {
    const ctx = run({});
    expect(n(ctx.decision007)).toBeNull();
  });
  it('008: newItem value may be null', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008), [1, 2, null]), 'decision008').toBe(true);
  });
  it('009: match function returning true will replace items', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009), [5, 5, 7, 8]), 'decision009').toBe(true);
  });
  it('010: position must be a number', () => {
    const ctx = run({});
    expect(n(ctx.decision010)).toBeNull();
  });
  it('011: position will be truncated to integer', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011), [1, 4, 3]), 'decision011').toBe(true);
  });
  it('011_a: negative position will be truncated to integer', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011_a), [1, 2, 4]), 'decision011_a').toBe(true);
  });
  it("012: named arguments ('position') ", () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision012), [1, 4, 3]), 'decision012').toBe(true);
  });
  it("013: named arguments ('match') ", () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision013), [1, 4, 3]), 'decision013').toBe(true);
  });
  it('014: too many arguments gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision014)).toBeNull();
  });
  it('015: too few arguments gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision015)).toBeNull();
  });
  it('016: unknown named argument gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision016)).toBeNull();
  });
  it('017: invalid match function signature (too many arguments) gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision017)).toBeNull();
  });
  it('018: invalid match function signature (too few arguments) gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision018)).toBeNull();
  });
  it('019: match function must return boolean value', () => {
    const ctx = run({});
    expect(n(ctx.decision019)).toBeNull();
  });
  it('020: match function will be called for every list item', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision020), [5, 5, 5, 5]), 'decision020').toBe(true);
  });
  it('021: will coerce to singleton list', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision021), [5]), 'decision021').toBe(true);
  });
});
