// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../../src/index.js';
import { aeq, type Ctx, n } from '../utils.js';

// Decisions evaluated in dependency order for every test case
const CHAIN: [string, string][] = [
  ['decision001', '2 in range("[1..3]")'],
  ['decision001_a', 'range("[1..3]") instance of range<number>'],
  ['decision001_b', 'range(string("[1..3]")) instance of range<number>'],
  ['decision001_c', 'range("[\\"a\\"..\\"c\\"]") instance of range<string>'],
  ['decision001_d', 'range("[@\\"1970-01-01\\"..@\\"1970-01-02\\"]") instance of range<date>'],
  [
    'decision001_e',
    'range("[@\\"1970-01-01T00:00:00\\"..@\\"1970-01-02T00:00:00\\"]") instance of range<date and time>',
  ],
  ['decision001_g', 'range("[@\\"00:00:00\\"..@\\"00:00:00\\"]") instance of range<time>'],
  ['decision001_h', 'range("[@\\"P1D\\"..@\\"P2D\\"]") instance of range<days and time duration>'],
  [
    'decision001_i',
    'range("[@\\"P1Y\\"..@\\"P2Y\\"]") instance of range<years and months duration>',
  ],
  ['decision002', '2 in range(string("[1..3]"))'],
  ['decision003_a', 'range("[18..21]") = [18..21]'],
  ['decision003_b', 'range("(18..21]") = (18..21]'],
  ['decision003_c', 'range("]18..21]") = ]18..21]'],
  ['decision003_d', 'range("[18..21)") = [18..21)'],
  ['decision003_e', 'range("[18..21[") = [18..21['],
  ['decision004_e', 'range("[..2]")'],
  ['decision004_f', 'range("[1..]")'],
  ['decision005_a', 'range("[\\"a\\"..\\"c\\"]") = ["a".."c"]'],
  [
    'decision005_b',
    'range("[@\\"1970-01-01\\"..@\\"1970-01-02\\"]") = [@"1970-01-01"..@"1970-01-02"]',
  ],
  [
    'decision005_c',
    'range("[@\\"1970-01-01T00:00:00\\"..@\\"1970-01-02T00:00:00\\"]") =\n                [@"1970-01-01T00:00:00"..@"1970-01-02T00:00:00"]',
  ],
  ['decision005_d', 'range("[@\\"00:00:00\\"..@\\"00:00:00\\"]") = [@"00:00:00"..@"00:00:00"]'],
  ['decision005_e', 'range("[@\\"P1D\\"..@\\"P2D\\"]") = [@"P1D"..@"P2D"]'],
  ['decision005_f', 'range("[@\\"P1Y\\"..@\\"P2Y\\"]") = [@"P1Y"..@"P2Y"]'],
  ['decision006', 'range(" [ 1 .. 3 ] ") = [1..3]'],
  [
    'decision007_a',
    'range("[date(\\"1970-01-01\\")..date(\\"1970-01-02\\")]") = [date("1970-01-01")..date("1970-01-02")]',
  ],
  ['decision007_b', 'range("[date(string(\\"1970-01-01\\"))..date(\\"1970-01-02\\")]")'],
  ['decision007_c', 'range("[date(input_001)..date(\\"1970-01-02\\")]")'],
  [
    'decision008_a',
    'range("[date and time(\\"1970-01-01T00:00:00\\")..@\\"1970-01-02T00:00:00\\"]") =\n                [@"1970-01-01T00:00:00"..@"1970-01-02T00:00:00"]',
  ],
  [
    'decision008_b',
    'range("[date and time(string(\\"1970-01-01T00:00:00\\"))..@\\"1970-01-02T00:00:00\\"]")',
  ],
  ['decision008_c', 'range("[date and time(input_001)..@\\"1970-01-02T00:00:00\\"]")'],
  [
    'decision009_a',
    'range("[time(\\"00:00:00\\")..@\\"00:00:00\\"]") = [@"00:00:00"..@"00:00:00"]',
  ],
  ['decision009_b', 'range("[time(string(\\"00:00:00\\"))..@\\"00:00:00\\"]")'],
  ['decision009_c', 'range("[time(input_001)..@\\"00:00:00\\"]")'],
  ['decision010_a', 'range("[duration(\\"P1D\\")..@\\"P2D\\"]") = [@"P1D"..@"P2D"]'],
  ['decision010_b', 'range("[duration(string(\\"P1D\\"))..@\\"P2D\\"]")'],
  ['decision010_c', 'range("[duration(input_001)..@\\"P2D\\"]")'],
  ['decision011', 'range(from: "[1..3]") = [1..3]'],
  ['decision012', 'range(fron: "[1..3]")'],
  ['decision013_a', 'range("[1..3]", "foo")'],
  ['decision013_b', 'range()'],
  ['decision014', 'range([1..3])'],
  ['decision015_a', 'range("")'],
  ['decision015_b', 'range(" ")'],
  ['decision016', 'range(string(""))'],
  ['decision017', 'range(">=10")'],
  ['decision018', 'range("[1..\\"b\\"]")'],
  ['decision019_a', 'range("[@\\"1970-01-01\\"..@\\"1970-01-02T00:00:00\\"]")'],
  ['decision019_b', 'range("[@\\"1970-01-01T00:00:00\\"..@\\"1970-01-02\\"]")'],
  ['decision020', 'range("[3..1]")'],
  ['decision021', 'range("[@\\"1970-01-02\\"..@\\"1970-01-01\\"]")'],
  ['decision022', 'range("[@\\"1970-01-02T00:00:00\\"..@\\"1970-01-01T00:00:00\\"]")'],
  ['decision023', 'range("[\\"z\\"..\\"a\\"]")'],
  ['decision024', 'range("[@\\"P2D\\"..@\\"P1D\\"]")'],
  ['decision025', 'range("[@\\"P2Y\\"..@\\"P1Y\\"]")'],
  ['decision026', 'range("[@\\"02:00:00\\"..@\\"01:00:00\\"]")'],
  ['decision027', 'range("[null..null]")'],
];

describe('FEEL TCK / 1156-range-function', () => {
  function run(inputs: Ctx): Ctx {
    const ctx: Ctx = { ...inputs };
    for (const [name, expr] of CHAIN) ctx[name] = evaluate(expr, ctx).value;
    return ctx;
  }

  it('001: Sanity check something is in range', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001), true), 'decision001').toBe(true);
  });
  it('001_a: range(number) instance of range<number>', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_a), true), 'decision001_a').toBe(true);
  });
  it('001_b: range(number) instance of range<number>', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_b), true), 'decision001_b').toBe(true);
  });
  it('001_c: range(string) instance of range<string>', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_c), true), 'decision001_c').toBe(true);
  });
  it('001_d: range(date) instance of range<date>', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_d), true), 'decision001_d').toBe(true);
  });
  it('001_e: range(date and time) instance of range<date and time>', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_e), true), 'decision001_e').toBe(true);
  });
  it('001_g: range(time) instance of range<time>', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_g), true), 'decision001_g').toBe(true);
  });
  it('001_h: range(days and time duration) instance of range<days and time duration>', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_h), true), 'decision001_h').toBe(true);
  });
  it('001_i: range(years and months duration) instance of range<years and months duration>', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision001_i), true), 'decision001_i').toBe(true);
  });
  it('002: sanity check using a non-literal string expression ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision002), true), 'decision002').toBe(true);
  });
  it('003_a: range() function result equals FEEL range: [..]', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_a), true), 'decision003_a').toBe(true);
  });
  it('003_b: range() function result equals FEEL range: (..]', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_b), true), 'decision003_b').toBe(true);
  });
  it('003_c: range() function result equals FEEL range: ]..]', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_c), true), 'decision003_c').toBe(true);
  });
  it('003_d: range() function result equals FEEL range: [..)', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_d), true), 'decision003_d').toBe(true);
  });
  it('003_e: range() function result equals FEEL range: [..[', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision003_e), true), 'decision003_e').toBe(true);
  });
  it('004_e: closed start endpoint with no value is not valid and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision004_e)).toBeNull();
  });
  it('004_f: closed end endpoint with no value is not valid and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision004_f)).toBeNull();
  });
  it('005_a: range(string) function equals a unary FEEL range: string ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005_a), true), 'decision005_a').toBe(true);
  });
  it('005_b: range(date) function equals a unary FEEL range: date ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005_b), true), 'decision005_b').toBe(true);
  });
  it('005_c: range(date and time) function equals a unary FEEL range: date and time ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005_c), true), 'decision005_c').toBe(true);
  });
  it('005_d: range(time) function equals a unary FEEL range: time ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005_d), true), 'decision005_d').toBe(true);
  });
  it('005_e: range(days and time duration) function equals a unary FEEL range: days and time duration ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005_e), true), 'decision005_e').toBe(true);
  });
  it('005_f: range(years and months duration) function equals a unary FEEL range: years and months duration ', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision005_f), true), 'decision005_f').toBe(true);
  });
  it('006: will ignore whitespace when parsing', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision006), true), 'decision006').toBe(true);
  });
  it('007_a: use of date() function literal is permitted', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision007_a), true), 'decision007_a').toBe(true);
  });
  it('007_b: use of date() function as non literal is not permitted and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision007_b)).toBeNull();
  });
  it('007_c: use of date() function as non literal is not permitted and gives null', () => {
    const ctx = run({ input_001: '1970-01-01' });
    expect(n(ctx.decision007_c)).toBeNull();
  });
  it('008_a: use of date and time() function literal is permitted', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision008_a), true), 'decision008_a').toBe(true);
  });
  it('008_b: use of date and time() function as non literal is not permitted and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision008_b)).toBeNull();
  });
  it('008_c: use of date and time() function as non literal is not permitted and gives null', () => {
    const ctx = run({ input_001: '1970-01-01T00:00:00' });
    expect(n(ctx.decision008_c)).toBeNull();
  });
  it('009_a: use of time() function literal is permitted', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision009_a), true), 'decision009_a').toBe(true);
  });
  it('009_b: use of time() function as non literal is not permitted and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision009_b)).toBeNull();
  });
  it('009_c: use of time() function as non literal is not permitted and gives null', () => {
    const ctx = run({ input_001: '00:00:00' });
    expect(n(ctx.decision009_c)).toBeNull();
  });
  it('010_a: use of duration() function literal is permitted', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision010_a), true), 'decision010_a').toBe(true);
  });
  it('010_b: use of duration() function as non literal is not permitted and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision010_b)).toBeNull();
  });
  it('010_c: use of duration() function as non literal is not permitted and gives null', () => {
    const ctx = run({ input_001: 'P1D' });
    expect(n(ctx.decision010_c)).toBeNull();
  });
  it('011: named argument', () => {
    const ctx = run({});
    expect(aeq(n(ctx.decision011), true), 'decision011').toBe(true);
  });
  it('012: invalidly named argument gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision012)).toBeNull();
  });
  it('013_a: too many arguments gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision013_a)).toBeNull();
  });
  it('013_b: too few arguments gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision013_b)).toBeNull();
  });
  it('014: invalid argument type gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision014)).toBeNull();
  });
  it('015_a: empty string gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision015_a)).toBeNull();
  });
  it('015_b: whitespace only gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision015_b)).toBeNull();
  });
  it('016: non-literal argument providing invalid range string gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision016)).toBeNull();
  });
  it('017: a unary range is not a valid literal range string and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision017)).toBeNull();
  });
  it('018: mismatching endpoint types gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision018)).toBeNull();
  });
  it('019_a: date and date and time end points are not equivalent and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision019_a)).toBeNull();
  });
  it('019_b: date and date and time end points are not equivalent and gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision019_b)).toBeNull();
  });
  it('020: descending numeric range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision020)).toBeNull();
  });
  it('021: descending date range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision021)).toBeNull();
  });
  it('022: descending date time range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision022)).toBeNull();
  });
  it('023: descending string range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision023)).toBeNull();
  });
  it('024: descending date duration range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision024)).toBeNull();
  });
  it('025: descending year duration range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision025)).toBeNull();
  });
  it('026: descending time range gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision026)).toBeNull();
  });
  it('027: both null endpoints gives null', () => {
    const ctx = run({});
    expect(n(ctx.decision027)).toBeNull();
  });
});
