// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-functions / feel-functions/string', () => {
  describe('fn-contains', () => {
    const EXPR = 'contains(s, match)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'ob' }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'xyz' }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: '' }).value)).toEqual(true);
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: '', match: '' }).value)).toEqual(true);
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foo' }).value)).toEqual(true);
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'bar' }).value)).toEqual(true);
    });
    it('case 7', () => {
      expect(n(evaluate(EXPR, { s: 'hello', match: 'HELLO' }).value)).toEqual(false);
    });
  });
  describe('fn-ends-with', () => {
    const EXPR = 'ends with(s, match)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'bar' }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foo' }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: '' }).value)).toEqual(true);
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foobar' }).value)).toEqual(true);
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foobarbaz' }).value)).toEqual(false);
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: '', match: '' }).value)).toEqual(true);
    });
  });
  describe('fn-lower-case', () => {
    const EXPR = 'lower case(s)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'HELLO' }).value)).toEqual('hello');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'Hello World' }).value)).toEqual('hello world');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: '' }).value)).toEqual('');
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'hello' }).value)).toEqual('hello');
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'ABC123' }).value)).toEqual('abc123');
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'FOO BAR' }).value)).toEqual('foo bar');
    });
  });
  describe('fn-matches-flags', () => {
    const EXPR =
      '{\n  case_sensitive_no_match: matches("ABC", "abc"),\n  case_insensitive: matches("ABC", "abc", "i"),\n  case_insensitive_partial: matches("Hello World", "hello", "i"),\n  multiline_no_flag: matches("line1\\nline2", "^line2"),\n  multiline_with_flag: matches("line1\\nline2", "^line2", "m"),\n  dotall_no_flag: matches("line1\\nline2", "line1.line2"),\n  dotall_with_flag: matches("line1\\nline2", "line1.line2", "s"),\n  combined_flags: matches("HELLO\\nWORLD", "^world$", "im"),\n  extended_whitespace: matches("hello", "he l l o", "x"),\n  no_match_returns_false: matches("hello", "xyz", "i")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        case_sensitive_no_match: false,
        case_insensitive: true,
        case_insensitive_partial: true,
        multiline_no_flag: false,
        multiline_with_flag: true,
        dotall_no_flag: false,
        dotall_with_flag: true,
        combined_flags: true,
        extended_whitespace: true,
        no_match_returns_false: false,
      });
    });
  });
  describe('fn-matches', () => {
    const EXPR = 'matches(s, pattern)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', pattern: 'fo+' }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', pattern: '^foo' }).value)).toEqual(true);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', pattern: 'xyz' }).value)).toEqual(false);
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: '12345', pattern: '\\d+' }).value)).toEqual(true);
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'hello', pattern: '^hello$' }).value)).toEqual(true);
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'hello', pattern: '^world$' }).value)).toEqual(false);
    });
    it('case 7', () => {
      expect(n(evaluate(EXPR, { s: 'abc123', pattern: '[a-z]+' }).value)).toEqual(true);
    });
  });
  describe('fn-named-params', () => {
    const EXPR =
      '{\n  substring_named: substring(string: "hello world", start position: 7),\n  substring_len_named: substring(string: "hello world", start position: 1, length: 5),\n  contains_named: contains(string: "hello world", match: "world"),\n  starts_with_named: starts with(string: "hello world", match: "hello"),\n  ends_with_named: ends with(string: "hello world", match: "world"),\n  replace_named: replace(input: "hello world", pattern: "world", replacement: "FEEL"),\n  matches_named: matches(input: "hello world", pattern: ".*world.*"),\n  split_named: split(string: "a,b,c", delimiter: ","),\n  upper_named: upper case(string: "hello"),\n  lower_named: lower case(string: "HELLO")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        substring_named: 'world',
        substring_len_named: 'hello',
        contains_named: true,
        starts_with_named: true,
        ends_with_named: true,
        replace_named: 'hello FEEL',
        matches_named: true,
        split_named: ['a', 'b', 'c'],
        upper_named: 'HELLO',
        lower_named: 'hello',
      });
    });
  });
  describe('fn-replace-backreference', () => {
    const EXPR =
      '{\n  capture_group_1: replace("hello world", "(world)", "[$1]"),\n  capture_group_swap: replace("John Smith", "(\\w+) (\\w+)", "$2, $1"),\n  capture_group_double: replace("abc", "(a)(b)(c)", "$3$2$1"),\n  no_capture: replace("hello", "l+", "L"),\n  case_insensitive_replace: replace("Hello WORLD", "world", "FEEL", "i"),\n  global_replace: replace("aababab", "a", "X"),\n  empty_match: replace("abc", "b*", "X"),\n  digits_replace: replace("phone: 123-456-7890", "\\d", "X")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        capture_group_1: 'hello [world]',
        capture_group_swap: 'Smith, John',
        capture_group_double: 'cba',
        no_capture: 'heLo',
        case_insensitive_replace: 'Hello FEEL',
        global_replace: 'XXbXbXb',
        empty_match: null,
        digits_replace: 'phone: XXX-XXX-XXXX',
      });
    });
  });
  describe('fn-replace-regex-groups', () => {
    const EXPR =
      '{\n  simple: replace("hello world", "world", "FEEL"),\n  global: replace("aaa", "a", "b"),\n  capture_group: replace("John Smith", "(\\w+)\\s(\\w+)", "$2, $1"),\n  remove_spaces: replace("a b c", "\\s+", ""),\n  no_match: replace("hello", "xyz", "ABC"),\n  null_input: replace(null, "x", "y"),\n  case_insensitive: replace("Hello WORLD", "hello", "hi", "i")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        simple: 'hello FEEL',
        global: 'bbb',
        capture_group: 'Smith, John',
        remove_spaces: 'abc',
        no_match: 'hello',
        null_input: null,
        case_insensitive: 'hi WORLD',
      });
    });
  });
  describe('fn-replace', () => {
    const EXPR = 'replace(s, pattern, replacement)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'hello', pattern: 'l', replacement: 'r' }).value)).toEqual(
        'herro',
      );
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'abc', pattern: 'b', replacement: 'X' }).value)).toEqual('aXc');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'aaa', pattern: 'a', replacement: 'b' }).value)).toEqual('bbb');
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', pattern: 'o+', replacement: '0' }).value)).toEqual(
        'f0bar',
      );
    });
    it('case 5', () => {
      expect(
        n(evaluate(EXPR, { s: 'hello world', pattern: '\\s', replacement: '_' }).value),
      ).toEqual('hello_world');
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'abc', pattern: 'xyz', replacement: 'Z' }).value)).toEqual(
        'abc',
      );
    });
  });
  describe('fn-split', () => {
    const EXPR = 'split(s, delimiter)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'a,b,c', delimiter: ',' }).value)).toEqual(['a', 'b', 'c']);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'one;two;three', delimiter: ';' }).value)).toEqual([
        'one',
        'two',
        'three',
      ]);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'hello', delimiter: 'l' }).value)).toEqual(['he', '', 'o']);
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'abc', delimiter: 'x' }).value)).toEqual(['abc']);
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'a b c', delimiter: '\\s' }).value)).toEqual(['a', 'b', 'c']);
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'foo', delimiter: 'foo' }).value)).toEqual(['', '']);
    });
  });
  describe('fn-starts-with', () => {
    const EXPR = 'starts with(s, match)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foo' }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'bar' }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: '' }).value)).toEqual(true);
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foobar' }).value)).toEqual(true);
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foobarbaz' }).value)).toEqual(false);
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: '', match: '' }).value)).toEqual(true);
    });
  });
  describe('fn-string-join', () => {
    const EXPR =
      '{\n  single_arg: string join(["a", "b", "c"]),\n  with_delimiter: string join(["a", "b", "c"], ","),\n  with_space: string join(["hello", "world"], " "),\n  empty_list: string join([]),\n  empty_delimiter: string join(["a", "b", "c"], ""),\n  single_element: string join(["only"], ","),\n  with_nulls: string join(["a", null, "c"], "-"),\n  four_arg: string join(["a", "b", "c"], ",", "[", "]"),\n  four_arg_empty: string join([], ",", "[", "]"),\n  named_params: string join(list: ["x", "y"], delimiter: "+"),\n  named_full: string join(list: ["a", "b"], delimiter: ",", prefix: "<", suffix: ">")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        single_arg: 'abc',
        with_delimiter: 'a,b,c',
        with_space: 'hello world',
        empty_list: '',
        empty_delimiter: 'abc',
        single_element: 'only',
        with_nulls: 'a-c',
        four_arg: '[a,b,c]',
        four_arg_empty: '[]',
        named_params: 'x+y',
        named_full: '<a,b>',
      });
    });
  });
  describe('fn-string-length-edge', () => {
    const EXPR =
      '{\n  empty: string length(""),\n  single: string length("a"),\n  spaces: string length("   "),\n  unicode_emoji: string length("😀"),\n  unicode_accented: string length("café"),\n  null_input: string length(null),\n  newline: string length("\\n"),\n  long_string: string length("hello world!")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        empty: 0,
        single: 1,
        spaces: 3,
        unicode_emoji: 1,
        unicode_accented: 4,
        null_input: null,
        newline: 1,
        long_string: 12,
      });
    });
  });
  describe('fn-string-length', () => {
    const EXPR = 'string length(s)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'hello' }).value)).toEqual(5);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: '' }).value)).toEqual(0);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'ABC' }).value)).toEqual(3);
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: null }).value)).toEqual(null);
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'a' }).value)).toEqual(1);
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'Hello World' }).value)).toEqual(11);
    });
  });
  describe('fn-string-type-coerce', () => {
    const EXPR =
      '{\n  from_number: string(42),\n  from_float: string(3.14),\n  from_bool_true: string(true),\n  from_bool_false: string(false),\n  from_null: string(null),\n  from_date: string(@"2024-01-15"),\n  from_duration: string(duration("P1Y2M")),\n  from_dt_duration: string(duration("P1DT2H3M"))\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        from_number: '42',
        from_float: '3.14',
        from_bool_true: 'true',
        from_bool_false: 'false',
        from_null: null,
        from_date: '2024-01-15',
        from_duration: 'P1Y2M',
        from_dt_duration: 'P1DT2H3M',
      });
    });
  });
  describe('fn-string', () => {
    const EXPR = 'string(from)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { from: 1.1 }).value)).toEqual('1.1');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { from: true }).value)).toEqual('true');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { from: null }).value)).toEqual(null);
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { from: 'abc' }).value)).toEqual('abc');
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { from: [1, 2] }).value)).toEqual('[1, 2]');
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { from: 0 }).value)).toEqual('0');
    });
    it('case 7', () => {
      expect(n(evaluate(EXPR, { from: false }).value)).toEqual('false');
    });
  });
  describe('fn-substring-after', () => {
    const EXPR = 'substring after(s, match)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foo' }).value)).toEqual('bar');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'xyz' }).value)).toEqual('');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'bar' }).value)).toEqual('');
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'o' }).value)).toEqual('obar');
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'hello world', match: ' ' }).value)).toEqual('world');
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'abcabc', match: 'b' }).value)).toEqual('cabc');
    });
  });
  describe('fn-substring-before', () => {
    const EXPR = 'substring before(s, match)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'bar' }).value)).toEqual('foo');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'xyz' }).value)).toEqual('');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'foo' }).value)).toEqual('');
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'foobar', match: 'o' }).value)).toEqual('f');
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'hello world', match: ' ' }).value)).toEqual('hello');
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'abcabc', match: 'b' }).value)).toEqual('a');
    });
  });
  describe('fn-substring-boundary', () => {
    const EXPR =
      '{\n  from_start: substring("abcdef", 1),\n  from_second: substring("abcdef", 2),\n  negative_index: substring("abcdef", -3),\n  negative_with_length: substring("abcdef", -3, 2),\n  full_length: substring("abcdef", 1, 6),\n  beyond_end: substring("abcdef", 1, 100),\n  last_char: substring("abcdef", 6, 1),\n  null_string: substring(null, 1)\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        from_start: 'abcdef',
        from_second: 'bcdef',
        negative_index: 'def',
        negative_with_length: 'de',
        full_length: 'abcdef',
        beyond_end: 'abcdef',
        last_char: 'f',
        null_string: null,
      });
    });
  });
  describe('fn-substring-length', () => {
    const EXPR = 'substring(s, start, len)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: 2, len: 3 }).value)).toEqual('ell');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: 1, len: 2 }).value)).toEqual('he');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: 2, len: 0 }).value)).toEqual('');
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: 1, len: 5 }).value)).toEqual('hello');
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'abcdef', start: 3, len: 3 }).value)).toEqual('cde');
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: -3, len: 2 }).value)).toEqual('ll');
    });
  });
  describe('fn-substring', () => {
    const EXPR = 'substring(s, start)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: 2 }).value)).toEqual('ello');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: -2 }).value)).toEqual('lo');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'abc', start: 1 }).value)).toEqual('abc');
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: '', start: 1 }).value)).toEqual('');
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: 1 }).value)).toEqual('hello');
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'hello', start: 5 }).value)).toEqual('o');
    });
  });
  describe('fn-upper-case', () => {
    const EXPR = 'upper case(s)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'hello' }).value)).toEqual('HELLO');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'HELLO' }).value)).toEqual('HELLO');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'Hello World' }).value)).toEqual('HELLO WORLD');
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: '' }).value)).toEqual('');
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { s: 'abc123' }).value)).toEqual('ABC123');
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { s: 'foo bar' }).value)).toEqual('FOO BAR');
    });
  });
});
