// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-functions / feel-functions/context', () => {
  describe('fn-context-merge', () => {
    const EXPR = 'context merge(lst)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { lst: [{ a: 1 }, { b: 2 }] }).value)).toEqual({ a: 1, b: 2 });
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { lst: [{ a: 1 }, { a: 2 }] }).value)).toEqual({ a: 2 });
    });
  });
  describe('fn-context-put-nested', () => {
    const EXPR =
      '{\n  simple_put: context put({a: 1, b: 2}, "c", 3),\n  override_key: context put({a: 1, b: 2}, "a", 99),\n  add_to_empty: context put({}, "x", 42),\n  merge_two: context merge({a: 1}, {b: 2}),\n  merge_overlap: context merge({a: 1, b: 2}, {b: 99, c: 3}),\n  get_existing: get value({a: 1, b: 2}, "a"),\n  get_missing: get value({a: 1}, "z"),\n  entries_count: count(get entries({a: 1, b: 2, c: 3}))\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        simple_put: { a: 1, b: 2, c: 3 },
        override_key: { a: 99, b: 2 },
        add_to_empty: { x: 42 },
        merge_two: { a: 1, b: 2 },
        merge_overlap: { a: 1, b: 99, c: 3 },
        get_existing: 1,
        get_missing: null,
        entries_count: 3,
      });
    });
  });
  describe('fn-context-put-path', () => {
    const EXPR =
      '{\n  put_new_key: context put({a: 1}, "b", 2),\n  put_override: context put({a: 1, b: 2}, "a", 99),\n  put_path_nested: context put({a: {b: 1}}, ["a", "b"], 99),\n  put_path_add_nested: context put({a: {b: 1}}, ["a", "c"], 42),\n  put_path_single: context put({a: 1}, ["b"], 2),\n  put_path_deep: context put({a: {b: {c: 1}}}, ["a", "b", "c"], 999),\n  merge_two: context merge([{a: 1}, {b: 2}]),\n  merge_override: context merge([{a: 1, b: 0}, {b: 2, c: 3}]),\n  merge_three: context merge([{a: 1}, {b: 2}, {c: 3}])\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        put_new_key: { a: 1, b: 2 },
        put_override: { a: 99, b: 2 },
        put_path_nested: { a: { b: 99 } },
        put_path_add_nested: { a: { b: 1, c: 42 } },
        put_path_single: { a: 1, b: 2 },
        put_path_deep: { a: { b: { c: 999 } } },
        merge_two: { a: 1, b: 2 },
        merge_override: { a: 1, b: 2, c: 3 },
        merge_three: { a: 1, b: 2, c: 3 },
      });
    });
  });
  describe('fn-context-put', () => {
    const EXPR = 'context put(m, key, val)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { m: { a: 1 }, key: 'b', val: 2 }).value)).toEqual({ a: 1, b: 2 });
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { m: { a: 1 }, key: 'a', val: 99 }).value)).toEqual({ a: 99 });
    });
  });
  describe('fn-context', () => {
    const EXPR = 'context(entries)';

    it('case 1', () => {
      expect(
        n(
          evaluate(EXPR, {
            entries: [
              { key: 'a', value: 1 },
              { key: 'b', value: 2 },
            ],
          }).value,
        ),
      ).toEqual({ a: 1, b: 2 });
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { entries: [] }).value)).toEqual({});
    });
  });
  describe('fn-get-entries', () => {
    const EXPR = 'get entries(m)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { m: { a: 1 } }).value)).toEqual([{ key: 'a', value: 1 }]);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { m: {} }).value)).toEqual([]);
    });
  });
  describe('fn-get-value', () => {
    const EXPR = 'get value(m, key)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { m: { a: 1, b: 2 }, key: 'a' }).value)).toEqual(1);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { m: { x: 'hello' }, key: 'y' }).value)).toEqual(null);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { m: {}, key: 'k' }).value)).toEqual(null);
    });
  });
  describe('fn-named-params-context', () => {
    const EXPR =
      '{\n  get_value_named: get value(m: {a: 1, b: 2}, key: "a"),\n  get_entries_named: count(get entries(m: {x: 10, y: 20})),\n  context_put_named: context put(context: {a: 1}, key: "b", value: 2),\n  context_merge_named: context merge(contexts: [{a: 1}, {b: 2}]),\n  context_named: context(entries: [{key: "k", value: 42}])\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        get_value_named: 1,
        get_entries_named: 2,
        context_put_named: { a: 1, b: 2 },
        context_merge_named: { a: 1, b: 2 },
        context_named: { k: 42 },
      });
    });
  });
});
