// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-functions / feel-functions/conversion', () => {
  describe('fn-date-conversion', () => {
    const EXPR = 'date(y, m, d)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { y: 2024, m: 6, d: 15 }).value)).toEqual('2024-06-15');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { y: 2000, m: 1, d: 1 }).value)).toEqual('2000-01-01');
    });
  });
  describe('fn-date-from-string-edge', () => {
    const EXPR =
      '{\n  iso_standard: date("2024-01-15"),\n  leap_day: date("2024-02-29"),\n  non_leap_fail: date("2023-02-29"),\n  last_of_month: date("2024-01-31"),\n  invalid_month: date("2024-13-01"),\n  null_input: date(null),\n  components: date(2024, 6, 15),\n  component_invalid: date(2024, 2, 30)\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        iso_standard: '2024-01-15',
        leap_day: '2024-02-29',
        non_leap_fail: null,
        last_of_month: '2024-01-31',
        invalid_month: null,
        null_input: null,
        components: '2024-06-15',
        component_invalid: null,
      });
    });
  });
  describe('fn-date-from-string', () => {
    const EXPR = 'date(s)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: '2024-06-15' }).value)).toEqual('2024-06-15');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: '2000-01-01' }).value)).toEqual('2000-01-01');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'invalid' }).value)).toEqual(null);
    });
  });
  describe('fn-duration-from-string', () => {
    const EXPR = 'duration(s)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: 'P1Y' }).value)).toEqual('P1Y');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'PT3H30M' }).value)).toEqual('PT3H30M');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'P1Y6M' }).value)).toEqual('P1Y6M');
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { s: 'invalid' }).value)).toEqual(null);
    });
  });
  describe('fn-number-conversion', () => {
    const EXPR = 'number(from, gs, ds)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { from: '1.000,00', gs: '.', ds: ',' }).value)).toEqual(1000);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { from: '1,000.00', gs: ',', ds: '.' }).value)).toEqual(1000);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { from: '123', gs: ' ', ds: '.' }).value)).toEqual(123);
    });
  });
  describe('fn-number-grouping-decimal', () => {
    const EXPR =
      '{\n  european_format: number("1.234,56", ".", ","),\n  us_format: number("1,234.56", ",", "."),\n  no_grouping: number("1234.56", null, "."),\n  integer_only: number("42", null, "."),\n  negative: number("-1,234.56", ",", "."),\n  invalid: number("abc", null, "."),\n  null_input: number(null, null, ".")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        european_format: 1234.56,
        us_format: 1234.56,
        no_grouping: 1234.56,
        integer_only: 42,
        negative: -1234.56,
        invalid: null,
        null_input: null,
      });
    });
  });
  describe('fn-string-conversion', () => {
    const EXPR = '{ a: string(1.5), b: string(null), c: string(true), d: string([1,2]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: '1.5', b: null, c: 'true', d: '[1, 2]' });
    });
  });
  describe('fn-string-number-format', () => {
    const EXPR =
      '{\n  integer_str: string(42),\n  negative_str: string(-7),\n  zero_str: string(0),\n  decimal_str: string(3.14),\n  small_decimal: string(0.001),\n  large_int: string(1000000),\n  bool_true: string(true),\n  bool_false: string(false),\n  null_str: string(null),\n  list_str: string([1, 2, 3]),\n  ctx_str: string({a: 1}),\n  date_str: string(date("2024-01-15")),\n  duration_str: string(duration("P1Y2M")),\n  num_from_str: number("42"),\n  num_from_decimal: number("3.14"),\n  num_negative: number("-7"),\n  num_european: number("1.234,56", ".", ","),\n  num_us: number("1,234.56", ",", ".")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        integer_str: '42',
        negative_str: '-7',
        zero_str: '0',
        decimal_str: '3.14',
        small_decimal: '0.001',
        large_int: '1000000',
        bool_true: 'true',
        bool_false: 'false',
        null_str: null,
        list_str: '[1, 2, 3]',
        ctx_str: '{a: 1}',
        date_str: '2024-01-15',
        duration_str: 'P1Y2M',
        num_from_str: 42,
        num_from_decimal: 3.14,
        num_negative: -7,
        num_european: 1234.56,
        num_us: 1234.56,
      });
    });
  });
  describe('fn-time-conversion', () => {
    const EXPR = 'time(h, min, sec)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { h: 14, min: 30, sec: 0 }).value)).toEqual('14:30:00');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { h: 0, min: 0, sec: 0 }).value)).toEqual('00:00:00');
    });
  });
  describe('fn-time-from-string', () => {
    const EXPR = 'time(s)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: '14:30:00' }).value)).toEqual('14:30:00');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: '00:00:00' }).value)).toEqual('00:00:00');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { s: 'invalid' }).value)).toEqual(null);
    });
  });
  describe('fn-years-months-duration-from-dates', () => {
    const EXPR = 'years and months duration(from, to)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { from: '2024-01-01', to: '2023-01-01' }).value)).toEqual('-P1Y');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { from: '2024-06-15', to: '2024-06-15' }).value)).toEqual('P0Y');
    });
  });
});
