// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-functions / feel-functions/error-cases', () => {
  describe('fn-err-div-by-zero', () => {
    const EXPR = 'a / 0';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: 10 }).value)).toEqual(null);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: 0 }).value)).toEqual(null);
    });
  });
  describe('fn-err-empty-list-numeric', () => {
    const EXPR = '{ a: min([]), b: max([]), c: sum([]), d: product([]), e: mean([]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: null, b: null, c: null, d: null, e: null });
    });
  });
  describe('fn-err-index-out-of-bounds', () => {
    const EXPR = '{ a: lst[10], b: lst[0], c: lst[-10] }';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { lst: [1, 2, 3] }).value)).toEqual({ a: null, b: null, c: null });
    });
  });
  describe('fn-err-log-nonpositive', () => {
    const EXPR = 'log(n)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { n: 0 }).value)).toEqual(null);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { n: -1 }).value)).toEqual(null);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { n: 1 }).value)).toEqual(0);
    });
  });
  describe('fn-err-missing-arg', () => {
    const EXPR = 'substring(s, 1)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { s: null }).value)).toEqual(null);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { s: 'hello' }).value)).toEqual('hello');
    });
  });
  describe('fn-err-null-list', () => {
    const EXPR = '{ a: count(null), b: min(null), c: max(null), d: sum(null) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: null, b: null, c: null, d: null });
    });
  });
  describe('fn-err-null-number', () => {
    const EXPR = '{ a: abs(null), b: floor(null), c: ceiling(null) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: null, b: null, c: null });
    });
  });
  describe('fn-err-null-string', () => {
    const EXPR = '{ a: string length(null), b: upper case(null), c: contains(null, "x") }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: null, b: null, c: null });
    });
  });
  describe('fn-err-sqrt-negative', () => {
    const EXPR = 'sqrt(n)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { n: -1 }).value)).toEqual(null);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { n: 4 }).value)).toEqual(2);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { n: 0 }).value)).toEqual(0);
    });
  });
  describe('fn-err-wrong-type-string', () => {
    const EXPR = 'string length(42)';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual(null);
    });
  });
  describe('fn-error-null-propagation-chain', () => {
    const EXPR =
      '{\n  substring_null: substring(null, 1),\n  upper_null: upper case(null),\n  lower_null: lower case(null),\n  contains_null_str: contains(null, "x"),\n  contains_null_sub: contains("hello", null),\n  starts_null: starts with(null, "h"),\n  ends_null: ends with(null, "o"),\n  div_zero: 1 / 0,\n  sqrt_neg: sqrt(-4),\n  index_out: [1,2,3][5],\n  index_zero: [1,2,3][0],\n  floor_null: floor(null),\n  count_null: count(null)\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        substring_null: null,
        upper_null: null,
        lower_null: null,
        contains_null_str: null,
        contains_null_sub: null,
        starts_null: null,
        ends_null: null,
        div_zero: null,
        sqrt_neg: null,
        index_out: null,
        index_zero: null,
        floor_null: null,
        count_null: null,
      });
    });
  });
  describe('fn-error-type-mismatch', () => {
    const EXPR =
      '{\n  string_len_number: string length(42),\n  floor_string: floor("hello"),\n  ceiling_bool: ceiling(true),\n  sqrt_string: sqrt("four"),\n  log_string: log("ten"),\n  abs_string: abs("negative"),\n  decimal_string: decimal("3.14", 0),\n  contains_number: contains(42, 4),\n  upper_number: upper case(42),\n  list_contains_non_list: list contains(42, 4)\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        string_len_number: null,
        floor_string: null,
        ceiling_bool: null,
        sqrt_string: null,
        log_string: null,
        abs_string: null,
        decimal_string: null,
        contains_number: null,
        upper_number: null,
        list_contains_non_list: null,
      });
    });
  });
});
