// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-functions / feel-functions/range', () => {
  describe('fn-after', () => {
    const EXPR =
      '{ a: after(6, [2..5]), b: after([6..8], [2..5]), c: after(1, [2..5]), d: after(5, [2..5]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false, d: false });
    });
  });
  describe('fn-before', () => {
    const EXPR =
      '{ a: before(1, [2..5]), b: before([1..2], [3..5]), c: before(5, [2..4]), d: before([1..3], [3..5]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false, d: false });
    });
  });
  describe('fn-coincides', () => {
    const EXPR =
      '{ a: coincides(5, 5), b: coincides([1..5], [1..5]), c: coincides(5, 4), d: coincides([1..5], [1..4]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false, d: false });
    });
  });
  describe('fn-during', () => {
    const EXPR = '{ a: during(3, [1..5]), b: during([2..4], [1..5]), c: during([1..6], [1..5]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false });
    });
  });
  describe('fn-finished-by', () => {
    const EXPR =
      '{ a: finished by([1..5], 5), b: finished by([1..5], [3..5]), c: finished by([1..5], 4) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false });
    });
  });
  describe('fn-finishes', () => {
    const EXPR =
      '{ a: finishes(5, [1..5]), b: finishes([3..5], [1..5]), c: finishes(4, [1..5]), d: finishes([1..5], [1..5]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false, d: true });
    });
  });
  describe('fn-includes', () => {
    const EXPR =
      '{ a: includes([1..5], 3), b: includes([1..5], [2..4]), c: includes([1..5], [1..6]), d: includes([1..5], 5) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false, d: true });
    });
  });
  describe('fn-meets', () => {
    const EXPR = '{ a: meets([1..3], [3..5]), b: meets([1..3), [3..5]), c: meets([1..2], [3..5]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: false, c: false });
    });
  });
  describe('fn-met-by', () => {
    const EXPR =
      '{ a: met by([3..5], [1..3]), b: met by([3..5], [1..3)), c: met by([3..5], [1..2]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: false, c: false });
    });
  });
  describe('fn-overlaps-after', () => {
    const EXPR =
      '{ a: overlaps after([2..5], [1..3]), b: overlaps after([1..5], [1..3]), c: overlaps after([1..4], [3..5]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: false, c: false });
    });
  });
  describe('fn-overlaps-before', () => {
    const EXPR =
      '{ a: overlaps before([1..3], [2..5]), b: overlaps before([1..3], [1..5]), c: overlaps before([3..5], [1..4]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: false, c: false });
    });
  });
  describe('fn-overlaps', () => {
    const EXPR =
      '{ a: overlaps([1..3], [2..5]), b: overlaps([1..3], [4..6]), c: overlaps([1..5], [2..3]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: false, c: true });
    });
  });
  describe('fn-range-edge-cases', () => {
    const EXPR =
      '{\n  before_point_range: before(1, [2..5]),\n  before_range_point: before([1..2], 3),\n  before_touching: before([1..2], [2..4]),\n  after_point_range: after(6, [2..5]),\n  meets_ranges: meets([1..3], [3..5]),\n  overlaps_true: overlaps([1..4], [3..7]),\n  overlaps_false: overlaps([1..3], [4..7]),\n  during_point: during(3, [1..5]),\n  during_equal: during([2..4], [1..5]),\n  coincides_equal: coincides([1..5], [1..5]),\n  coincides_unequal: coincides([1..5], [1..4])\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        before_point_range: true,
        before_range_point: true,
        before_touching: false,
        after_point_range: true,
        meets_ranges: true,
        overlaps_true: true,
        overlaps_false: false,
        during_point: true,
        during_equal: true,
        coincides_equal: true,
        coincides_unequal: false,
      });
    });
  });
  describe('fn-range-open-endpoints', () => {
    const EXPR =
      '{\n  before_open_left: before((1..5], [5..9]),\n  before_open_right: before([1..5), [5..9]),\n  meets_open: meets([1..5), (5..9]),\n  overlaps_before_open: overlaps before([1..5], [3..8]),\n  starts_same_start: starts([2..5], [2..8]),\n  finishes_same_end: finishes([5..8], [2..8]),\n  finished_by: finished by([2..8], [5..8]),\n  includes_point: includes([2..8], 5),\n  includes_range: includes([2..8], [4..6])\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        before_open_left: false,
        before_open_right: true,
        meets_open: false,
        overlaps_before_open: true,
        starts_same_start: true,
        finishes_same_end: true,
        finished_by: true,
        includes_point: true,
        includes_range: true,
      });
    });
  });
  describe('fn-started-by', () => {
    const EXPR =
      '{ a: started by([1..5], 1), b: started by([1..5], [1..3]), c: started by([1..5], 2) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false });
    });
  });
  describe('fn-starts', () => {
    const EXPR = '{ a: starts(1, [1..5]), b: starts([1..3], [1..5]), c: starts(2, [1..5]) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: true, b: true, c: false });
    });
  });
});
