// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-types / feel-types/string', () => {
  describe('feel-string-escape-sequences', () => {
    const EXPR =
      '{\n  newline: string length("line1\\nline2"),\n  tab: string length("a\\tb"),\n  backslash: "a\\\\b",\n  quote: "say \\"hello\\"",\n  unicode_latin: "é",\n  unicode_cjk: "中文",\n  null_escape: "\u0000" = "\u0000",\n  raw_length: string length("hello"),\n  escape_in_concat: "pre" + "\\n" + "post"\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        newline: 11,
        tab: 3,
        backslash: 'a\\b',
        quote: 'say "hello"',
        unicode_latin: 'é',
        unicode_cjk: '中文',
        null_escape: true,
        raw_length: 5,
        escape_in_concat: 'pre\npost',
      });
    });
  });
  describe('feel-string-unicode-escape', () => {
    const EXPR =
      '{\n  latin_a: "A",\n  accented_e: "é",\n  euro_sign: "€",\n  cjk_char: "中",\n  multicode: "Hello",\n  mixed: "preApost",\n  length_of_escaped: string length("中文"),\n  equals_literal: "A" = "A",\n  upper_of_escaped: upper case("hello")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        latin_a: 'A',
        accented_e: 'é',
        euro_sign: '€',
        cjk_char: '中',
        multicode: 'Hello',
        mixed: 'preApost',
        length_of_escaped: 2,
        equals_literal: true,
        upper_of_escaped: 'HELLO',
      });
    });
  });
  describe('feel-string-unicode-semantics', () => {
    const EXPR =
      '{\n  emoji_length: string length("😀"),\n  emoji_mixed_length: string length("a😀b"),\n  cjk_length: string length("中文字"),\n  accented_nfc_length: string length("é"),\n  upper_ascii: upper case("hello"),\n  lower_ascii: lower case("HELLO"),\n  upper_accented: upper case("café"),\n  substring_cjk: substring("中文字", 2, 1),\n  substring_emoji: substring("😀abc", 1, 1),\n  substring_after_cjk: substring("中文字", 2),\n  concat_unicode: "pre" + "中" + "post",\n  contains_unicode: contains("hello世界", "世界"),\n  ends_with_emoji: ends with("hi😀", "😀")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        emoji_length: 1,
        emoji_mixed_length: 3,
        cjk_length: 3,
        accented_nfc_length: 1,
        upper_ascii: 'HELLO',
        lower_ascii: 'hello',
        upper_accented: 'CAFÉ',
        substring_cjk: '文',
        substring_emoji: '😀',
        substring_after_cjk: '文字',
        concat_unicode: 'pre中post',
        contains_unicode: true,
        ends_with_emoji: true,
      });
    });
  });
  describe('ft-string-comparison-lt', () => {
    const EXPR = 'a < b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: 'apple', b: 'banana' }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: 'z', b: 'a' }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: 'abc', b: 'abc' }).value)).toEqual(false);
    });
  });
  describe('ft-string-concat-number', () => {
    const EXPR = 'string(a) + " units"';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: 42 }).value)).toEqual('42 units');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: 0 }).value)).toEqual('0 units');
    });
  });
  describe('ft-string-concat', () => {
    const EXPR = 'a + b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: 'hello', b: ' world' }).value)).toEqual('hello world');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: '', b: 'x' }).value)).toEqual('x');
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: 'a', b: 'b' }).value)).toEqual('ab');
    });
  });
  describe('ft-string-empty', () => {
    const EXPR = 'a = ""';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: '' }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: ' ' }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: 'x' }).value)).toEqual(false);
    });
  });
  describe('ft-string-equality', () => {
    const EXPR = 'a = b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: 'foo', b: 'foo' }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: 'foo', b: 'FOO' }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: '', b: '' }).value)).toEqual(true);
    });
  });
  describe('ft-string-escape-newline', () => {
    const EXPR = '"line1\\nline2"';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual('line1\nline2');
    });
  });
  describe('ft-string-escape-quote', () => {
    const EXPR = '"say \\"hi\\""';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual('say "hi"');
    });
  });
  describe('ft-string-escape-tab', () => {
    const EXPR = '"col1\\tcol2"';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual('col1\tcol2');
    });
  });
  describe('ft-string-literal', () => {
    const EXPR = '"hello"';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual('hello');
    });
  });
  describe('ft-string-multiline', () => {
    const EXPR = 'a + "\\n" + a';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: 'hi' }).value)).toEqual('hi\nhi');
    });
  });
  describe('ft-string-null-concat', () => {
    const EXPR = 'a + b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: 'hello', b: null }).value)).toEqual(null);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: 'hello', b: ' world' }).value)).toEqual('hello world');
    });
  });
  describe('ft-string-unicode', () => {
    const EXPR = '"ABC"';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual('ABC');
    });
  });
});
