// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-types / feel-types/boolean', () => {
  describe('feel-instance-of-primitives', () => {
    const EXPR =
      '{\n  number_check: 42 instance of number,\n  string_check: "hello" instance of string,\n  bool_check: true instance of boolean,\n  false_check: false instance of boolean,\n  date_check: @"2024-01-15" instance of date,\n  time_check: @"09:30:00" instance of time,\n  dt_check: @"2024-01-15T09:00:00" instance of date and time,\n  dt_duration_check: duration("P1DT2H") instance of days and time duration,\n  ym_duration_check: duration("P1Y2M") instance of years and months duration\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        number_check: true,
        string_check: true,
        bool_check: true,
        false_check: true,
        date_check: true,
        time_check: true,
        dt_check: true,
        dt_duration_check: true,
        ym_duration_check: true,
      });
    });
  });
  describe('feel-no-type-coercion', () => {
    const EXPR =
      '{\n  string_num_eq: "5" = 5,\n  num_string_eq: 5 = "5",\n  string_zero_eq: "0" = 0,\n  bool_num_eq: true = 1,\n  bool_zero_eq: false = 0,\n  date_string_eq: date("2024-01-15") = "2024-01-15",\n  explicit_string_concat: string(5) + "0",\n  explicit_num_from_string: number("5") + 1,\n  null_equals_null: null = null,\n  null_equals_missing: null = {a: 1}.b\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        string_num_eq: null,
        num_string_eq: null,
        string_zero_eq: null,
        bool_num_eq: null,
        bool_zero_eq: null,
        date_string_eq: null,
        explicit_string_concat: '50',
        explicit_num_from_string: 6,
        null_equals_null: true,
        null_equals_missing: true,
      });
    });
  });
  describe('ft-boolean-and', () => {
    const EXPR = 'a and b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: true, b: true }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: true, b: false }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: false, b: false }).value)).toEqual(false);
    });
  });
  describe('ft-boolean-literal-false', () => {
    const EXPR = 'false';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual(false);
    });
  });
  describe('ft-boolean-literal-true', () => {
    const EXPR = 'true';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual(true);
    });
  });
  describe('ft-boolean-not', () => {
    const EXPR = 'not(a)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: true }).value)).toEqual(false);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: false }).value)).toEqual(true);
    });
  });
  describe('ft-boolean-null-and', () => {
    const EXPR = 'a and null';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: true }).value)).toEqual(null);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: false }).value)).toEqual(false);
    });
  });
  describe('ft-boolean-null-or', () => {
    const EXPR = 'a or null';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: true }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: false }).value)).toEqual(null);
    });
  });
  describe('ft-boolean-or', () => {
    const EXPR = 'a or b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: true, b: false }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: false, b: false }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: true, b: true }).value)).toEqual(true);
    });
  });
  describe('ft-boolean-short-circuit', () => {
    const EXPR = 'a or b and c';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: false, b: true, c: true }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: false, b: true, c: false }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: true, b: false, c: false }).value)).toEqual(true);
    });
  });
});
