// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-types / feel-types/list', () => {
  describe('feel-filter-scalar-coercion', () => {
    const EXPR =
      '{\n  scalar_filter_pass: 5[item > 3],\n  scalar_filter_fail: 5[item > 10],\n  string_filter: "hello"[item = "hello"],\n  scalar_count: count(42),\n  scalar_in_list: count([42]),\n  null_count: count([null]),\n  sum_singleton: sum(5),\n  max_singleton: max(10),\n  mean_singleton: mean(7),\n  list_filter_index: [10, 20, 30][2],\n  list_filter_negative: [10, 20, 30][-1],\n  list_filter_pred: [1, 2, 3, 4][item > 2],\n  nested_filter: [[1, 2], [3, 4], [5, 6]][sum(item) > 5]\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        scalar_filter_pass: [5],
        scalar_filter_fail: [],
        string_filter: ['hello'],
        scalar_count: 1,
        scalar_in_list: 1,
        null_count: 1,
        sum_singleton: 5,
        max_singleton: 10,
        mean_singleton: 7,
        list_filter_index: 20,
        list_filter_negative: 30,
        list_filter_pred: [3, 4],
        nested_filter: [
          [3, 4],
          [5, 6],
        ],
      });
    });
  });
  describe('feel-for-iteration-edge', () => {
    const EXPR =
      '{\n  ascending_range: for i in 1..5 return i,\n  descending_range: for i in 5..1 return i,\n  range_same_bounds: for i in 3..3 return i,\n  multi_iterator_order: for i in [1, 2], j in [10, 20] return i + j,\n  multi_iterator_3: for i in [1, 2], j in ["a", "b"] return string(i) + j,\n  for_filter_combo: for x in [1, 2, 3, 4, 5] return if x > 2 then x * 10 else x,\n  for_over_empty: for x in [] return x * 2,\n  for_nested: for i in 1..3 return for j in 1..3 return i * j,\n  for_with_filter_then: (for x in [1, 2, 3, 4, 5] return x * 2)[item > 4],\n  cartesian_size: count(for i in 1..3, j in 1..3, k in 1..3 return i * j * k)\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        ascending_range: [1, 2, 3, 4, 5],
        descending_range: [5, 4, 3, 2, 1],
        range_same_bounds: [3],
        multi_iterator_order: [11, 21, 12, 22],
        multi_iterator_3: ['1a', '1b', '2a', '2b'],
        for_filter_combo: [1, 2, 30, 40, 50],
        for_over_empty: [],
        for_nested: [
          [1, 2, 3],
          [2, 4, 6],
          [3, 6, 9],
        ],
        for_with_filter_then: [6, 8, 10],
        cartesian_size: 27,
      });
    });
  });
  describe('feel-list-coercion-filter', () => {
    const EXPR =
      '{\n  scalar_index_1: "hello"[1],\n  list_index_1: ["a","b","c"][1],\n  list_index_2: ["a","b","c"][2],\n  list_index_last: ["a","b","c"][-1],\n  scalar_filter_eq: "hello"[item = "hello"],\n  list_filter_eq: ["a","b","c"][item = "b"]\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        scalar_index_1: 'hello',
        list_index_1: 'a',
        list_index_2: 'b',
        list_index_last: 'c',
        scalar_filter_eq: ['hello'],
        list_filter_eq: ['b'],
      });
    });
  });
  describe('feel-list-coercion-quantifiers', () => {
    const EXPR =
      '{\n  some_scalar_true: some x in "hello" satisfies x = "hello",\n  some_scalar_false: some x in "hello" satisfies x = "world",\n  every_scalar_true: every x in "hello" satisfies x = "hello",\n  every_scalar_false: every x in "hello" satisfies x = "world",\n  some_number: some x in 42 satisfies x > 40,\n  every_number: every x in 42 satisfies x > 40\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        some_scalar_true: true,
        some_scalar_false: false,
        every_scalar_true: true,
        every_scalar_false: false,
        some_number: true,
        every_number: true,
      });
    });
  });
  describe('feel-list-for-multi-iterator', () => {
    const EXPR =
      '{\n  two_number_lists: for i in [1, 2], j in [10, 20] return i + j,\n  string_product: for x in ["a", "b"], y in ["1", "2"] return x + y,\n  three_iterators: for a in [1, 2], b in [3], c in [10, 20] return a + b + c,\n  single_pair: for i in [5], j in [3] return i * j\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        two_number_lists: [11, 21, 12, 22],
        string_product: ['a1', 'a2', 'b1', 'b2'],
        three_iterators: [14, 24, 15, 25],
        single_pair: [15],
      });
    });
  });
  describe('feel-list-for-nested', () => {
    const EXPR =
      '{\n  nested_for: for i in [1, 2] return (for j in [10, 20] return i + j),\n  for_then_filter: (for i in [1, 2, 3, 4, 5] return i * i)[item > 10],\n  for_to_sum: sum(for i in [1, 2, 3, 4, 5] return i),\n  map_and_count: count(for x in ["a", "bb", "ccc"] return string length(x))\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        nested_for: [
          [11, 21],
          [12, 22],
        ],
        for_then_filter: [16, 25],
        for_to_sum: 15,
        map_and_count: 3,
      });
    });
  });
  describe('feel-list-for-partial-iteration', () => {
    const EXPR =
      '{\n  range_double: for i in 1..5 return i * 2,\n  range_identity: for i in 1..5 return i,\n  conditional_in_for: for i in 1..4 return if i > 2 then i * 10 else i,\n  range_squares: for i in 1..4 return i * i,\n  range_single: for i in 3..3 return i\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        range_double: [2, 4, 6, 8, 10],
        range_identity: [1, 2, 3, 4, 5],
        conditional_in_for: [1, 2, 30, 40],
        range_squares: [1, 4, 9, 16],
        range_single: [3],
      });
    });
  });
  describe('feel-list-for-partial', () => {
    const EXPR =
      '{\n  cumulative_sum: for i in 1..5 return if i = 1 then 1 else partial[-1] + i,\n  fibonacci: for i in 1..8 return if i = 1 then 1 else if i = 2 then 1 else partial[-1] + partial[-2],\n  running_max: for x in [3, 1, 4, 1, 5, 9, 2, 6] return if count(partial) = 0 then x else max(partial[-1], x)\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        cumulative_sum: [1, 3, 6, 10, 15],
        fibonacci: [1, 1, 2, 3, 5, 8, 13, 21],
        running_max: [3, 3, 4, 4, 5, 9, 9, 9],
      });
    });
  });
  describe('feel-list-path-expression', () => {
    const EXPR =
      '{\n  simple_path: [{a: 1, b: 2}, {a: 3, b: 4}].a,\n  nested_path: [{p: {q: 10}}, {p: {q: 20}}].p.q,\n  three_elements: [{a: 1}, {a: 2}, {a: 3}].a,\n  single_element: [{x: 42}].x,\n  two_keys: [{a: 1, b: 10}, {a: 2, b: 20}].b,\n  path_with_filter: [{a: 1}, {a: 2}, {a: 3}].a[item > 1]\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        simple_path: [1, 3],
        nested_path: [10, 20],
        three_elements: [1, 2, 3],
        single_element: [42],
        two_keys: [10, 20],
        path_with_filter: [2, 3],
      });
    });
  });
  describe('feel-list-path-null-propagation', () => {
    const EXPR =
      '{\n  missing_key: [{a: 1}, {b: 2}].a,\n  all_missing: [{b: 1}, {b: 2}].a,\n  null_value: [{a: null}, {a: 5}].a,\n  partial_missing: [{a: 1}, {a: 2}, {b: 3}].a\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        missing_key: [1, null],
        all_missing: [null, null],
        null_value: [null, 5],
        partial_missing: [1, 2, null],
      });
    });
  });
  describe('feel-list-quantifier-empty', () => {
    const EXPR =
      '{\n  some_empty_true: some x in [] satisfies true,\n  some_empty_false: some x in [] satisfies false,\n  some_empty_expr: some x in [] satisfies x > 0,\n  every_empty_true: every x in [] satisfies true,\n  every_empty_false: every x in [] satisfies false,\n  every_empty_expr: every x in [] satisfies x > 0,\n  some_nonempty_false: some x in [1, 2, 3] satisfies x > 10,\n  some_nonempty_true: some x in [1, 2, 3] satisfies x > 2,\n  every_nonempty_true: every x in [1, 2, 3] satisfies x > 0,\n  every_nonempty_false: every x in [1, 2, 3] satisfies x > 1,\n  some_with_null: some x in [null, null] satisfies x = null,\n  every_with_null: every x in [1, null, 3] satisfies x > 0\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        some_empty_true: false,
        some_empty_false: false,
        some_empty_expr: false,
        every_empty_true: true,
        every_empty_false: true,
        every_empty_expr: true,
        some_nonempty_false: false,
        some_nonempty_true: true,
        every_nonempty_true: true,
        every_nonempty_false: false,
        some_with_null: true,
        every_with_null: null,
      });
    });
  });
  describe('feel-list-singleton-coercion', () => {
    const EXPR =
      '{\n  count_string: count("hello"),\n  count_number: count(42),\n  count_bool: count(true),\n  list_contains_scalar: list contains("hello", "hello"),\n  list_contains_not: list contains("hello", "world"),\n  append_scalar: append("x", "y"),\n  count_equals: count(["hello"]) = count("hello"),\n  list_contains_list_vs_scalar: list contains([1,2,3], 2)\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        count_string: 1,
        count_number: 1,
        count_bool: 1,
        list_contains_scalar: null,
        list_contains_not: null,
        append_scalar: ['x', 'y'],
        count_equals: true,
        list_contains_list_vs_scalar: true,
      });
    });
  });
  describe('ft-list-access-filter', () => {
    const EXPR = 'a[item > 5]';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: [1, 5, 10, 3, 8] }).value)).toEqual([10, 8]);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: [1, 2, 3] }).value)).toEqual([]);
    });
  });
  describe('ft-list-access-index', () => {
    const EXPR = 'a[1]';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: [10, 20, 30] }).value)).toEqual(10);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: ['x', 'y'] }).value)).toEqual('x');
    });
  });
  describe('ft-list-access-negative', () => {
    const EXPR = 'a[-1]';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: [10, 20, 30] }).value)).toEqual(30);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: ['x', 'y', 'z'] }).value)).toEqual('z');
    });
  });
  describe('ft-list-concat', () => {
    const EXPR = 'concatenate(a, b)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: [1, 2], b: [3, 4] }).value)).toEqual([1, 2, 3, 4]);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: [], b: [1] }).value)).toEqual([1]);
    });
  });
  describe('ft-list-empty', () => {
    const EXPR = '[]';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual([]);
    });
  });
  describe('ft-list-equality', () => {
    const EXPR = 'a = b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: [1, 2, 3], b: [1, 2, 3] }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: [1, 2], b: [1, 3] }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: [], b: [] }).value)).toEqual(true);
    });
  });
  describe('ft-list-every', () => {
    const EXPR = 'every x in a satisfies x > 0';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: [1, 2, 3] }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: [1, -1, 3] }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: [] }).value)).toEqual(true);
    });
  });
  describe('ft-list-in', () => {
    const EXPR = 'a in b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: 5, b: [1, 5, 10] }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: 4, b: [1, 5, 10] }).value)).toEqual(false);
    });
  });
  describe('ft-list-literal', () => {
    const EXPR = '[1, 2, 3]';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual([1, 2, 3]);
    });
  });
  describe('ft-list-nested', () => {
    const EXPR = '[[1,2],[3,4]]';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual([
        [1, 2],
        [3, 4],
      ]);
    });
  });
  describe('ft-list-null', () => {
    const EXPR = 'a[10]';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: [1, 2, 3] }).value)).toEqual(null);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: [1] }).value)).toEqual(null);
    });
  });
  describe('ft-list-some', () => {
    const EXPR = 'some x in a satisfies x > 5';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: [1, 3, 7] }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: [1, 2, 3] }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: [] }).value)).toEqual(false);
    });
  });
});
