// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { parseDuration } from '../../src/temporal/duration.js';
import { parseDate, parseDateTime, parseTime } from '../../src/temporal/index.js';
import { n } from '../tck/utils.js';

const d = parseDate,
  t = parseTime,
  dt = parseDateTime,
  _dur = parseDuration;

describe('dmn-fixtures / feel-types / feel-types/date', () => {
  describe('feel-at-literal-arithmetic', () => {
    const EXPR =
      '{\n  at_date_plus_duration: @"2024-01-15" + @"P5D",\n  at_date_minus_duration: @"2024-01-20" - @"P5D",\n  at_datetime_plus_duration: @"2024-01-15T09:00:00" + @"PT2H",\n  at_datetime_minus_duration: @"2024-01-15T09:00:00" - @"P1D",\n  at_time_plus_duration: @"09:00:00" + @"PT30M",\n  at_duration_plus_duration: @"P1Y" + @"P6M",\n  at_duration_mul_number: @"P1D" * 3,\n  at_date_eq_constructor: @"2024-01-15" = date("2024-01-15"),\n  at_datetime_comparison: @"2024-01-15T09:00:00" < @"2024-01-15T10:00:00",\n  at_duration_comparison: @"P1Y" > @"P6M",\n  at_in_range: @"2024-06-15" in [@"2024-01-01"..@"2024-12-31"]\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        at_date_plus_duration: '2024-01-20',
        at_date_minus_duration: '2024-01-15',
        at_datetime_plus_duration: '2024-01-15T11:00:00',
        at_datetime_minus_duration: '2024-01-14T09:00:00',
        at_time_plus_duration: '09:30:00',
        at_duration_plus_duration: 'P1Y6M',
        at_duration_mul_number: 'P3D',
        at_date_eq_constructor: true,
        at_datetime_comparison: true,
        at_duration_comparison: true,
        at_in_range: true,
      });
    });
  });
  describe('feel-date-arithmetic-invariants', () => {
    const EXPR =
      '{\n  month_then_day: (date("2024-03-30") + duration("P1M")) + duration("P1D"),\n  day_then_month: (date("2024-03-30") + duration("P1D")) + duration("P1M"),\n  date_vs_datetime: date("2024-01-15") = date and time("2024-01-15T00:00:00"),\n  date_to_datetime: date and time(date("2024-01-15"), time("00:00:00")) = date and time("2024-01-15T00:00:00"),\n  naive_vs_tz_add: date and time("2024-01-15T12:00:00") = date and time("2024-01-15T12:00:00Z"),\n  dst_summer: date and time("2024-07-15T12:00:00@Europe/London"),\n  dst_winter: date and time("2024-01-15T12:00:00@Europe/London"),\n  feb29_plus_1y: date("2024-02-29") + duration("P1Y"),\n  feb29_plus_4y: date("2024-02-29") + duration("P4Y"),\n  jan31_minus_p1m: date("2024-03-31") - duration("P1M")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        month_then_day: '2024-05-01',
        day_then_month: '2024-04-30',
        date_vs_datetime: false,
        date_to_datetime: true,
        naive_vs_tz_add: false,
        dst_summer: '2024-07-15T12:00:00@Europe/London',
        dst_winter: '2024-01-15T12:00:00@Europe/London',
        feb29_plus_1y: '2025-02-28',
        feb29_plus_4y: '2028-02-29',
        jan31_minus_p1m: '2024-02-29',
      });
    });
  });
  describe('feel-date-month-end', () => {
    const EXPR =
      '{\n    jan31_plus_1m: date("2024-01-31") + duration("P1M"),\n    jan31_plus_1m_nonleap: date("2023-01-31") + duration("P1M"),\n    mar31_plus_1m: date("2024-03-31") + duration("P1M"),\n    jan31_plus_2m: date("2024-01-31") + duration("P2M"),\n    jan28_plus_1m: date("2024-01-28") + duration("P1M"),\n    feb29_plus_1y: date("2024-02-29") + duration("P1Y"),\n    feb29_plus_4y: date("2024-02-29") + duration("P4Y"),\n    jan31_minus_1m: date("2024-03-31") - duration("P1M"),\n    dec31_plus_1d: date("2024-12-31") + duration("P1D"),\n    feb28_nonleap_plus_1d: date("2023-02-28") + duration("P1D")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        jan31_plus_1m: '2024-02-29',
        jan31_plus_1m_nonleap: '2023-02-28',
        mar31_plus_1m: '2024-04-30',
        jan31_plus_2m: '2024-03-31',
        jan28_plus_1m: '2024-02-28',
        feb29_plus_1y: '2025-02-28',
        feb29_plus_4y: '2028-02-29',
        jan31_minus_1m: '2024-02-29',
        dec31_plus_1d: '2025-01-01',
        feb28_nonleap_plus_1d: '2023-03-01',
      });
    });
  });
  describe('feel-date-timezone-boundary', () => {
    const EXPR =
      '{\n  date_year: @"2024-03-15".year,\n  date_month: @"2024-03-15".month,\n  date_day: @"2024-03-15".day,\n  date_no_offset: @"2024-03-15".time offset,\n  date_self_equal: @"2024-03-15" = @"2024-03-15",\n  date_before: @"2024-01-01" < @"2024-12-31"\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        date_year: 2024,
        date_month: 3,
        date_day: 15,
        date_no_offset: null,
        date_self_equal: true,
        date_before: true,
      });
    });
  });
  describe('feel-datetime-timezone-comparison', () => {
    const EXPR = 'DT = @"2024-01-15T06:00:00+00:00"';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { DT: dt('2024-01-15T09:00:00+03:00') }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { DT: dt('2024-01-15T06:00:00Z') }).value)).toEqual(true);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { DT: dt('2024-01-15T07:00:00+01:00') }).value)).toEqual(true);
    });
    it('case 4', () => {
      expect(n(evaluate(EXPR, { DT: dt('2024-01-15T01:00:00-05:00') }).value)).toEqual(true);
    });
    it('case 5', () => {
      expect(n(evaluate(EXPR, { DT: dt('2024-01-15T12:00:00+06:00') }).value)).toEqual(true);
    });
    it('case 6', () => {
      expect(n(evaluate(EXPR, { DT: dt('2024-01-15T09:00:00+01:00') }).value)).toEqual(false);
    });
    it('case 7', () => {
      expect(n(evaluate(EXPR, { DT: dt('2024-01-15T09:00:00Z') }).value)).toEqual(false);
    });
    it('case 8', () => {
      expect(n(evaluate(EXPR, { DT: dt('2024-01-15T05:59:59Z') }).value)).toEqual(false);
    });
  });
  describe('feel-datetime-timezone-iana', () => {
    const EXPR =
      '{\n  paris_winter_eq_offset: @"2024-01-15T09:00:00@Europe/Paris" = @"2024-01-15T08:00:00+00:00",\n  paris_hour: @"2024-01-15T09:30:00@Europe/Paris".hour,\n  tokyo_eq_offset: @"2024-07-15T09:00:00@Asia/Tokyo" = @"2024-07-15T00:00:00+00:00",\n  ny_winter_eq_offset: @"2024-01-15T12:00:00@America/New_York" = @"2024-01-15T17:00:00+00:00",\n  paris_summer_dst: @"2024-07-15T09:00:00@Europe/Paris" = @"2024-07-15T07:00:00+00:00"\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        paris_winter_eq_offset: true,
        paris_hour: 9,
        tokyo_eq_offset: true,
        ny_winter_eq_offset: true,
        paris_summer_dst: true,
      });
    });
  });
  describe('feel-datetime-timezone-offset', () => {
    const EXPR =
      '{\n  same_instant: @"2024-01-15T09:00:00+03:00" = @"2024-01-15T06:00:00+00:00",\n  not_same: @"2024-01-15T09:00:00+00:00" = @"2024-01-15T09:00:00+03:00",\n  earlier: @"2024-01-15T06:00:00+03:00" < @"2024-01-15T06:00:00+00:00",\n  later: @"2024-01-15T09:00:00+00:00" > @"2024-01-15T09:00:00+03:00",\n  hour: @"2024-01-15T14:30:00+05:00".hour,\n  minute: @"2024-01-15T14:30:00+05:00".minute\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        same_instant: true,
        not_same: false,
        earlier: true,
        later: true,
        hour: 14,
        minute: 30,
      });
    });
  });
  describe('feel-datetime-timezone-utc', () => {
    const EXPR =
      '{\n  z_eq_zero_offset: @"2024-06-01T12:00:00Z" = @"2024-06-01T12:00:00+00:00",\n  z_hour: @"2024-06-01T15:30:00Z".hour,\n  z_minute: @"2024-06-01T15:30:00Z".minute,\n  plus_one_before_z: @"2024-06-01T12:00:00+01:00" < @"2024-06-01T12:00:00Z",\n  minus_one_after_z: @"2024-06-01T12:00:00Z" < @"2024-06-01T12:00:00-01:00",\n  z_year: @"2024-06-01T12:00:00Z".year\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        z_eq_zero_offset: true,
        z_hour: 15,
        z_minute: 30,
        plus_one_before_z: true,
        minus_one_after_z: true,
        z_year: 2024,
      });
    });
  });
  describe('feel-temporal-arithmetic', () => {
    const EXPR =
      '{\n  date_plus_ym_duration: date("2024-01-15") + duration("P1Y"),\n  date_minus_ym_duration: date("2024-01-15") - duration("P1M"),\n  date_plus_dt_duration: date("2024-01-15") + duration("P5D"),\n  date_minus_dt_duration: date("2024-01-15") - duration("P5D"),\n  datetime_plus_dt_duration: date and time("2024-01-15T09:00:00") + duration("PT2H"),\n  datetime_minus_dt_duration: date and time("2024-01-15T09:00:00") - duration("P1D"),\n  datetime_plus_ym_duration: date and time("2024-01-15T09:00:00") + duration("P1Y"),\n  datetime_minus_datetime: date and time("2024-01-15T11:00:00") - date and time("2024-01-15T09:00:00"),\n  time_plus_dt_duration: time("09:00:00") + duration("PT2H30M"),\n  time_minus_dt_duration: time("09:00:00") - duration("PT30M"),\n  date_minus_date: date("2024-06-15") - date("2024-01-15")\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        date_plus_ym_duration: '2025-01-15',
        date_minus_ym_duration: '2023-12-15',
        date_plus_dt_duration: '2024-01-20',
        date_minus_dt_duration: '2024-01-10',
        datetime_plus_dt_duration: '2024-01-15T11:00:00',
        datetime_minus_dt_duration: '2024-01-14T09:00:00',
        datetime_plus_ym_duration: '2025-01-15T09:00:00',
        datetime_minus_datetime: 'PT2H',
        time_plus_dt_duration: '11:30:00',
        time_minus_dt_duration: '08:30:00',
        date_minus_date: 'P152D',
      });
    });
  });
  describe('feel-time-timezone-offset', () => {
    const EXPR =
      '{\n  equal_times: @"09:00:00+03:00" = @"06:00:00+00:00",\n  not_equal_times: @"09:00:00+03:00" = @"09:00:00+00:00",\n  time_before: @"06:00:00+03:00" < @"06:00:00+00:00",\n  time_hour: @"14:30:00+05:00".hour,\n  time_minute: @"14:30:00+05:00".minute,\n  time_utc_hour: @"14:30:00+00:00".hour\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        equal_times: true,
        not_equal_times: false,
        time_before: true,
        time_hour: 14,
        time_minute: 30,
        time_utc_hour: 14,
      });
    });
  });
  describe('ft-date-add-duration', () => {
    const EXPR = 'a + duration("P1Y")';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: d('2023-01-01') }).value)).toEqual('2024-01-01');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: d('2024-02-29') }).value)).toEqual('2025-02-28');
    });
  });
  describe('ft-date-comparison', () => {
    const EXPR = 'a < b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: d('2023-12-31'), b: d('2024-01-01') }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: d('2024-06-01'), b: d('2024-01-01') }).value)).toEqual(false);
    });
  });
  describe('ft-date-equality', () => {
    const EXPR = 'a = b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: d('2024-01-01'), b: d('2024-01-01') }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: d('2024-01-01'), b: d('2024-01-02') }).value)).toEqual(false);
    });
  });
  describe('ft-date-literal', () => {
    const EXPR = 'date("2024-06-15")';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual('2024-06-15');
    });
  });
  describe('ft-date-month-day', () => {
    const EXPR = '{ month: month(a), day: day(a) }';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: d('2024-06-15') }).value)).toEqual({ month: 6, day: 15 });
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: d('2024-01-01') }).value)).toEqual({ month: 1, day: 1 });
    });
  });
  describe('ft-date-sub-date', () => {
    const EXPR = 'a - b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: d('2025-01-01'), b: d('2024-01-01') }).value)).toEqual('P366D');
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: d('2024-07-01'), b: d('2024-01-01') }).value)).toEqual('P182D');
    });
  });
  describe('ft-date-year', () => {
    const EXPR = 'year(a)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: d('2024-06-15') }).value)).toEqual(2024);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: d('1999-12-31') }).value)).toEqual(1999);
    });
  });
  describe('ft-datetime-comparison', () => {
    const EXPR = 'a < b';

    it('case 1', () => {
      expect(
        n(evaluate(EXPR, { a: dt('2024-01-01T00:00:00'), b: dt('2024-06-01T00:00:00') }).value),
      ).toEqual(true);
    });
  });
  describe('ft-datetime-date-part', () => {
    const EXPR = 'date(a)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: dt('2024-06-15T14:30:00') }).value)).toEqual('2024-06-15');
    });
  });
  describe('ft-datetime-literal', () => {
    const EXPR = 'date and time("2024-06-15T14:30:00")';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual('2024-06-15T14:30:00');
    });
  });
  describe('ft-datetime-time-part', () => {
    const EXPR = 'time(a)';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: dt('2024-06-15T14:30:00') }).value)).toEqual('14:30:00');
    });
  });
  describe('ft-time-comparison', () => {
    const EXPR = 'a < b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: t('08:00:00'), b: t('09:00:00') }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: t('12:00:00'), b: t('11:00:00') }).value)).toEqual(false);
    });
  });
  describe('ft-time-equality', () => {
    const EXPR = 'a = b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: t('09:00:00'), b: t('09:00:00') }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: t('09:00:00'), b: t('10:00:00') }).value)).toEqual(false);
    });
  });
  describe('ft-time-literal', () => {
    const EXPR = 'time("14:30:00")';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual('14:30:00');
    });
  });
});
