// Auto-generated by scripts/gen-tck.ts — do not edit manually
import { describe, expect, it } from 'vitest';
import { evaluate } from '../../src/index.js';
import { n } from '../tck/utils.js';

describe('dmn-fixtures / feel-types / feel-types/context', () => {
  describe('feel-context-edge-cases', () => {
    const EXPR =
      '{\n  missing_key: {a: 1}.b,\n  missing_nested: {a: {b: 1}}.a.c,\n  empty_context: count(get entries({})),\n  empty_equal: {} = {},\n  sibling_reference: {a: 1, b: a + 1, c: b * 2}.c,\n  sibling_chain: {x: 10, y: x * 2, z: x + y}.z,\n  nested_refs: {outer: 10, inner: {x: outer + 1}}.inner.x,\n  function_entry_ref: {base: 5, add_base: function(n) n + base, result: add_base(10)}.result,\n  sibling_with_list: {items: [1, 2, 3], total: sum(items)}.total,\n  get_entries_structure: get entries({a: 1, b: 2})\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        missing_key: null,
        missing_nested: null,
        empty_context: 0,
        empty_equal: true,
        sibling_reference: 4,
        sibling_chain: 30,
        nested_refs: 11,
        function_entry_ref: 15,
        sibling_with_list: 6,
        get_entries_structure: [
          { key: 'a', value: 1 },
          { key: 'b', value: 2 },
        ],
      });
    });
  });
  describe('feel-context-function-entry', () => {
    const EXPR =
      '{\n  simple_invoke: {f: function(x) x * 2, result: f(5)}.result,\n  multi_entry: {\n    double: function(x) x * 2,\n    triple: function(x) x * 3,\n    d: double(4),\n    t: triple(4),\n    sum: double(4) + triple(4)\n  }.sum,\n  higher_order: {\n    apply: function(f, x) f(x),\n    double: function(x) x * 2,\n    result: apply(function(x) x * 2, 7)\n  }.result,\n  closure_like: {\n    base: 10,\n    add_base: function(x) x + 10,\n    result: add_base(5)\n  }.result,\n  chained: {\n    f: function(x) x + 1,\n    g: function(x) x * 2,\n    result: g(f(3))\n  }.result\n}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({
        simple_invoke: 10,
        multi_entry: 20,
        higher_order: 14,
        closure_like: 15,
        chained: 8,
      });
    });
  });
  describe('ft-context-access-key', () => {
    const EXPR = 'a.name';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: { name: 'Alice', age: 30 } }).value)).toEqual('Alice');
    });
  });
  describe('ft-context-access-nested', () => {
    const EXPR = 'a.address.city';

    it('case 1', () => {
      expect(
        n(evaluate(EXPR, { a: { address: { city: 'São Paulo', country: 'BR' } } }).value),
      ).toEqual('São Paulo');
    });
  });
  describe('ft-context-empty', () => {
    const EXPR = '{}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({});
    });
  });
  describe('ft-context-entry-override', () => {
    const EXPR = '{a: 1, b: a + 10}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: 1, b: 11 });
    });
  });
  describe('ft-context-equality', () => {
    const EXPR = 'a = b';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: { x: 1 }, b: { x: 1 } }).value)).toEqual(true);
    });
    it('case 2', () => {
      expect(n(evaluate(EXPR, { a: { x: 1 }, b: { x: 2 } }).value)).toEqual(false);
    });
    it('case 3', () => {
      expect(n(evaluate(EXPR, { a: {}, b: {} }).value)).toEqual(true);
    });
  });
  describe('ft-context-filter', () => {
    const EXPR = 'items[x > 1]';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { items: [{ x: 1 }, { x: 2 }, { x: 3 }] }).value)).toEqual([
        { x: 2 },
        { x: 3 },
      ]);
    });
  });
  describe('ft-context-function', () => {
    const EXPR = '{ double: function(x) x * 2, result: double(5) }.result';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual(10);
    });
  });
  describe('ft-context-in-list', () => {
    const EXPR = '[{x: 1}, {x: 2}, {x: 3}]';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual([{ x: 1 }, { x: 2 }, { x: 3 }]);
    });
  });
  describe('ft-context-key-with-space', () => {
    const EXPR = 'a."full name"';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: { 'full name': 'Alice Smith' } }).value)).toEqual('Alice Smith');
    });
  });
  describe('ft-context-literal', () => {
    const EXPR = '{a: 1, b: "hello"}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ a: 1, b: 'hello' });
    });
  });
  describe('ft-context-null-access', () => {
    const EXPR = 'a.missing';

    it('case 1', () => {
      expect(n(evaluate(EXPR, { a: { name: 'Alice' } }).value)).toEqual(null);
    });
  });
  describe('ft-context-with-list', () => {
    const EXPR = '{items: [1, 2, 3], count: count([1, 2, 3])}';

    it('case 1', () => {
      expect(n(evaluate(EXPR).value)).toEqual({ items: [1, 2, 3], count: 3 });
    });
  });
});
